### ISSUE TITLE
Yeelight stays at around 50% brightness

### ISSUE THREAD

**Issue by dENNtoet** [jghaanstra/com.xiaomi-miio#10]
Hi!

I have an issue with the dim level of my Yeelight when I want to change it via a flow. 

Scenario:
Motion Sensor goes off -> Time is between 00:00 and 06:00 (and sun is down) -> Set brightness to 5% (also tried other variables) -> Set color 'red' -> Send IFTTT (this is because I had an issue with the light being offline, so it's for backup). 

What happens is:
Motion sensor goes off -> Light goes on in the color red at around 50% brightness -> the IFTTT trigger fires a few seconds later because of delay since it needs to send it to the internet -> Brightness changes to the correct value.

![image](https://user-images.githubusercontent.com/26697014/30690333-1c13e170-9ec4-11e7-9554-2d8fd248263d.png)

**Comment by dENNtoet** [comment]
Additional findings:

This is the workaround that works:
Card 1: Turn on Yeelight
Card 2 (with 1s delay) Set brightness to X% 

From 'Off' to Set brightness to X% does not work. Keeps the brightness at 50%.

**Comment by dENNtoet** [comment]
additional info:

It's the set color that changes the brightness.. If I turn the lamp on with a flow it stays at around 5% brightness but if I want to change the color with a 2s delay it changes to 50% in that color.

**Comment by jghaanstra** [comment]
Will be fixed with the next SDK2 release.

**Comment by jghaanstra** [comment]
Fixed with https://github.com/jghaanstra/com.xiaomi-miio/commit/a6d1b172e053e8c8338ea6e439c43833208f9f6a

**Comment by jghaanstra** [comment]
I will push a beta release to the app store in the upcoming days with this fix. I would appreciate it if you would be willing to test it. It requires you to repair your Yeelights though.

**Comment by dENNtoet** [comment]
ok! how do I repair the yeelights?

**Comment by jghaanstra** [comment]
- Install beta
- Remove your Yeelights by clicking the cross in the top right corner from the device card
- Use the device pair wizard to add your Yeelights again
- Update all your flows since repairing breaks your flows
