### ISSUE TITLE
Xiaomi smartmobil fan 2s

### ISSUE THREAD

**Issue by henrikrox** [jghaanstra/com.xiaomi-miio#100]
https://m.banggood.com/New-Version-Smartmi-Natural-Wind-Pedestal-Fan-2S-with-MIJIA-APP-Control-Lithium-ion-Battery-DC-Frequency-Fan-p-1433885.html

Any chance of supporting this?

**Comment by jghaanstra** [comment]
You can request for support in the miio library here: https://github.com/aholstenson/miio

I believe it has been requested already but since the library is not maintained anymore it will probably not get added.

**Comment by mediter** [comment]
@henrikrox  hi, there! I am trying to add support of MiFan to miio, also to include support for using Siri to control the rolling.

As I do not have your model, I only have one Xiaomi Variable DC Fan 1x. The method `get_prop` only takes “all” as it’s parameter. I need your help to confirm whether this is the case for 2s as well.

Could u create a issue in my fork of miio? 

https://github.com/mediter/miio

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
