### ISSUE TITLE
Add support for XIAOMI Mijia Camera

### ISSUE THREAD

**Issue by mackelito** [jghaanstra/com.xiaomi-miio#102]
This one :) https://www.banggood.com/Battery-Version-XIAOMI-Mijia-CMSXJ11A-1080P-Smart-Wireless-APP-Control-IP-Camera-Waterproof-Outdoor-Camera-AI-Moving-Detection-Infrared-Nighte-Version-Baby-Monitors-p-1498519.html

**Comment by jghaanstra** [comment]
You can request for support of new devices in the miio library as the Homey app depends on it. But it's not maintained anymore so little chance this will get added.

https://github.com/aholstenson/miio

**Comment by mackelito** [comment]
hmmm.. how can an lib that Homey depends on be unmaintained? 😬
