### ISSUE TITLE
Missing yeelight lamps and strips

### ISSUE THREAD

**Issue by vjmikey** [jghaanstra/com.xiaomi-miio#104]
Hii,

I have around 21 rgb lights and led strips. 
Unfortunately on the app the yeelight searcher got only 16 light input available. 

I've checked if the lan mode is on (yeelight app) and if the light worked on the traditional yeelight app.

So I can't find out why the 5 other light won't work here.

**Comment by jghaanstra** [comment]
Is it always the same lights not being found, even when for instance powering down some other lights. I can imagine the discovery process timing out with so many lights but if it's always the same lights not being discovered there might be something else going on.

Are the lights not being discovered of the same type? I'm looking for some sort of pattern I can work with.

**Comment by vjmikey** [comment]
The lamps that are not found are the same RGB type.

Maybe a idea to make box where to type the ip of the yeelight

**Comment by jghaanstra** [comment]
I'd rather just fix the problem.

Do you know how to run the app from the command line? I could create a debug version that would give me more information.

**Comment by vjmikey** [comment]
Do you main the homey or the yeelight app?

Okay later this day I am at home. 

Do can contact me with slack. Mike Foppen

**Comment by vjmikey** [comment]
Thanksss. It worked now.

Just added with your app the last 5 devices. 


Super!! Have a nice day
