### ISSUE TITLE
Obtain Mi Home device token - encrypted Android backups

### ISSUE THREAD

**Issue by bbkr** [jghaanstra/com.xiaomi-miio#106]
Hi

New encrypted Android phones does not allow to create **not** encrypted ADB backup.

This can be solved by installing Java and using backup extractor from  https://github.com/nelenkov/android-backup-extractor . Which will prompt for password in user friendly way and also add tar headers automatically.

```
$ java -jar abe-all.jar unpack mi-home-backup.ab unpack mi-home-backup.tar
This backup is encrypted, please provide the password
Password:

# extract without header trick
$ tar -zxf mi-home-backup.tar

# db file is accessible
$ ls apps/com.xiaomi.smarthome/db/
geofencing.db				google_app_measurement.db		miio.db					miio2.db				mistat.db
geofencing.db-journal			google_app_measurement.db-journal	miio.db-journal				miio2.db-journal			mistat.db-journal

```

I think it's worth adding in tutorial of how to get device token.

**Comment by jghaanstra** [comment]
Thanx, added it to the docs.
