### ISSUE TITLE
v2.13.1 - 15.10.19 install issue

### ISSUE THREAD

**Issue by ic3cool** [jghaanstra/com.xiaomi-miio#107]
The app did not auto update so i removed the old one. Now its i getting an issue installing the newer version. Homey is up to date according to the update function with in.

![781E84E4-A3C0-43B8-8842-1A6A905DA778](https://user-images.githubusercontent.com/20092339/67140549-ed60ca80-f25b-11e9-933f-4e2418302655.jpeg)

**Comment by jghaanstra** [comment]
The lastest version of the app requires Homey firmware 3.x. You have three choices.

Switch to Homey experimental channel and install Homey firmware 3.x RCx
Wait till Homey firmware 3.x is released to the stable channel, my guess is this wont take long anymore
Install the previous release from the Shelly app using the command line as described here .
