### ISSUE TITLE
v2.13.1 no possibility to install on Homey Pro - incompatible version

### ISSUE THREAD

**Issue by alef201** [jghaanstra/com.xiaomi-miio#108]
Hi,

I have Homey pro. I de-installed this app and I tried to install once again, but I received
message:

This app is incompatible with your Homey software version.

What is the issue ?

Regards.

Ales

**Comment by jghaanstra** [comment]
The lastest version of the app requires Homey firmware 3.x. You have three choices.

Switch to Homey experimental channel and install Homey firmware 3.x RCx
Wait till Homey firmware 3.x is released to the stable channel, my guess is this wont take long anymore
Install the previous release from the Shelly app using the command line as described here https://community.athom.com/t/how-to-cli-install-method/198.
