### ISSUE TITLE
App is incompatible with current version of homey

### ISSUE THREAD

**Issue by nordtorp95** [jghaanstra/com.xiaomi-miio#109]
Please update the app for homey version 2.5.2+

**Comment by jghaanstra** [comment]
The lastest version of the app requires Homey firmware 3.x. You have three choices.

Switch to Homey experimental channel and install Homey firmware 3.x RCx
Wait till Homey firmware 3.x is released to the stable channel, my guess is this wont take long anymore
Install the previous release from the app using the command line as described here https://community.athom.com/t/how-to-cli-install-method/198 .

**Comment by nordtorp95** [comment]
Okay, thank you for the quick response
