### ISSUE TITLE
Yeelights / LED strip - status on not updated when color changed & off

### ISSUE THREAD

**Issue by shaarkys** [jghaanstra/com.xiaomi-miio#112]
Hi,
I recently faced interesting behavior.  I'm turning my Yeelights LED strips on together with TV (condition power consumption) and as I know LED Strip gets on directly when setting color, I omit "turn on" LED strip command. However I have another flow which is linked with condition if the LED strip is on or off and I realized despite LED stripe was on, it was visible by Homey as off and flow has been never triggered. Is it working as designed ? Naturally now I'm turning the LED Strip on first and changing color second - but shouldn't be the status on/off reported anyway, if it's turning on automatically when changing color ? Or vice versa, should the LED Strip turn on when changing color and LED stripe is off ? I have workaround in place just someone else might be fighting this this as well. Thank you.

Btw, when running latest beta, I get in the console :

> 2019-11-11 15:31:17 [log] [ManagerDrivers] [yeelights] [8] Unable to process message because of error: SyntaxError: Unexpected token { in JSON at position 24

**Comment by jghaanstra** [comment]
I can add a failsafe mechanism when the color is changed while the onoff capability is off it changes the onoff capability to on as well.

About the error, this is due to a bug in the Yeelight API. Cant really do anything about it but it does not effect the app. It's been in there since day one and not now in the lastest beta.

**Comment by jghaanstra** [comment]
Fixed with https://github.com/jghaanstra/com.xiaomi-miio/releases/tag/2.13.2
