### ISSUE TITLE
Extract token from the new Roborock app and Roborock S4

### ISSUE THREAD

**Issue by Cloudenius** [jghaanstra/com.xiaomi-miio#113]
Hello,

I'm trying to get the token of my new Roborock S4. It seems that [this new app](https://apps.apple.com/us/app/roborock/id1462875428) is the new way forward for Roborock, as users can migrate their account from Mi Home to the Roborock app.  

Running the `miio discover` command finds the device, but unfortunately not the token:
![image](https://user-images.githubusercontent.com/14926452/68993701-58adb480-087b-11ea-8145-1aa29baaef66.png)

I've tried to create an unencrypted backup of my phone with the Roborock app installed to see if the token is stored somewhere, but unfortunately couldn't find anything useful.

Do you have any other suggestions I can try?

Thank you.

**Comment by jghaanstra** [comment]
Dont know, perhaps post it in the support topic and see if someone from the community has experience with this.

**Comment by Cloudenius** [comment]
@jghaanstra I moved back to the Mi Home app which still works for my S4. (Had to switch to an EU-region - otherwise it wouldn't display the S4 model) While I'm now using the Mi Home app, the RoboRock app itself was way more stable. I will close the issue. Hope someone finds a new way of using the RoboRock app with miio in the future.
