### ISSUE TITLE
App has crashed

### ISSUE THREAD

**Issue by shaarkys** [jghaanstra/com.xiaomi-miio#115]
Hi, I wrote on forum I had problem with connectivity lost of Yeelight Stripe after while, now luckily just app restart fixed connectivity (seems only Homey got issue as original Yeelight app operates stripe normally). However after reboot I got info that app crashed but yet it was working.
![SmartSelect_20191120-235236_Homey](https://user-images.githubusercontent.com/14859895/69285808-0f9a8f00-0bf2-11ea-8159-421147733153.jpg)

**Comment by shaarkys** [comment]
95d516ce-173e-4c68-b83a-2855e234848d

**Comment by shaarkys** [comment]
Btw, when I was restarting app, two out of 13 devices showed red mark (yet original YEELIGHT APP shows well lights online and controllable)

**Comment by jghaanstra** [comment]
The crash is not related to Yeelights but to Xiaomi devices. It's not something I can fix as it's in the miio library.

About the Yeelights not being available on restart. Do your lights have a static IP?

**Comment by shaarkys** [comment]
I was hoping it will be not related to legacy miio library :-(

For Yeelights, yes, I have DHCP static assignments for all of them. Odd that the device even ping on the IP but Homey seems don't see it (and even I was not able to re-register after removal).

I think nothing can be done then,right?

**Comment by jghaanstra** [comment]
I'm working on splitting the Yeelights from the Xiaomi app. In doing so I'll have a good look into the Yeelight code as well. Perhaps I can find improvements. It's strange though you seem to be the only one having these issues with the Yeelights.

I'll keep this open and will look into it further once this split has taken place.

**Comment by jghaanstra** [comment]
I'm closing this now as the Yeelights have been seperated from the Xiaomi Mi Home app. If you experience crashes with the new Yeelight app please report them in that repository.
