### ISSUE TITLE
Please help me with this sentence, trying to obtain token but didn't understand the step in method 4b

### ISSUE THREAD

**Issue by lukinalutuna** [jghaanstra/com.xiaomi-miio#116]
Hi,

so I tried the method 4b in this section:
https://github.com/jghaanstra/com.xiaomi-miio/blob/master/docs/obtain_token.md

I've done the steps and I gained some data over Wireshark. Data consisted of 32 bytes of I think hexadecimal string.

I'm not a native english speaker, please help me so I can understand this sentence better:
"Extract the last 16 bytes of the answer and convert them to a (32 characters) hexadecimal string using xxd -p."

The answer is:

Which bytes is the last 16 bytes of the answer? 

Thanks.

**Comment by jghaanstra** [comment]
Never used that method myself and it was added by someone else as pull request. So I dont know exactly what it means as well. I think you can just copy the last 32 characters.

```In the last 16 bytes (32 characters) of the devices response is the device token. Copy and save it somewhere.```

**Comment by lukinalutuna** [comment]
Does it mean that the token is 32 characters long?

**Comment by jghaanstra** [comment]
That's correct, it's 32 characters.
