### ISSUE TITLE
Roborock Vacuum v1 tokens

### ISSUE THREAD

**Issue by krejkrejkrej** [jghaanstra/com.xiaomi-miio#119]
I've followed your great write-up on token-fetching from a Roborock Vacuum, and would like to add a comment. After a lot of struggling, I concluded that in newer (2018-ish?) firmwares, Xiaomi has made it more difficult to acquire the token from it. 

When the vacuum is reset, a new token is generated. This token is what you get when using method 3, 4a or 4b, when run against an uninitialized vacuum and connected to the hotspot network from the vacuum. However, when you connect the vacuum to your xiaomi account and the app, the token is re-generated again, and in all further communication this new token is not disclosed. 

This makes it impossible to use the network-sniffing methods to pick up the newly generated token. I was able to use MiHome 5.4.54 and pick up the token from the log file on an android phone. 

I suggest that this information is included in the document (https://github.com/jghaanstra/com.xiaomi-miio/blob/master/docs/obtain_token.md), to help other users. 

btw, it may also be useful to other users to mention the possibility to use an Android emulator instead of a physical phone when working with token extraction.

**Comment by jghaanstra** [comment]
The is an old issue which will be closed now. The instructions will be reviewed since time soon.
