### ISSUE TITLE
Feature Request: Change Brightness over Time - Yeelight

### ISSUE THREAD

**Issue by vaderag** [jghaanstra/com.xiaomi-miio#12]
Having moved from Hue to Yeelight, the one feature I miss is being able to change brightness over time.

I.e. use as wakeup (0-100% over 30mins) or use as preparing for bed (x% to 0% over 15mins)

Additionally, while I'm unsure of feasability) it would be great to be able to do the same transitions with colours (Red - Blue - Green) over 10mins

**Comment by jghaanstra** [comment]
In version 2.2.0 I have added a action card to change brightness over time. This will be published to the beta channel of the app store soon. It's currently limited to a time of 30 seconds but I'll remove the time limit once it goed into the stable channel allowing you to set it up the way you like.

I have also added a action card allowing you to send custom commands to any Yeelight. This will allow you to do anything you like with it. Have a look at the documentation here to see what becomes possible: http://www.yeelight.com/download/Yeelight_Inter-Operation_Spec.pdf

I'd appreciate some feedback on the beta app before it goes to stable though.

**Comment by vaderag** [comment]
@jghaanstra wow - that is super fast work!
I'll be happy to do a little testing once you release the beta. That said, currently only have the one bulb - 3 more on their way from China currently ;)

**Comment by jghaanstra** [comment]
It's out in the beta channel, I would appreciate it if you could test it and supply me of feedback.

**Comment by jghaanstra** [comment]
With release 2.2.1-beta also any limitation on the duration will be removed. I'm closing this issue, if you have any further remarks concening this feature let me know and I'll re-open it.
