### ISSUE TITLE
Can't add Gateway to Homey.

### ISSUE THREAD

**Issue by Fotofantasten** [jghaanstra/com.xiaomi-miio#120]
I'm trying to connect My Mi Home gateway to homey but I cant. I get the error "timed out after 30000ms."

Ive upgraded the Mi Home gateway to latest firmware (3.4.6_132).
I'm running the latest Xiaomi Mi Home App in Homey (2.13.8).
I'm running Homey version 3.2.0
And android Homey app 3.2.0.441

I've tried to re-add the gateway in the mi home app (New token).
I've restarted the app in homey.
I've restarted Homey.

Still same response when I test the connection.

The device is working thru the Mi Home Android app and I can control the alarm and light from there...

**Comment by jghaanstra** [comment]
Support for the gateway will be removed as Xiaomi changed something and my currently implementation does not work anymore.
