### ISSUE TITLE
Cant connect fan to app

### ISSUE THREAD

**Issue by jayjay-sweden** [jghaanstra/com.xiaomi-miio#121]
My connected Xiaomi Smartmi Fan 2 gets busy message alot.  I have 2 fans of the same model. (Fan identifies as zhimi.fan.za3)

Same thing with both of them.  Using app version v2.13.9

**Comment by jghaanstra** [comment]
Closing old issues. This app needs financial support for further development and upgrade to SDK3. For more info see: https://community.homey.app/t/app-pro-xiaomi-mi-home-app-for-wifi-devices/118/943
