### ISSUE TITLE
Cannot connect to Lumi Version 3 Mi Hub/Gateway

### ISSUE THREAD

**Issue by RossBrisbane** [jghaanstra/com.xiaomi-miio#123]
The gateway does not connect and times out.

I tested the same method in a now discontinued development app called Yeti.
The app is an android Based App that enables one to talk to the Xiaomi Gateway and inherit all the child devices that are paired with it.
Procedure:
Setting in the Xiaomi Gateway
Three Dot choose, 
Choose about
Click multiple times the version number at bottom
The setting to Network turn on
Copy the Password
Result:
Entered in Yet App worked and connected Xiaomi Gateway.
Result in Homey Mi Home App:
Fails to Connect/ Times out.

Mobile Phone: Xiaomi Note 6 Pro Android 9 
App: Mi Home Homey App latest version
Hardware & Software Platform Homey updated with LATEST firmware/os

**Comment by jghaanstra** [comment]
Closing old issues. This app needs financial support for further development and upgrade to SDK3. For more info see: https://community.homey.app/t/app-pro-xiaomi-mi-home-app-for-wifi-devices/118/943
