### ISSUE TITLE
Roborock s5

### ISSUE THREAD

**Issue by jampeef** [jghaanstra/com.xiaomi-miio#124]
Setting fan speed does not seem to work.
I have a flow which vacuums a area late at night which works flawless thanks for that. The only thing is I want the fan speed to be set to quiet but it always runs at standard mode.

**Comment by jghaanstra** [comment]
Closing old issues. This app needs financial support for further development and upgrade to SDK3. For more info see: https://community.homey.app/t/app-pro-xiaomi-mi-home-app-for-wifi-devices/118/943
