### ISSUE TITLE
Xiaomi Control Hub gw not connect homey

### ISSUE THREAD

**Issue by y9-csillagd** [jghaanstra/com.xiaomi-miio#125]
Hello

I'm trying to connect homey to the xiaomi gateway, but I'm having problems.
According to the description the data (mac and password) should be read in the about menu, but there is no about menu.
How do I add the Xiaomi Control Hub as a gateway in the homey app?
 
Mi home version: 5.6.56
Region: Hungary
 
Homey (Early 2019) version: 4.0.0
App version: 4.0.2.474

Very Thanks,
David

**Comment by cepes** [comment]
you need to unistall mi home app and install app Mi home by vevs on "your device" network you could found your tokken 👍 https://apkvision.com/app/modified-mi-home-by-vevs-38331/

**Comment by y9-csillagd** [comment]
> you need to unistall mi home app and install app Mi home by vevs on "your device" network you could found your tokken 👍 https://apkvision.com/app/modified-mi-home-by-vevs-38331/

thx cepes

**Comment by jghaanstra** [comment]
Closing old issues. This app needs financial support for further development and upgrade to SDK3. For more info see: https://community.homey.app/t/app-pro-xiaomi-mi-home-app-for-wifi-devices/118/943
