### ISSUE TITLE
Xiaomi Roborock s5 Max, can't be connected yet

### ISSUE THREAD

**Issue by WeZZeY** [jghaanstra/com.xiaomi-miio#126]
I've just recently gotten my xiaomi roborock s5 Max (new model) and when I use the token and ip to connect to the device with the MI home homey app I get the following message: "device.getState is not a function"

**Comment by jonatanbergman** [comment]
I have problem to add the s5max to

**Comment by sauk1** [comment]
Same here, get the same response when adding device. Adding it in app config works, but that doesn't add it as a device.

**Comment by torroa** [comment]
Seems to be similar issue with S6 MaxV. Unable to install the Roborock with verified functional token.

**Comment by phict** [comment]
Same problem with S6 MaxV. seems the firmware has changed for maxV since it cannot be controlled with Mi Home v5.4.49 but the regular S6 can. both get a token but fail to open device.

**Comment by phict** [comment]
@Maxmudjon 
Found that this version of miio works good with S6 MaxV:
https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/tree/master/miio

Example to start/stop cleaning
const device = await miio.device({ip:"",token:""})
device.activateCleaning()
device.activateCharging()

and state can be found with:
await device.poll();
const state = await device.state();
console.log("state",state,device.properties);

hope it helps to get maxV support in the Homey app!

**Comment by torroa** [comment]
> @Maxmudjon
> Found that this version of miio works good with S6 MaxV:
> https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/tree/master/miio
> 
> Example to start/stop cleaning
> const device = await miio.device({ip:"",token:""})
> device.activateCleaning()
> device.activateCharging()
> 
> and state can be found with:
> await device.poll();
> const state = await device.state();
> console.log("state",state,device.properties);
> 
> hope it helps to get maxV support in the Homey app!

Yes, the Homebridge app is working with S6 MaxV. Roborock Control Center also works. Tried both to verify my token.

**Comment by phict** [comment]
@torroa @Maxmudjon cloned this repo and replaced the miio directory with the one i linked, then installed it on my homey. now roborock s6 and s6 maxV is working perfectly.

**Comment by torroa** [comment]
> @torroa @Maxmudjon cloned this repo and replaced the miio directory with the one i linked, then installed it on my homey. now roborock s6 and s6 maxV is working perfectly.

Any chance that you could share the repo with the updated miio device library?

**Comment by phict** [comment]
> > @torroa @Maxmudjon cloned this repo and replaced the miio directory with the one i linked, then installed it on my homey. now roborock s6 and s6 maxV is working perfectly.
> 
> Any chance that you could share the repo with the updated miio device library?

1. Clone / download this repo
2. Download this folder: https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/tree/master/miio
3. Extract folder from 2 into miio folder in this repo.
4. Set app id and name to something else in app.json
5. Done

I changed the app name / app id because did

**Comment by torroa** [comment]
> > > @torroa @Maxmudjon cloned this repo and replaced the miio directory with the one i linked, then installed it on my homey. now roborock s6 and s6 maxV is working perfectly.
> > 
> > 
> > Any chance that you could share the repo with the updated miio device library?
> 
> 1. Clone / download this repo
> 2. Download this folder: https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/tree/master/miio
> 3. Extract folder from 2 into miio folder in this repo.
> 4. Set app id and name to something else in app.json
> 5. Done (Install it with "homey app Install")
> 
> I changed the app name / app id because did

I've tried that, but the app is crashing and won't start on my Homey :P

**Comment by phict** [comment]
@torroa forgot two things. i think you need to have same name in package.json as in app.json and then i had to addenv.json in root with {"HOME": "./"}

[com.xiaomi.roborock.zip](https://github.com/Maxmudjon/com.xiaomi-miio/files/4915546/com.xiaomi.roborock.zip)

**Comment by torroa** [comment]
> @torroa forgot two things. i think you need to have same name in package.json as in app.json and then i had to addenv.json in root with {"HOME": "./"}
> 
> [com.xiaomi.roborock.zip](https://github.com/Maxmudjon/com.xiaomi-miio/files/4915546/com.xiaomi.roborock.zip)
> 
> hope it works until the regular app gets updated.

Seems to be working, except zones and go to target.

**Comment by bullseye1977** [comment]
is there any update for this issue?

**Comment by Arjan-21** [comment]
This update works!! Thanks
Hopefully there will be a zone/spot or room cleaning and a way to get the roborock to a destination for empty recycle bin soon.

**Comment by Crawlers11** [comment]
Iv menage to get the v6max working with homey, but I canot get the zones and goto function to work in the flow cards.

**Comment by thorleifjaocbsen** [comment]
Seems like the "hack"  above works. Can this be officially implemented so we do not have to create our own app? @Maxmudjon ?

**Comment by thorleifjaocbsen** [comment]
What is going on here? When can this be fixed? Developers? :)

**Comment by tomaakvik** [comment]
I would also like support for my Roborock S5 Max. Please fix.

**Comment by marcorogo** [comment]
Hi, I fixed a little bit the code and now the zones and goto functions work. I don't have much knowledge in device programming but I hope it can help someone ;)
[Roborock_Zones_Goto.zip](https://github.com/Maxmudjon/com.xiaomi-miio/files/6408030/Roborock_Zones_Goto.zip)

**Comment by bullseye1977** [comment]
I will try the new code today. Thanks for your effort

**Comment by Arjan-21** [comment]
Thank you for making this change in de app. I think it works for me. Now I've to find all the coordinates.

**Comment by Arjan-21** [comment]
I think in this version there is a issue with adjusting the fan. In the other version it was possible. Now it say it’s possible, but don’t change anything.

**Comment by Arjan-21** [comment]
> Hi, I fixed a little bit the code and now the zones and goto functions work. I don't have much knowledge in device programming but I hope it can help someone ;)
> [Roborock_Zones_Goto.zip](https://github.com/Maxmudjon/com.xiaomi-miio/files/6408030/Roborock_Zones_Goto.zip)

Is there a way to fix the fan speed?

**Comment by Arjan-21** [comment]
The fan speed problem was already in the first app. But never noticed

**Comment by marcorogo** [comment]
I'm working on a version that solves the fan speed problem, adds room cleaning mode and other stuff  ;)

**Comment by Arjan-21** [comment]
That’s really nice. I was trying to find something for the fan speed.

**Comment by bullseye1977** [comment]
> I'm working on a version that solves the fan speed problem, adds room cleaning mode and other stuff ;)

Great!

**Comment by marcorogo** [comment]
Here we are!
Here is the list of changes made: 

Fan speed fixed,
Fan speed managed via device interface and action card,
Water mode managed via device interface and action card,
Customise clean-ups per rooms,
Clean rooms

To start cleaning the rooms you need to enter the respective ids in the appropriate action card. The ids start from the number 16 and you have to find out what number a particular room is associated with. The rooms can be entered separated by a comma (16,17,18,19,20) or without a comma (1617181920) this is useful if you want to use variables or tags. By repeating the number of a room, it will be cleaned again. For example (16,16,16,16) will clean the same room 4 times.
I have not tested everything 100% and I am not an expert, try it and let me know 😉
[Roborock_Zones_Goto_CleanRooms_WaterMode.zip](https://github.com/Maxmudjon/com.xiaomi-miio/files/6758875/Roborock_Zones_Goto_CleanRooms_WaterMode.zip)

**Comment by Arjan-21** [comment]
Wow, You are the best!!
I’m going to install the new app and going to try everything. I’ll let you know how it works.

**Comment by ifs-dinodona** [comment]
> Here we are!
> Here is the list of changes made:
> 
> Fan speed fixed,
> Fan speed managed via device interface and action card,
> Water mode managed via device interface and action card,
> Customise clean-ups per rooms,
> Clean rooms
> 
> To start cleaning the rooms you need to enter the respective ids in the appropriate action card. The ids start from the number 16 and you have to find out what number a particular room is associated with. The rooms can be entered separated by a comma (16,17,18,19,20) or without a comma (1617181920) this is useful if you want to use variables or tags. By repeating the number of a room, it will be cleaned again. For example (16,16,16,16) will clean the same room 4 times.
> I have not tested everything 100% and I am not an expert, try it and let me know 😉
> [Roborock_Zones_Goto_CleanRooms_WaterMode.zip](https://github.com/Maxmudjon/com.xiaomi-miio/files/6758875/Roborock_Zones_Goto_CleanRooms_WaterMode.zip)

Hi thank you for your job !! I just tested: 

Fan speed fixed : ok
Fan speed managed via device interface and action card : ok
Water mode managed via device interface and action card : ok
Customise clean-ups per rooms : not tested
Clean rooms : it works but we have to indicate at least 2 rooms. If I indicate 1 room (ex: 16) it does not work.

**Comment by marcorogo** [comment]
Thanks for testing! I fixed the Clean Room bug, now you can indicate  only one  room. Please let me know if any other bug comes up.
[Roborock_Zones_Goto_CleanRooms_WaterMode.zip](https://github.com/Maxmudjon/com.xiaomi-miio/files/6760401/Roborock_Zones_Goto_CleanRooms_WaterMode.zip)

**Comment by Arjan-21** [comment]
For me everything what I've tried worked and I tried function with "then". I don't understand what you mean with "Customise clean-ups per rooms". 
How can I use this?

**Comment by marcorogo** [comment]
Before in Homey you couldn't use the customize cleaning function that allows you to choose differents settings( fan speed and water mode ) for different room. Now you can, you just need to set your Xiaomi app (from Manage Maps menu) and then select customize mode in Homey interface.

**Comment by Arjan-21** [comment]
That is really nice. I'm normally use it for upstairs (had to do turn it on manually). The only thing I've to use the Xiaomi app for is change the map to an other floor.

**Comment by Arjan-21** [comment]
I’ve one little question (hopefully it’s possible). Is there a way to change, when the roborock is spot cleaning or room cleaning that homey says roborock is stopped. I’m hoping to use stopped when homey is stocked or not able to go to the dock. But now getting also a message when he is cleaning a room.

**Comment by sanderjacobsen** [comment]
Hi guys, I'm new here. I’m having trouble with adding the Xiaomi Roborock S5 Max. I have a token but still getting the error “could not connect to device, handshake timeout”.

I extracted the token with these instruction: https://www.youtube.com/watch?v=m11qbkgOz5o 2.

What did I do wrong? Some help needed.

**Comment by sanderjacobsen** [comment]
> Hi, I fixed a little bit the code and now the zones and goto functions work. I don't have much knowledge in device programming but I hope it can help someone ;)
> [Roborock_Zones_Goto.zip](https://github.com/Maxmudjon/com.xiaomi-miio/files/6408030/Roborock_Zones_Goto.zip)

How can add this update? New installation?

**Comment by jghaanstra** [comment]
Closing old issues. This app needs financial support for further development and upgrade to SDK3. For more info see: https://community.homey.app/t/app-pro-xiaomi-mi-home-app-for-wifi-devices/118/943

With enough funding the improvements mentioned in this issue will be integrated.
