### ISSUE TITLE
Doesn't work with EU gateway

### ISSUE THREAD

**Issue by cepes** [jghaanstra/com.xiaomi-miio#128]
I have an EU gateway when i try the method with:
Mac and password: password doesn't work (i check my xiaomi password same result)

With ip and token : The homey screen ask me to wait after validate ip+ token. No error message.
(xiaomi gateway V2)

**Comment by jghaanstra** [comment]
Closing old issues. This app needs financial support for further development and upgrade to SDK3. For more info see: https://community.homey.app/t/app-pro-xiaomi-mi-home-app-for-wifi-devices/118/943
