### ISSUE TITLE
ZhiMi Fan

### ISSUE THREAD

**Issue by Bjokam** [jghaanstra/com.xiaomi-miio#129]
I have 2 ZhiMi Fani can get one of them to work on homey , but the other i can add but it keeps be in offline mode, but i work in xiaomi home app

Property | Value
-- | --
ID | d8ab03df-0167-464c-b54a-91e467c551df
Class | fan
Driver | homey:app:com.xiaomi-miio — zhimi-fan
Ready | Yes
Available | No (Offline)
Warning | No
Custom icon | No

**Comment by rickyhoots** [comment]
I just bought a second fan and am getting the same behaviour. Re-installed app, re-installed devices, did power cycles and everything but the second one is getting added but stays offline.

**Comment by rickyhoots** [comment]
After trying to connect the second Zhimi fan as a Dmaker and removing the device it could be added and now works flawlessly

**Comment by jghaanstra** [comment]
Closing old issues. This app needs financial support for further development and upgrade to SDK3. For more info see: https://community.homey.app/t/app-pro-xiaomi-mi-home-app-for-wifi-devices/118/943
