### ISSUE TITLE
The db file is absent

### ISSUE THREAD

**Issue by Gelezako** [jghaanstra/com.xiaomi-miio#13]
Hi all.
I opened this folder but it's empty. I have root.
/data/data/com.xiaomi.smarthome/databases/
What can I do to make the database file created? Thanks.

**Comment by jghaanstra** [comment]
Is your phone rooted, have you given your file explorer root access and have you enable to option in your file explorer to show all hidden files?

**Comment by Gelezako** [comment]
Thanks, the file was found!
