### ISSUE TITLE
looking for a way to obtain token of smart plug model: zncz02cm

### ISSUE THREAD

**Issue by BlurryFlurry** [jghaanstra/com.xiaomi-miio#130]
Older versions don't get connected with this model. it requires new versions of xiaomi home.
Is there any other way get the token?
I've spent my whole day for this. no luck :(

**Comment by jghaanstra** [comment]
Closing old issues. This app needs financial support for further development and upgrade to SDK3. For more info see: https://community.homey.app/t/app-pro-xiaomi-mi-home-app-for-wifi-devices/118/943
