### ISSUE TITLE
Xiaomi Mi Fan - Additional controls

### ISSUE THREAD

**Issue by BuSHari** [jghaanstra/com.xiaomi-miio#131]
Hi,

Right now there in only one button in the app for on and off.
Is there a chance to add additional controls of the Mi Fan (speed, angel, child lock...)?
I can see in the Device code that those controls are available, but i don't see it in the Homey app.
https://github.com/Maxmudjon/com.xiaomi-miio/blob/master/drivers/zhimi-fan/device.js

Any way to add/fix them (ZhiMi and Dmaker models)?

Thanks...

**Comment by jghaanstra** [comment]
This app needs financial support for further development and upgrade to SDK3. For more info see: https://community.homey.app/t/app-pro-xiaomi-mi-home-app-for-wifi-devices/118/943
