### ISSUE TITLE
Update for "Extract token from a backup on Android phones that allow non-encrypted backups"

### ISSUE THREAD

**Issue by wally-nl** [jghaanstra/com.xiaomi-miio#134]
Just tried the adb backup method, if all you get is a 41-47 byte file this is due to the fact that xiaomi has put android:allowBackup="false" in the APK's AndroidManifest.xml

This is at least from version 5.8.7 and onwards, maybe earlier

**Comment by jghaanstra** [comment]
Closing old issues. This app needs financial support for further development and upgrade to SDK3. For more info see: https://community.homey.app/t/app-pro-xiaomi-mi-home-app-for-wifi-devices/118/943
