### ISSUE TITLE
Adding Xiaomi Vacuum failes

### ISSUE THREAD

**Issue by yormedia** [jghaanstra/com.xiaomi-miio#135]
Hi,

When I try to add a Vacuum I will get the error.

 device.getState is not a function

homeyVersion | "5.0.0-rc.26"
-- | --

Regards,

Carlo

**Comment by Casall1000** [comment]
I get the same error device.getState is not a function when trying to add Xiaomi Roborock S6MaxV

Xioami Mi Home app: 3.0.8
Homey version: 5.0.0-rc 38

**Comment by JirLap** [comment]
Also on version 
homeyVersion | "4.2.0"
(S5 Max)

**Comment by jghaanstra** [comment]
These devices are currently not supported. This app needs financial support for further development and upgrade to SDK3. For more info see: https://community.homey.app/t/app-pro-xiaomi-mi-home-app-for-wifi-devices/118/943
