### ISSUE TITLE
Air purifier

### ISSUE THREAD

**Issue by miquelgeuens** [jghaanstra/com.xiaomi-miio#136]
![Screenshot_2020-11-09-11-32-01-708_app homey](https://user-images.githubusercontent.com/57488266/98531124-2cefbf80-2280-11eb-83c1-f3bb6167ae55.jpg)

**Comment by jghaanstra** [comment]
Closing old issues. This app needs financial support for further development and upgrade to SDK3. For more info see: https://community.homey.app/t/app-pro-xiaomi-mi-home-app-for-wifi-devices/118/943
