### ISSUE TITLE
Retrieve token via Genymotion Emulator

### ISSUE THREAD

**Issue by walthowd** [jghaanstra/com.xiaomi-miio#137]
Install GenyMotion
https://www.genymotion.com/download/

Setup new Android 8.0 custom phone

Install ARM translation tool:
https://github.com/m9rco/Genymotion_ARM_Translation/tree/master/package
 (drag onto VM window)

Restart phone/emulator

Install 5.4.49 of Mi Home (drag into VM window)
https://www.apkmirror.com/apk/xiaomi-inc/mihome/mihome-5-4-49-release/
Logon to your Xiaomi account. 

Restart phone/emulator

Click around in settings

Open FileBrowser 

Go to root / SmartHome/ Logs / plugDeviceManagerXXX and double click text files.

Search for "token"

**Comment by jghaanstra** [comment]
There are easier methods now. Closing this issue.
