### ISSUE TITLE
Mi Air Purifier 3 not working

### ISSUE THREAD

**Issue by Askeo** [jghaanstra/com.xiaomi-miio#140]
Mi Air Purifier 3 is not working with correct token and IP

Region: EU/DE

NAME: Mi Air Purifier 3/3H
ID: 313871411
IP: (censored)
TOKEN: (censored)
MODEL: zhimi.airpurifier.mb3

The message i get is handshake is not working & power is not a function

**Comment by ndwaard** [comment]
I have the same issue.

Region EU/NL

NAME: Mi Air Purifier 3/3H
ID: 270532552
IP: (censored)
TOKEN: (censored)
MODEL: zhimi.airpurifier.mb3

The message I get is: Device Power is not a funtion.

**Comment by caspervanzoest** [comment]
I also have the same issue. Adding the device goes OK, but in the Homey app the device loses connection.

**Comment by jghaanstra** [comment]
Closing old issues. This app needs financial support for further development and upgrade to SDK3. For more info see: https://community.homey.app/t/app-pro-xiaomi-mi-home-app-for-wifi-devices/118/943
