### ISSUE TITLE
Mi Smart Space Heater S not working

### ISSUE THREAD

**Issue by Askeo** [jghaanstra/com.xiaomi-miio#142]
NAME:  Mi Smart Space Heater S
ID:    333030646
IP:    (censored)
TOKEN: (censored)
MODEL: zhimi.heater.mc2

**Comment by jghaanstra** [comment]
This app needs financial support for further development and upgrade to SDK3. For more info see: https://community.homey.app/t/app-pro-xiaomi-mi-home-app-for-wifi-devices/118/943
