### ISSUE TITLE
Trying to connect smartmi evaporative humidifier 2

### ISSUE THREAD

**Issue by horstefan** [jghaanstra/com.xiaomi-miio#147]
Device fails to add with message below

![Screenshot_20210518-172631](https://user-images.githubusercontent.com/23259607/118679708-66405380-b7fe-11eb-9389-b80baf681a13.jpg)

**Comment by ifs-dinodona** [comment]
same error

**Comment by kapusticka** [comment]
Same for me

**Comment by kozo8603** [comment]
I got this error too (Model: zhimi.humidifier.ca4)
