### ISSUE TITLE
" device.getState is not a function " on connect Mi Robot Vacuum-Mop P

### ISSUE THREAD

**Issue by jlilleby** [jghaanstra/com.xiaomi-miio#149]
Trying to add my Mi Robot Vacuum-Mop P to my Homey Pro but when entering the Token, IP and refresh rate, i am prompted with 
 "device.getState is not a function", is this a known issue and any possible to fix this.

**Comment by jghaanstra** [comment]
Closing old issues. This app needs financial support for further development and upgrade to SDK3. For more info see: https://community.homey.app/t/app-pro-xiaomi-mi-home-app-for-wifi-devices/118/943
