### ISSUE TITLE
No issue: does iBackup view show the actual token?

### ISSUE THREAD

**Issue by iAmRenzo** [jghaanstra/com.xiaomi-miio#150]
I was extracting the token through the back-up/sqlite/website and I noticed the output was the same as the token mentioned in this window...

<img width="715" alt="Schermafbeelding 2021-10-13 om 15 05 27" src="https://user-images.githubusercontent.com/1183790/137138557-e23f3041-a531-4b03-9ca4-b9758eb2c873.png">

**Comment by jghaanstra** [comment]
Cleaning up old issues. If this is still an issue please open up a new one.
