### ISSUE TITLE
Vacuum became unavailable everyday at specific time

### ISSUE THREAD

**Issue by lkw11** [jghaanstra/com.xiaomi-miio#151]
Hi guys,

need some help on an issue for my Roborock G10 integrate in Xiaomi miio. Everything is working but it will became unavailable everyday at 03:26 my time. I have to open the MiHome app on my phone and it will update in HA.

Is there any solution ? I searched online but could not find any option.

Thanks.

**Comment by jghaanstra** [comment]
This is the repo for the Homey app, not for Home Assistant. Closing this issue.
