### ISSUE TITLE
When adding the Xiaomi Gateway 3 none of the device appear in HAI

### ISSUE THREAD

**Issue by Skrndelj** [jghaanstra/com.xiaomi-miio#152]
As the title states above added the gateway 3 and it detects devices but not on the actual device list but when you press configure
![image](https://user-images.githubusercontent.com/99065623/178049033-22d4f3af-a00c-4245-9ac1-90ac503f2589.png)

Devices do not show anything i currently have hooked up to it
![image](https://user-images.githubusercontent.com/99065623/178049114-0e85a6e2-a7d6-4d80-85b1-98a97701e398.png)

**Comment by jghaanstra** [comment]
This is the repo for Homey and not Home Assistant. Closing this issue.
