### ISSUE TITLE
Please add support for SDK3

### ISSUE THREAD

**Issue by powermarcel10** [jghaanstra/com.xiaomi-miio#154]
Hi, I am wondering if you will update your app to SDK3 in order to get it to work with the newest Homey pro 2023.

Best regards,
Marcel

**Comment by jghaanstra** [comment]
There is a bounty started on the forum to make this happen. Feel free to jump in make this happen.

https://community.homey.app/t/app-pro-xiaomi-mi-home-app-for-wifi-devices/118/942
