### ISSUE TITLE
Xiaomi GW v3 - Join button missing and dim values are not changing button on/off state

### ISSUE THREAD

**Issue by shaarkys** [jghaanstra/com.xiaomi-miio#159]
Xiaomi Gateway v2 (lumi.gateway.v3) added flawlessly (previously added as 3 devices, now as one) - I see however JOIN button missing (eg. when adding devices to the GW itself). Light powered off via DIM or powered on via DIM is not resulting in Button switching off/on- - it’s currently independent on light itself but button itself turn lights on/off.

I had JOIN button available from the Mi Homey app v 1.1.12 - https://github.com/Maxmudjon/com.maxmudjon.mihomey or better https://github.com/Maxmudjon/com.maxmudjon.mihomey/blob/master/drivers/gateway/driver.compose.json

**Comment by jghaanstra** [comment]
Could you explain in more detail what the join button offers in functionality. I probably cant add it in the current driver as this is relying on the miio library while the functionality for the join button is implemented through the library that is used to connect ZigBee subdevices. So implementing it would mean having to create a new driver for the gateway just for this functionality.

But I really need to know what the button actually does.

**Comment by jghaanstra** [comment]
Nevermind, I know what it does and I think I found the equivalent command using the miio library so now extra action is needed.

**Comment by shaarkys** [comment]
Just maybe let's wait for some feedback, if anyone else is missing that. I just observed it's missing, used it some time ago when testing pairing with devices that had troubles when pairing with Homey itself - but I wonder if anyone is using it....

**Comment by jghaanstra** [comment]
I've added it already as well as turning off/on based on dimming to 0 (off) or 0+ (on). Will be available in the next release.
