### ISSUE TITLE
Call to device timed out

### ISSUE THREAD

**Issue by basvdploeg** [jghaanstra/com.xiaomi-miio#160]
I'm using the app with a Mi Air Purifier 3H, but the device keeps switching between working (for a couple of seconds) and getting error `Apparaat is onbereikbaar: Call to device timed out`. 

The device is connected to my local network, and is available via the Xiaomi Home app without a problem.

Diagnostics Report: `d38cc3cb-ac96-4288-93cc-db6bcd8543d3`
App version: v3.1.0
Homey Pro (Early 2023)

**Comment by jghaanstra** [comment]
Could you let me know on which app you where previously using this device with. And also with what driver it was paired with on that app?

[ ] App store Xiaomi Mi Home with air purifier driver (generic)
[ ] Community app Mi Homey with Mi Air Purifier 3H driver

**Comment by basvdploeg** [comment]
I was using the Mi Homey (community app) with Mi Air Purifier 3H driver.

**Comment by jghaanstra** [comment]
Could you re-test this on version 3.1.1 which is currently available in the test channel.

**Comment by basvdploeg** [comment]
Seems to work better now! I’ll keep monitoring this, but it’s working without timeouts now.

Thanks! 🙏🏻
