### ISSUE TITLE
WSDCGQ01LM sensor - Zigbee - added succesfully, not updating values

### ISSUE THREAD

**Issue by shaarkys** [jghaanstra/com.xiaomi-miio#161]
https://community.homey.app/t/app-pro-xiaomi-mi-home-app-for-wifi-devices/118/1029?u=sharkys

 I tested adding one of the Xiaomi temp. sensor WSDCGQ01LM(…they were really unreliable with Homey) and seems while original app shows updates, the Homey integration with added device not. 
Sent diag. on 7.3. evening -  if this helps to discover something more - eg. even for others Zigbee type devices.

Thank you.

**Comment by shaarkys** [comment]
FYI, it was handled previously by this code - https://github.com/Maxmudjon/com.maxmudjon.mihomey/tree/master/drivers/temp_hum_sensor - but never had integrated this way, so maybe it's wrong already there...

**Comment by jghaanstra** [comment]
Will be fixed in the next release.
