### ISSUE TITLE
When crawling trough Xiaomi Gateway v2 settings, sections are not loading

### ISSUE THREAD

**Issue by shaarkys** [jghaanstra/com.xiaomi-miio#162]
....I'm not sure if it's not issue of my Homey, however other devices loads fine (including devices from this integration)

Diag. a108b4de-c637-487c-a813-5ad9878a8252

How to replicate : see video - open GW, go directly to other tab - it will not load. But when you just scroll, it's fine.

https://user-images.githubusercontent.com/14859895/223668794-1d44b181-8f0a-4cf5-87c6-dd6575501c97.mp4

**Comment by jghaanstra** [comment]
I'll have to see if I can reproduce this but for more it doesn't seem to be something related to the Mi Home app.

**Comment by shaarkys** [comment]
It could be Homey issue indeed, btw it do not happen on the Web app....

**Comment by jghaanstra** [comment]
I can not reproduce but I'm using the beta app because I'm also testing with HP2023. But it's not something that can be solved within the app though. If it bothers you, you can report it at Athom HQ.

**Comment by shaarkys** [comment]
Fixed in latest beta of Android app :-)
