### ISSUE TITLE
Xiaomi Gateway v2 - Volume set RADIO Volume

### ISSUE THREAD

**Issue by shaarkys** [jghaanstra/com.xiaomi-miio#164]
When I was restoring my flows, I realized that VOLUME set the RADIO volume but not ALARM, Doorbell etc.
Would be great to have this option at least via FLOWs if not via settings in the app itself.

Thank you.

Screenshot from the Xiaomi app (tested actually the RADIO volume has been moving)

![obrazek](https://user-images.githubusercontent.com/14859895/223675202-4e295841-89f4-4c40-a794-6854a6b19d07.png)

**Comment by jghaanstra** [comment]
Is this available on the Mi Homey app? And it so, how is it implemented there?

**Comment by shaarkys** [comment]
I think it was done in the way, that actually Gateway has been represented by 3 different devices - Radio, Gateway and some 3rd one - don't recall, also unfortunately not running the old app anymore. So when you want to change Radio volume, you were adjusting volume of Radio device, when Gateway - the Alarm etc.

**Comment by shaarkys** [comment]
If it helps more : 

https://github.com/Maxmudjon/com.maxmudjon.mihomey/tree/master/drivers/gateway_security
https://github.com/Maxmudjon/com.maxmudjon.mihomey/tree/master/drivers/gateway
https://github.com/Maxmudjon/com.maxmudjon.mihomey/tree/master/drivers/gateway_radio

..I personally never user Radio, only Gateway and Security (Gateway as Gateway for devices + playing sound and using as light notification and Security - for Alarms etc.)

I think it might be enough just to add additional slider to the DIM LEVEL, Volume level...not sure if Homey can handle it still ;-)

**Comment by jghaanstra** [comment]
There will be an extra slider for the alarm volume and a custom action card allowing you to set the volume of the selected types in the next release.
