### ISSUE TITLE
Support for dmaker.fan.p15

### ISSUE THREAD

**Issue by nerdtechse** [jghaanstra/com.xiaomi-miio#166]
Added a dmaker.fan.p15 with the selection of "Dmaker Mi Fan Generic" when added. Which was successfully added to my homey. But the name was set to "Unknown model"  and when i try to turn off or on it gives me the error "this.miio.setPower is not a function"

The model of fan is Xiaomi Mi Smart Standing Fan Pro

Diag report d522486c-3a0c-4cf5-b768-12ae5b9d6be5

**Comment by jghaanstra** [comment]
Added it with the `DMaker` miio device class. Please test it with release 3.1.12 when it's release in the upcoming days. Might not work perfect or even at all. This is just a quick experiment.

**Comment by jghaanstra** [comment]
Update released, please test and post the outcome here.

**Comment by nerdtechse** [comment]
Thanks for trying but.. No, sorry didnt work gets the error message "Busy" 

Do you want a new diag report?

**Comment by jghaanstra** [comment]
Yes please, this doesnt sound like an error message coming from the driver.

**Comment by nerdtechse** [comment]
Ok! Here it is! 

c2cdf46a-f314-456b-94d3-1fd3584c815a

**Comment by jghaanstra** [comment]
You seem to have added with the `Mi Smart Standing Fan 3` driver. Please test the `Dmaker Mi Fan Generic` driver.

**Comment by nerdtechse** [comment]
Have readded it again as a `Dmaker Mi Fan Genric`  But the same thing happends.. 

143ee172-420f-47e6-bb47-e33895450e02

**Comment by jghaanstra** [comment]
According to the log you send me you have the same device paired 4 times. The message busy is a result of overflowing the device with traffic. Remove all but one and test again.

```
[log] 2023-03-14 20:41:25 [ManagerDrivers] [Driver:zhimi_fan_za5] [Device:d145ad3b-e4fa-4c04-92ed-6c88579a914a] WiFi Device Init: Unknown model (dmaker.fan.p15) with ip 172.16.17.192 and capabilities onoff,onoff.swing,dim,dim.angle,zhimi_fan_za5_mode,measure_humidity,measure_temperature and model dmaker.fan.p15 and store values  model,power,modes
[log] 2023-03-14 20:42:58 [ManagerDrivers] [Driver:dmaker-fan] [Device:51b8748c-4346-4d04-91a1-342dc844c9b1] WiFi Device Init: Mi Smart Standing Fan Pro (dmaker.fan.p15) with ip 172.16.17.192 and capabilities onoff and model dmaker.fan.p15 and store values  model,power,modes
[log] 2023-03-15 01:34:29 [ManagerDrivers] [Driver:dmaker-fan] [Device:d98b2e14-f10c-4849-9621-c6063c7f1834] WiFi Device Init: Mi Smart Standing Fan Pro (dmaker.fan.p15) with ip 172.16.17.192 and capabilities onoff and model dmaker.fan.p15 and store values  model,power,modes
[log] 2023-03-15 08:53:18 [ManagerDrivers] [Driver:dmaker-fan] [Device:a9fbfb11-cba8-4beb-8db6-14dc7ef2cb95] WiFi Device Init: Mi Smart Standing Fan Pro (dmaker.fan.p15) with ip 172.16.17.192 and capabilities onoff and model dmaker.fan.p15 and store values  model,power,modes
```

**Comment by nerdtechse** [comment]
![image](https://user-images.githubusercontent.com/35535897/225346716-59b805ac-d996-42e7-bb31-7bfb09d5ed13.png)

There is just one paired. The others in the log is when i tried earlier pairings. I could try to reboot the homey if that is still doing something with the deleted devices.

**Comment by jghaanstra** [comment]
Ok, too bad for now. Perhaps support will be added in the future.

**Comment by jghaanstra** [comment]
I published a new release to the test channel which contains support for this device. Please test.

**Comment by nerdtechse** [comment]
Sorry for late answer been away some days. 

Tried the new version and same thing the fan gets flooded so even the orginal app dont work.  This time i also reseted the fan before trying and got a new token. (Just to rule out the fan as a problem) :)

**Comment by jghaanstra** [comment]
Could you send me diagnostic report

Do you have the device paired with other integrations as well? If so, this can cause issues. This unofficial API is not made to be used by multiple integrations besides the official smartphone app.

**Comment by jghaanstra** [comment]
It seems you paired it with a 10 seconds polling frequency. Could you re-move and re-pair it maintaining the default 60 seconds polling frequency.

**Comment by nerdtechse** [comment]
Strange didnt change that.. Reseted the fan again.. Tested with official smartphone app.. worked.. Installed on homey with new token. Wont work and official app isnt working.. I double checked it was now set to 60sec in polling. 

Also did a new report cf149c84-0724-4511-a946-ae0dc9061f71

**Comment by jghaanstra** [comment]
I made some changes in release 3.1.18. Not sure if this helps your issue but please retest and let me know the outcome.

**Comment by dikal31** [comment]
Can you add Mi Smart Standing Fan 2

dmaker.fan.p18

**Comment by jghaanstra** [comment]
@nerdtechse I added a new driver for various Dmaker models including the `dmaker.fan.p15`. Could you test your device with the `Advanced Dmaker Fan` driver and let me know the outcome.

**Comment by nerdtechse** [comment]
@jghaanstra Sorry for late answer have been away working alot. But now im home and had time to test it! 

You are a real star and it works really good! Great work!
