### ISSUE TITLE
Support for zhimi.fan.za4

### ISSUE THREAD

**Issue by bulletcather** [jghaanstra/com.xiaomi-miio#167]
If i turn on a fan.
This message appears.
Also there are no flow cards for the device

![Screenshot_20230308-220631](https://user-images.githubusercontent.com/67913404/223852367-1f408899-72cd-476f-9dc0-86beb519379e.png)

**Comment by bulletcather** [comment]
2a4186e4-04b1-4fb8-931d-ad7e8ea3e90d

**Comment by jghaanstra** [comment]
It is probably an unsupported model. What is the model identifier or the exact name of the fan?

**Comment by bulletcather** [comment]
It is not a new device.
It works with the stable version

It is Smartmi Standing Fan 2S

**Comment by jghaanstra** [comment]
> It is not a new device.
> It works with the stable version

Then you probably paired it with the wrong driver, for instance the generic Dmaker driver instead of the Zhimi driver (or visa versa). Try one of the other driver for fans.

**Comment by bulletcather** [comment]
After re-adding the device it now works.
It also have more functions like swing and power level.

Thx for the support
