### ISSUE TITLE
Gateway - volume control

### ISSUE THREAD

**Issue by shaarkys** [jghaanstra/com.xiaomi-miio#168]
FYI 

![obrazek](https://user-images.githubusercontent.com/14859895/224031727-ef5403fb-ec24-4433-9a1c-e6b207987bcf.png)

Also I realized that following triggers are not changing volume itself when executed...

![obrazek](https://user-images.githubusercontent.com/14859895/224032436-158a40dc-2cc0-4ac9-bcfe-0c246a046521.png)

Tricky part is that this flow eg. even execute related sound - but I believe this is as designed, as it's even coming from the original app itself.

![obrazek](https://user-images.githubusercontent.com/14859895/224035953-4c2ca8e8-d62c-42ee-96ce-8543dab83557.png)

No big deal but still maybe some small fixes might be done.

Diag. code : bcfbaf3d-c931-408e-8d3e-f247f4fc7707

**Comment by jghaanstra** [comment]
Error with radio will be fixed in the next release.

It's appearantly not possible to set the volume of an effect in one flow. Will be removed from the card next release.

Setting the volume will indeed make a sound, this can not be prevented as this is how the API works.
