### ISSUE TITLE
Roborock S5 issues

### ISSUE THREAD

**Issue by zawinull** [jghaanstra/com.xiaomi-miio#169]
The installation succeeds but the Roborock S5 does not work with "Mi Roborock Vacuum v1 / 1s / s5" driver: "Device is unreachable: invalid_setting_type."

With the "Robot Vacuum Cleaners Generic" driver the commands work but it does not read the status changes.

**Comment by jghaanstra** [comment]
This issue is being tracked here: https://github.com/jghaanstra/com.xiaomi-miio/issues/165
