### ISSUE TITLE
vacuum not working anymore

### ISSUE THREAD

**Issue by chrisboer** [jghaanstra/com.xiaomi-miio#17]
What do you mean with since new firmware ? If you don't update the firmware then you won't have a problem is it ?

**Comment by jghaanstra** [comment]
Hello @chrisboer,

If your Mi Robot is currently working with my app you have two choices. Don't update and wait I until the app is not supported by Homey core anymore (from Homey firmware 2.x) or try a command line install of the software in the beta branch here on github which still contains the Mi Robot driver. Disclaimer, this requires you to repair your Mi Robot which I was unable to.
