### ISSUE TITLE
v3.1.5 - Roborock S5 status change issue

### ISSUE THREAD

**Issue by zawinull** [jghaanstra/com.xiaomi-miio#171]
v3.1.5 - With "Mi Roborock Vacuum v1 / 1s / s5" driver, after startup the status changes to "Cleaning" correctly, but then it steps through all the statuses in sequence.

![image](https://user-images.githubusercontent.com/53702811/224305586-8a5290db-93a9-485e-ac60-bb43c53bcb36.png)

**Comment by jghaanstra** [comment]
Please try again on the next release (3.1.6) and report back in the issue below if it isnt fixed. This issue if related to all vacuum cleaner issues.

https://github.com/jghaanstra/com.xiaomi-miio/issues/165
