### ISSUE TITLE
Humidifier V2 water level and humidity data

### ISSUE THREAD

**Issue by zawinull** [jghaanstra/com.xiaomi-miio#174]
v3.1.8 - Mi Humidifier v2 - Generic: works fine but water level and humidity data are inaccurate.

![image](https://user-images.githubusercontent.com/53702811/224502922-1da07f89-e604-4b6d-8aed-d2f7b6186846.png)

**Comment by jghaanstra** [comment]
Not sure if this is easily fixable. Could you answer these questions and do the following.

- Could you send me a diagnostic report
- Has the humidity or waterlevel changed since you updated to 3.1.8 ?
- What is the configured polling frequency for the device?
- If you restart the app, does it update to the correct values?

**Comment by zawinull** [comment]
- Diagnostic report has been sent: db5599ad-bc3b-45b2-8eaf-63c0f693281a
- Yes, the humidity and waterlevel data are constantly changing. The difference between the MI app and Homey data does not seem to be constant. Strange, but over time the difference between the humidity data decreased, after about 20 minutes it became accurate. I have two humidifiers, the phenomenon is exactly the same for both. However, the water level data remained inaccurate (on both devices)
- The polling frequency is 60.
- If I restart the app does not update to the correct values.

**Comment by jghaanstra** [comment]
Have you tried pairing it with the `Mi (Air) Humidifier v2` driver? Perhaps this gives better results.

**Comment by zawinull** [comment]
Sorry but in the previous posts I didn't refer to the correct driver version, I actually used the `Mi (Air) Humidifier v2` driver (both versions have "v2" in the name which is quite misleading). However, I now found myself trying to pair one of the humidifiers with the `Mi Humidifier v2 - Generic` driver. The pairing was successful but after a few seconds the connection was lost ("Device is unreachable: depth is not defined"). 

Diagnostic report was sent: 5d6080af-6dd0-4cec-a6f4-1aa8f421c09f

**Comment by jghaanstra** [comment]
For own reference regarding this issue.

```[err] 2023-03-13 12:27:41 [ManagerDrivers] [Driver:mi-humidifier2] [Device:c4497a61-0ea7-47ca-b91d-6f47443150b3] ReferenceError: depth is not defined
    at MiHumidifier2Device.retrieveDeviceData (/drivers/wifi_device.js:342:55)
```

```
Error: humidifier2_mode InvalidEnumValueError: auto is not a valid enum value (invalid_enum_value)
```

**Comment by jghaanstra** [comment]
@zawinull (or anyone else with the same issue), did you have this device paired with Homey before the update and if so, with the Xiaomi Mi Home or the Mi Homey (community) app and with what driver?

**Comment by zawinull** [comment]
It was paired with the Xiaomi Mi Home app and worked fine with the `Mi Humidifier v2` driver.  

This device was sold under many different names: (Xiaomi/Smartmi/Zhim) Air Humidifier 2/Humidifier V2/Evaporative Humidifier V2 - All of them have this identifier: SKV6001EU / CJXJSQ02ZM
https://www.aliexpress.com/item/1005001701842270.html

**Comment by jghaanstra** [comment]
I think I found the bug. On the previous version it did not show water level. But when adding this i introduced a bug. Please test on the next release.

**Comment by zawinull** [comment]
I installed both 3.1.11 "Humidifier v2" drivers.
After installation, the devices identify themselves as `Mi (Air) Humidifier v2` regardless of which driver I used.

`Mi Humidifier v2 - Generic` data
Humidity: ok
Waterlevel: ok
Power: 0W - I don't think this device can provide this data, but there may be models or firmwares that can. 
Temperature: missing - this device can provide this data.

`Mi (Air) Humidifier v2` data
Humidity: ok
Waterlevel: inaccurate and does not seem to be changing
Temperature: ok, but sometimes it disappears and then reappears.

Target relative humidity parameter is not used by this device.

**Comment by jghaanstra** [comment]
> I installed both 3.1.11 "Humidifier v2" drivers.
> After installation, the devices identify themselves as Mi (Air) Humidifier v2 regardless of which driver I used.

Because it retrieves the name based on your device model (which is zhimi.humidifier.cb1)

> Power: 0W - I don't think this device can provide this data, but there may be models or firmwares that can.

Not sure why this is in there. I'll remove this capability.

> It seems to me that the Mi Humidifier v2 - Generic driver is a better choice for the SKV6001EU / CJXJSQ02ZM v2 models.

I'll add it to the docs and will close this issue. For now the ` Mi Humidifier v2 - Generic driver` is an improvement over the currently live release as it also includes water level now. It's impossible to create a driver for each device seperately.
