### ISSUE TITLE
Missing device type (Device capabilities app)

### ISSUE THREAD

**Issue by shaarkys** [jghaanstra/com.xiaomi-miio#175]
Previous implementation from time to time lost connection to the robots - eg. due to the temporary wifi signal dropouts or due to the roaming (802.11r) - never found the culprit. For this reasons I have been using trigger from [Device capabilities](https://homey.app/en-us/app/nl.qluster-it.DeviceCapabilities/Device-Capabilities/) - "Device become available/unavailable" - for some reasons Device type is not populated (I mean any)

![image](https://user-images.githubusercontent.com/14859895/224571467-984f4474-5ad6-427c-8693-ea5dbe5667b9.png)

For other devices, eg. yours Yeelights LAN ;-) 

![image](https://user-images.githubusercontent.com/14859895/224571610-6816b20d-82bc-45ba-890a-68e38e703a6f.png)

It's not important, but is it hard to be fixed (due to the amount of devices supported) or it's just minor ? If it's more time demanding, please close it as you will be not implementing it - I was just not sure if it's bug or intention.

Thank you.

**Comment by jghaanstra** [comment]
I dont know, I have a default SDK3 implementation with the Xiaomi Mi Home app. You'd better ask the developer of the Device capabilities app why this is happening. I dont think it's something for me to fix.

**Comment by shaarkys** [comment]
Indeed, fixed by Arie - thank you 

Version 2.9.28 — Bugfixed: Set devices with class/brand/etc should now work for everyone.
https://homey.app/en-us/app/nl.qluster-it.DeviceCapabilities/Device-Capabilities/test/
