### ISSUE TITLE
This is amazing... The robot G1 connected through your app.  (Dreame Bot
L10 Pro /
Xiaomi Vacuum
1T (WiFi) )
On/Off works fine.  The 3C air purifier also works in Homey like never before. 

### ISSUE THREAD

**Issue by Matthew1910** [jghaanstra/com.xiaomi-miio#177]

**Comment by jghaanstra** [comment]
Good to hear

**Comment by Matthew1910** [comment]
What happened to your app????  Nothing works 🙃🙃🙃

**Comment by Matthew1910** [comment]
Many devices have disappeared.

**Comment by jghaanstra** [comment]
You probably installed the live version. The upgrade is still in the test channel of the app store.

https://homey.app/nl-nl/app/com.xiaomi-miio/Xiaomi-Mi-Home/test/

**Comment by Matthew1910** [comment]
Yesterday I connected the bridge to Homey pro and noticed that strange
things started happening in different apps.  I'll check it out soon...
Thank you for your help👍😉

pon., 20 mar 2023, 07:05 użytkownik Jelger Haanstra <
***@***.***> napisał:

**Comment by Matthew1910** [comment]
Hello, have you changed anything in your application?? Vacuum cleaner
problems...I can't remove the device, and I can't use it.
Error log:
9e072a9d-3899-41a3-8e95-4f844885514f
Gr.Matt

pon., 20 mar 2023, 07:17 użytkownik Matthew M. ***@***.***>
napisał:

**Comment by jghaanstra** [comment]
What maintenance proces? Just long press the device, click on the cogwheel in the top right corner and use the "Remove this device" option.

**Comment by Matthew1910** [comment]
![Screenshot_20230411_202527_Homey.jpg](https://user-images.githubusercontent.com/98472600/231256169-312cf7af-96b1-43a0-a38d-2597d492456c.jpg)

**Comment by Matthew1910** [comment]
![Screenshot_20230411_202957_Homey.jpg](https://user-images.githubusercontent.com/98472600/231256415-a3762237-879d-4e7e-941e-9b2483b08250.jpg)

**Comment by Matthew1910** [comment]
b1cfe2a3-e7ba-42a3-a508-c2780ca9ae0f

**Comment by Matthew1910** [comment]
That damned vacuum cleaner is the last missing piece in my ecosystem.  PLEASE HELP ME!

**Comment by jghaanstra** [comment]
> That damned vacuum cleaner is the last missing piece in my ecosystem. PLEASE HELP ME!

I added a new ticket for adding support for this device..

https://github.com/jghaanstra/com.xiaomi-miio/issues/196

Adding support for new devices is not high on my priority list though.

**Comment by Matthew1910** [comment]
And can't you possibly add 1 more device with these "random" settings??  (...and when the time comes, maybe you'll develop them further.)

**Comment by Matthew1910** [comment]
Hi Dear Master, why can't I add an air purifier???  Has anything changed
again? Gr.Matt


wt., 11 kwi 2023, 20:43 użytkownik Jelger Haanstra ***@***.***>
napisał:

**Comment by jghaanstra** [comment]
A lot has changed. Use the forum. Read the changelog there and if you still have issues explain them there.

https://community.homey.app/t/app-pro-xiaomi-mi-home-app/118/1273
