### ISSUE TITLE
Humidifier JSQ - deerma.humidifier.jsq

### ISSUE THREAD

**Issue by djmaupp** [jghaanstra/com.xiaomi-miio#178]
7198a54d-5c12-4e88-ba95-f46aa5e79722

Hi as mentioned in a email conversation my humidifier won’t show any data.

Temp: unknown
Humidity: unknown 
Water level: Yes
(I assume that means filled and not empty, so maybe reverse it so it is actually an alarm when empty)

![IMG_0532](https://user-images.githubusercontent.com/116944608/225108460-ac792ae0-a986-49d4-90ac-8ea75ea64d54.jpeg)
![IMG_0534](https://user-images.githubusercontent.com/116944608/225108467-ff357e84-8ae5-4e4e-85d1-408fd9376d1e.jpeg)

Modes:
Level 1: Works sets it to low
Level 2: Works sets it to medium
Humidity: Wrong translation this sets the mode to High (should set it to auto/humidity)

Missing mode:
Level 3: This option is missing (High setting)

Dim level 
This works, and sets the humidity between 40% (0 on the slider) and 70% (100 on the slider)
Could this be changed that it only slides between 40 and 70?
But only when I set the mode to “auto/humidity” in the Xiaomi app.

**Comment by jghaanstra** [comment]
Has this device ever worked before on Homey and if so, what app and driver?

If not, it's a feature I'll look into at a later time.

**Comment by jghaanstra** [comment]
I have found some documentation and have updated the mode and the water empty alarm.

> Could this be changed that it only slides between 40 and 70?

Not possible in the Homey UI. But should it be limited to between 40 and 70 at all or should it just be from 0 to 100%?

**Comment by jghaanstra** [comment]
Ok, see my message above. 

> Could this be changed that it only slides between 40 and 70?

Not possible in the Homey UI. But should it be limited to between 40 and 70 at all or should it just be from 0 to 100%?

**Comment by djmaupp** [comment]
> Not possible in the Homey UI. But should it be limited to between 40 and 70 at all or should it just be from 0 to 100%?

I think limited will be the best as it’s the only option as well in the Mi Home app

![IMG_0536](https://user-images.githubusercontent.com/116944608/225123260-0c045755-fac5-477e-835f-9dd0794812e9.jpeg)

**Comment by jghaanstra** [comment]
Ok, i'll release the update  this evening. Please report back once tested again.

**Comment by djmaupp** [comment]
Version 3.1.12

Temp is fixed 👍🏻
Humidity is fixed 👍🏻

🚨Modes have disappeared 
🚨I see a motion alarm in it now (active)

And the water level is (still) active is this correct?

**Comment by jghaanstra** [comment]
I'll fix these last things with the next release but that wont be today anymore.

**Comment by djmaupp** [comment]
No problem! I will watch it and let you know!

**Comment by djmaupp** [comment]
Yes of course! :)

Modes are back but they are not working.
In the official app I see the modes go to a unselected state, that is not possible when I switch between modes via their app.

![IMG_6193](https://user-images.githubusercontent.com/116944608/225412755-9c6cd91c-099b-4bbb-a1ef-c866ac430420.png)

The waterlevel alarm is still "active" but the device is filled. so this should be not alarming I think.
And the water tank state is unknown.
Oh and the motion alarm is still in it.

![IMG_6192](https://user-images.githubusercontent.com/116944608/225412527-702c73c6-a8fe-4b0b-8207-0b093fbf8fc7.png)


Small note but not a problem caused specifically by the app I think.
After intensive testing I always lock out of the device and need to pull the plug to get it to work again.
_Could not connect to device, handshake timeout_

**Comment by jghaanstra** [comment]
> Modes are back but they are not working.

Hopefully fixed on the next release

> The waterlevel alarm is still "active" but the device is filled. so this should be not alarming I think.
> And the water tank state is unknown.

Their implementation seems to be really counter intuitive where the value waterstatus === 1 (true) when it's not empty. I switched it around which should fix that. As well as the watertank status which is currently not updating. Comes with the next release.

> Oh and the motion alarm is still in it.

You need to re-pair it to get rid of that.

**Comment by djmaupp** [comment]
> You need to re-pair it to get rid of that.
After the new update? Because when I do I now, it comes back.

**Comment by jghaanstra** [comment]
> > You need to re-pair it to get rid of that
> 
> After the new update? Because when I do I now, it comes back.
After the new update. Should be fixed on 3.1.14.

**Comment by jghaanstra** [comment]
Version 3.1.14 is now in the test channel. Please retest setting the mode, waterlevel alarm and that the motion alarm is gone when re-pairing.

**Comment by djmaupp** [comment]
All the above is working ✅

LED via settings will not turn it on or off.
Buzzer via settings works.


The flow modes ar not a reflection yet of the mode screen.
<img width="471" alt="Scherm­afbeelding 2023-03-18 om 20 18 13" src="https://user-images.githubusercontent.com/116944608/226132594-182810af-b800-4fde-bc7a-8d874a00aa3e.png">

Dim level in flow is a bit high? Or is this necessary for the 40 till 70% slider function
<img width="411" alt="Scherm­afbeelding 2023-03-18 om 20 18 33" src="https://user-images.githubusercontent.com/116944608/226132600-aa565056-313a-4617-b28d-77045ddcc94a.png">

**Comment by jghaanstra** [comment]
> LED via settings will not turn it on or off.

Will not be able to fix this. The current implementation is as documented.

> The flow modes ar not a reflection yet of the mode screen.
> Dim level in flow is a bit high? Or is this necessary for the 40 till 70% slider function

Will fix that with the next release

**Comment by jghaanstra** [comment]
> triggerCapabilityListener is not defined

Pfff, so hard to get it right without being able to test it. Hopefully fixed on the next release.

**Comment by djmaupp** [comment]
I understand. But also impossible to own all the devices 😅

**Comment by jghaanstra** [comment]
> triggerCapabilityListener is not defined

Could you test on release 3.1.17?

**Comment by djmaupp** [comment]
Fixed!
