### ISSUE TITLE
Air Purifier 2S (zhimi.airpurifier.mc1)

### ISSUE THREAD

**Issue by djmaupp** [jghaanstra/com.xiaomi-miio#179]
Hi the Purifier 2S (connected as Mi Luchtreinigers)

Shows a mode called Standby but this is not supported by this model

"Mode idle not supported"

For the rest this model works great and has no problems

**Comment by djmaupp** [comment]
Ive spotted some other points:

- Flowcard for led display not working (Method not found.)
In the 2S I don't have bright dim or off, but only on and off in the MiHomeApp

Things that are maybe not supported or embedded
- On/off settings for Buzzer
- Filter remaining data/lifespan days

**Comment by jghaanstra** [comment]
> Shows a mode called Standby but this is not supported by this model
> "Mode idle not supported"

Thanx for reporting but it's supported by other models though. Generic drivers may contain functionality for more devices, some of which might not work on all models. It's impossible to create specific drivers for each specific device.

> Flowcard for led display not working (Method not found.) In the 2S I don't have bright dim or off, but only on and off in the MiHomeApp

Same as above, other models do. I fixed the flow card but it might not work properly for your model.

> On/off settings for Buzzer. Filter remaining data/lifespan days

The generic driver doesnt support this.

Something else to try is to pair it with the `Mi Humidifier v1 ` driver. It seems this device share similar functionality and supports more feature than the generic driver. Please let me know.

**Comment by djmaupp** [comment]
> Something else to try is to pair it with the `Mi Humidifier v1 ` driver. It seems this device share similar functionality and supports more feature than the generic driver. Please let me know.

I can't connect a purifier to the Humidifier driver.

**Comment by jghaanstra** [comment]
Argh, just wasted 30 minutes of my life looking at the wrong device type.

**Comment by djmaupp** [comment]
I understand. I’m always looking 3 times with purifier or humidifier in English

**Comment by jghaanstra** [comment]
Could you check this again on release 3.1.13.

**Comment by djmaupp** [comment]
✅ Setting LED in settings is working (on/off)
🛑 Changing LED via flow not working (on/off)

✅ Changing modes works: Auto, Stil (Silent/Night) and Favorite (Manual speed)
🛑 Changing modes in flow is not working for Night/Silent
Mode `night` not supported

⭐️ The "manual/favorite" mode can also have a dim slider for the speed 
✅ Changing speed via flow is working

**Comment by jghaanstra** [comment]
> 🛑 Changing LED via flow not working (on/off)

Hopefully fixed with next release, kinda hard to make it work with all variations out there

> 🛑 Changing modes in flow is not working for Night/Silent

Fixed with the next release

> ⭐️ The "manual/favorite" mode can also have a dim slider for the speed

Not for now, I need to get things stable first before introducing more features and possible bugs

**Comment by djmaupp** [comment]
Thanks! 

The ⭐️ was just something I noticed. I understand that the goal is first to iron all the bugs out

**Comment by jghaanstra** [comment]
Setting the LED and the mode should now be fixed with release 3.1.14. Please retest.

**Comment by djmaupp** [comment]
> 🛑 Changing LED via flow not working (on/off)

this.hasCapability is not a function



> Changing modes in flow is not working for Night/Silent

✅ Fixed

**Comment by jghaanstra** [comment]
> this.hasCapability is not a function

Will fix that with the next release.

**Comment by djmaupp** [comment]
> > 🛑 Changing LED via flow not working (on/off)

✅ Fixed
