### ISSUE TITLE
Support for Roborock S7 MaxV Ultra (roborock.vacuum.a27)

### ISSUE THREAD

**Issue by Zekcode** [jghaanstra/com.xiaomi-miio#180]
Is there any plans for adding support for the Roborock S7? it can be added as a "advance Vacuum" and read batterystates and some basic information, but are not able to be toggled on/off inside the app.

**Comment by jghaanstra** [comment]
What is the actual error? And what is the device model? And have you send a diagnostic report after trying?

I designed this driver on my Roborock S7 (roborock.vacuum.a15) and it's working fine for me. It could be something in your setup.

**Comment by Zekcode** [comment]
Error shown: **this.miio.clean is not a function**

Model: Roborock S7 MaxV Ultra with modelnumber: S270RR
Shown in Homey as: Unknown model (roborock.vacuum.a27)

Can't some reason create a diagnostic report, gets error "rate limited" even after reboot. hmm

![Screenshot 2023-03-16 at 11 09 27](https://user-images.githubusercontent.com/55090314/225585843-efa47557-3437-422c-bc57-9d452941860d.png)

**Comment by jghaanstra** [comment]
This model isnt supported (yet).

**Comment by Zekcode** [comment]
> 

Allright, let me know if i can assist you in any way regarding this product. :)

**Comment by jghaanstra** [comment]
Version 3.1.14 is now in the test channel and might contain support for this model. Please test.

**Comment by jghaanstra** [comment]
The errors I'm seeying in the are unrelated to the error about a capability listener. The errors are really weird though. And it seems the device is paired multiple times. Could you please completely remove all instance of the vacuum, re-pair it and see if the same error occurs.

**Comment by Zekcode** [comment]
> The errors I'm seeying in the are unrelated to the error about a capability listener. The errors are really weird though. And it seems the device is paired multiple times. Could you please completely remove all instance of the vacuum, re-pair it and see if the same error occurs.

What model do you want me to pick when parring? (just to be sure)
![Screenshot_4](https://user-images.githubusercontent.com/55090314/226120828-c69f01cf-35e0-47c3-87f5-3ab294e9686d.png)

**Comment by jghaanstra** [comment]
The first one (advanced vacuum). But it's important three device is completely removed from Homey first.

**Comment by Zekcode** [comment]
> The first one (advanced vacuum). But it's important three device is completely removed from Homey first.

Deleted alle devices and rebooted homey, added as advance vaccum, all working fine now.
New reportID: 3212a605-1ce6-4182-b7ce-48f993f19e18

DM/PM or drop a donation / paypal link etc, if you accept donations :)

**Comment by jghaanstra** [comment]
Good to hear. Closing this issue.

Donations are always welcome: https://www.paypal.com/paypalme/jghaanstra :-)

Thanx in advance.

**Comment by Zekcode** [comment]
> Good to hear. Closing this issue.
> 
> Donations are always welcome: https://www.paypal.com/paypalme/jghaanstra :-)
> 
> Thanx in advance.

The community are heavly relying on people like you, people there can afford a small donation should be doing so, if the dev is bringing them software there are helpful or usefull for them. Your support here is very much appreciated. I just send a small donation your way,  thanks!

**Comment by jghaanstra** [comment]
Thanx again, much appreciated!
