### ISSUE TITLE
Aqara double wireless switch (WXKG02LM) - no switch flow/action cards

### ISSUE THREAD

**Issue by Eternity-again** [jghaanstra/com.xiaomi-miio#182]
<img width="419" alt="Schermafbeelding 2023-03-17 om 15 05 14" src="https://user-images.githubusercontent.com/10754229/225927847-e51ec521-1b39-46fc-9cfc-45f6d88d3862.png">

Switch was migrated from the Homey Zigbee App by Ted and had actions card for both the left and right switch. It was paired with the Xiaomi gateway successfully, and Homey showed it as a device. However, the switches are not seen in the flow editor so the product can't operate anything.

**Comment by jghaanstra** [comment]
Should be fixed with the next release.

**Comment by jghaanstra** [comment]
Version 3.1.14 is now in the test channel. Please retest this issue.

**Comment by Eternity-again** [comment]
Closed
