### ISSUE TITLE
Mi Aqara Cube model sensor_cube.aqgl01 - not triggering all states

### ISSUE THREAD

**Issue by shaarkys** [jghaanstra/com.xiaomi-miio#183]
Hi, to follow-up on diag. report 47292c5d-02bd-4046-8369-b86c8cb97043 - original app show almost every move but the Homey register only rotation 

![obrazek](https://user-images.githubusercontent.com/14859895/226012273-f3b5398b-813f-49a0-b178-42f0aa30f632.png)

I tested with this flow - only Rotation has been triggered. 

![obrazek](https://user-images.githubusercontent.com/14859895/226020064-9d53fcaf-50a9-425d-b12a-137315631dbc.png)

However as I also mentioned, I had this as spare device only so rather performing just testing. If you are busy with other stuff, feel free to mark it as "waiting for additional inputs" - to see if others are using it and it's working fine for them.

**Comment by shaarkys** [comment]
Tested again SHAKE, Tap twice, Flip 180, Flip 90, Push - all registered by the original Mi Home App from Xiaomi. None except rotations in the Athom Homey app itself. On positive side, the rotation is nicely sensitive.

**Comment by jghaanstra** [comment]
Could you simplify your flow and not use the rotation tag in the action (as that is not available for all other cards).

**Comment by shaarkys** [comment]
Good hint - I shall next time include error output ;-) Sorry for false alarm, works as it should ;-)
