### ISSUE TITLE
Philips downlight - temporary error "Resp inv. json"

### ISSUE THREAD

**Issue by shaarkys** [jghaanstra/com.xiaomi-miio#184]
Resp inv. json when turning off light (Philips Downlight) via button in the app - temporary error, disappeared after several attempts

diag with error - e7e1c166-9b60-4757-b134-ae5c78aa5866

without error  - e803084d-84c5-4c76-b23d-1403c265c46a

Please close it is you see nothing relevant.

**Comment by jghaanstra** [comment]
Related log:

```
[err] 2023-03-19 22:27:27 [ManagerDrivers] [Driver:philips-bulb] [Device:8eb9bdf5-580d-42f6-bd68-7718a29d806e] Error: Resp invalid json.
    at Object.reject (/node_modules/miio/lib/network.js:503:13)
    at DeviceInfo.onMessage (/node_modules/miio/lib/network.js:402:8)
    at Socket. (/node_modules/miio/lib/network.js:171:12)
    at Socket.emit (node:events:526:28)
    at UDP.onMessage [as onmessage] (node:dgram:922:8) {
  code: -30001
}
```

This seems to be cause by a networking error between the device and the miio library which is used to talk to the unofficial Xiaomi API. According to the library the device returned some invalid JSON. There is not much which can be done about this as the API is not officially documented and supported.
