### ISSUE TITLE
Support for Mi Robot Vacuum-Mop 2 Ultra (dreame.vacuum.p2150a)

### ISSUE THREAD

**Issue by T0macher** [jghaanstra/com.xiaomi-miio#185]
Hi,

I have a vacuum cleaner and i would like to use with homey.
Unfortunately this modell isn't supported yet.

When i tried to add the device this is what happened:
At the first time, i Could add the device, but i get a warning sign immediately, so i removed, and tried again.
at the second time, i can
not add the device (i tried all the 4 vacuum cleaner category). if i put the “test connection” button a get a warn

<img width="1136" alt="Screenshot 2023-03-22 at 12 49 43" src="https://user-images.githubusercontent.com/128604773/226912518-3bbf924d-320c-4fa7-a203-f91383ec3618.png">

if you need more information, please let me know :)

**Comment by T0macher** [comment]
Hi, After the todays update, i could add the device, i got this immediately: 
<img width="1242" alt="Screenshot 2023-03-23 at 10 35 46" src="https://user-images.githubusercontent.com/128604773/227162538-984ac96a-ef04-40db-8456-977f6298543f.png">

**Comment by jghaanstra** [comment]
Please send a diagnostic report from the app settings.

**Comment by T0macher** [comment]
i sent.

that is the code what i got:
1221dcd2-2b06-4a1f-bcf1-5344af3a627e

**Comment by T0macher** [comment]
Hi @jghaanstra,

This is absolutely understandable!
Thank you for your time, I appreciate it!

Tamas

**Comment by jghaanstra** [comment]
A driver for dreame.vacuum.px models has been added with release 3.1.18. It will be buggy or might not work at all but please test  it thoroughly and post your findings here.

**Comment by jghaanstra** [comment]
> Thank you Jelger :)
> I could add the device, i see the consumables status, the battery status, and i can start the cleaning.
> I also made some basic flow to test the device.

> I have a question. Can the homey app manage the mop's zones form the xiaomi app? is it possible?

Managing the mop zones in the way this is done in the Xiaomi Mi home app is not possible. If you find issues please open up a new ticket which will be handle as bugs.
