### ISSUE TITLE
Left and Right relay not showing in Flows

### ISSUE THREAD

**Issue by PeetersJan** [jghaanstra/com.xiaomi-miio#187]
For the Aqara double relay type LLZMK11LM, only one of two relays are available in flows.
Model code: Relay.c2acn01

Issue already raised (and aknowledge by you) on the Homey forum, just trying to follow the guideline.

**Comment by jghaanstra** [comment]
Already solved locally and will be fixed with the next release.

**Comment by PeetersJan** [comment]
*closed*
