### ISSUE TITLE
Reverse logic on door/window sender (magnet)

### ISSUE THREAD

**Issue by EricMB73** [jghaanstra/com.xiaomi-miio#188]
Would love the option to be able to change the settings of the door/window sensor. So it will raise an alarm when the door is closed and stops the alarm when the door is opened.

**Comment by jghaanstra** [comment]
Added with release 3.1.18, please test.

**Comment by T0macher** [comment]
Thank you Jelger :)
I could add the device, i see the consumables status, the battery status, and i can start the cleaning.
I also made some basic flow to test the device.

I have a question. Can the homey app manage the mop's zones form the xiaomi app? is it possible?

**Comment by EricMB73** [comment]
Just tested the reverse logic switch…
Works perfect !!

thanks for adding this feature so fast !

Eric
