### ISSUE TITLE
Add support for Xiaomi Philips bulbs

### ISSUE THREAD

**Issue by jghaanstra** [jghaanstra/com.xiaomi-miio#19]
Currently not even supported by the miio library and technical data needs to be retrieved from other Xiaomi libraries.

**Comment by thunderace** [comment]
Xiaomi Philips bulbs works fine with the miio library.

**Comment by jghaanstra** [comment]
@thunderace 
Thanx, I actually implemented this with release 2.4.1 but forgot to close the issue.

https://github.com/jghaanstra/com.xiaomi-miio/releases/tag/2.4.1
