### ISSUE TITLE
Add support for dmaker.fan.p18 (Mi Smart Fan 2)

### ISSUE THREAD

**Issue by dikal31** [jghaanstra/com.xiaomi-miio#192]
Can you add Mi Smart Standing Fan 2

dmaker.fan.p18

**Comment by dikal31** [comment]
My Fan write issues in homey, say Busy after i turn on/off everytime (zhimi.fan.za3)

Can you fix it?

**Comment by jghaanstra** [comment]
> My Fan write issues in homey, say Busy after i turn on/off everytime (zhimi.fan.za3)
> 
> Device is unreachable: fan_zhimi_mode InvalidEnumValueError: 0 is not a valid enum value (invalid_enum_value)
> 
> I addet with Basic Smartmi/Zhimi, (Zhimi.fan.za3) another say issues evertime.. can you changes it on your site Supported devices

Please report this in a separate issue as it's unrelated to your original request. And send me a diagnostic report from the app so I can actually try and fix it.

**Comment by dikal31** [comment]
I solved this case by using one of the other smart fan driver, so I used this one - "Basic Smartmi/Zhimi", (Zhimi.fan.za3)

Can you change this on the page where it says which devices work and don't work, this driver I used does not report errors.

**Comment by jghaanstra** [comment]
> Can you change this on the page where it says which devices work and don't work, this driver I used does not report errors.

No, I'd rather fix the issue and make it work properly with the advanced driver. Will be fixed with the next release.

**Comment by dikal31** [comment]
I solved this case by using one of the other smart fan driver, so I used this one - "Basic Smartmi/Zhimi", (Zhimi.fan.za3)

I had problems with my second fan as you can see above this text.

Under supported devices you write you must use "Use Advanced Zhimi Fan driver" it failed for me, so I used the one called Basic Smartmi/zhimi instead as it does not fail in the code, mine kept showing red triangle, it solved I know to change to this basic driver instead of.

i hope you understand now... i solved the cases, too changes driver.

**Comment by dikal31** [comment]
Can you changes on the supported Devices?

https://github.com/jghaanstra/com.xiaomi-miio/wiki/Supported-Devices

**Comment by jghaanstra** [comment]
> Can you changes on the supported Devices?

Why is that important to you? I'd rather fix the issue with the advanced driver.

**Comment by dikal31** [comment]
> > Can you changes on the supported Devices?
> 
> Why is that important to you? I'd rather fix the issue with the advanced driver.

I have used the other driver as the other one reported an error, red triangle.
