### ISSUE TITLE
Aqara Product

### ISSUE THREAD

**Issue by dikal31** [jghaanstra/com.xiaomi-miio#193]
Will you add this Aqara Thermostat E1 (https://www.aqara.com/en/product/radiator-thermostat-e1)

And Hub E1 (https://www.aqara.com/en/product/hub-e1)

**Comment by jghaanstra** [comment]
Both devices are Zigbee devices and are supported (or support is being added) in the Aqara Zigbee app.

https://homey.app/a/com.xiaomi-mi/

If you really want them added in my app as a sub device of the Xiaomi Gateway V2 / V3 you would have to send me these devices. There is no documentation so I would need to have the devices.

Let me know or close the issue.
