### ISSUE TITLE
Fanspeed is always set to Balanced for S6MaxV

### ISSUE THREAD

**Issue by xgbcman** [jghaanstra/com.xiaomi-miio#194]
Fanspeed is always set to Balanced when I set any speed with fanspeed card. S6MaxV has five speeds Gentle, Quiet, Balanced, Turbo, Max but whatever I choose it is always changed to Balanced. See screenshot.
![Screenshot_20230410_152900_Mi Home](https://user-images.githubusercontent.com/40564043/230911691-2a394d2b-4a5b-4ff5-9cf2-ba3e6e7b4ce3.jpg)

**Comment by jghaanstra** [comment]
This is not for the S6MaxV as that vacuum model only has 4 vacuum power states. Please supply the model number (as in `roborock.vacuum.axx`).

And even if I know the model number I might not fix this issue. There are dozens of vacuum models out there, each with slightly different config. Supporting every feature for every model is impossible,

**Comment by xgbcman** [comment]
The model is roborock.vaccum.a10.

I helped Justin Haring a lot to test and debug his app "Roborock" so I understand that it is hard work to support all vaccum models, and it is small donations that hardly cover the time invested.

**Comment by jghaanstra** [comment]
It get's even weirder in supporting all models. I have the `roborock.vacuum.a10` myself but in the Xiaomi Mi Home app it only gives me 4 vacuum speeds. And according to the miio docs this model does only have 4 speeds.

https://home.miot-spec.com/spec/roborock.vacuum.a10 (see mode parameter)

So if you are 100% sure there are models out there with the same model number but with different features. Are you sure this is the correct model?

**Comment by xgbcman** [comment]
Xiaomi Home app
![Screenshot_20230410_173848_Mi Home](https://user-images.githubusercontent.com/40564043/230937682-d85f03b5-2a3c-4578-b68d-3857aad307df.jpg)

Label on vaccum
![20230410_173759](https://user-images.githubusercontent.com/40564043/230937925-20aad637-c612-4060-b750-7e7605179ee9.jpg)

**Comment by jghaanstra** [comment]
As I said, weird.

I just release version 3.1.20 which should do a little better job setting the fanspeed. It's probably not perfect but it will probably never be since I need to support other models with other configs as well. Please test and report back here.

**Comment by xgbcman** [comment]
Thank you for trying but it still same behaviour. It always changed to Balanced. 
I choose to not use fanspeed instead.

**Comment by jghaanstra** [comment]
> Thank you for trying but it still same behaviour. It always is changed to Balanced. I choose to not use fanspeed instead.

Could you please send me a diagnostic report from the app settings. Some other users might want to use this feature, so I want to fix it.

**Comment by xgbcman** [comment]
"84F321D4"

**Comment by xgbcman** [comment]
16f707f2-865e-4bd2-a315-35c6aa44301e

**Comment by Arjan-21** [comment]
I've now the same problem with my S5Max. After I upgraded my homey pro with the 2023 model (last week), so I don't know which update.
In my old homey I had 4 choices for fan speed and now I see 5. That's the only thing that look different. After the update homey didn't remember "silent" and showed me the empty fan card. Maybe this information is helping.

**Comment by jghaanstra** [comment]
Some models have 4 speeds others have 5. I cant adjust the flow card conditionally. Nothing has changed in this part of the app for some time now so I dont know why it broke for you just now.

I did look at the code again and I think I found the issue. Hope it will be fixed with release 3.2.8.

**Comment by Arjan-21** [comment]
Thank you!

**Comment by Arjan-21** [comment]
Hi Jelger,

I've updated to 3.2.8 and It works great for my roborock! Thank You

Only homey is seeing an error.
<img width="294" alt="Scherm­afbeelding 2023-06-09 om 16 31 09" src="https://github.com/jghaanstra/com.xiaomi-miio/assets/75159756/776f7bac-91fc-4724-b272-02f773962937">

**Comment by jghaanstra** [comment]
I'll fix that with the next release.

**Comment by jghaanstra** [comment]
The error should be gone with release 3.2.9.

**Comment by Arjan-21** [comment]
For me it works great. Thank you!

**Comment by xgbcman** [comment]
Great! Well done!

**Comment by xgbcman** [comment]
Unfortunately the fanspeed problem that was fixed in version 3.2.8 is back. 
The fanspeed card always results in Balanced fanspeed on S6MaxV.

**Comment by jghaanstra** [comment]
Since there has not been an update from the app it must be something else. Did you upgrade the firmware is your device? If not, try soft resetting and re-adding it to Homey.
