### ISSUE TITLE
Add support for Xiaomi Mi Smart Air Fryers

### ISSUE THREAD

**Issue by dikal31** [jghaanstra/com.xiaomi-miio#197]
Can you add this product?

https://amzn.eu/d/6YGOcIt

And this

https://amzn.eu/d/05UmUtQ

**Comment by jghaanstra** [comment]
Perhaps in the future, this is not high on my priority list.

For reference: https://home.miot-spec.com/s/Air%20Fryer

**Comment by jghaanstra** [comment]
There is a new version in the test channel that should add support for this device. Please test it by installing the test version (you can switch back to the live version without loosing devices and flows).

https://homey.app/nl-nl/app/com.xiaomi-miio/Xiaomi-Mi-Home/test/

**Comment by jghaanstra** [comment]
No feedback but now release with 3.2.3.
