### ISSUE TITLE
New version of miIO library

### ISSUE THREAD

**Issue by circuuz** [jghaanstra/com.xiaomi-miio#20]
A new version of the miIO library with rewritten support for the old vacuum and added support for the new vacuum. 
https://github.com/aholstenson/miio

Maybe the new releases could help bring back support for the old vacuum and add support for the new to this app? :)

I'm happy to help with testing!

**Comment by jghaanstra** [comment]
I already tested it a bit this evening, doesnt solve the issue for me. In fact, the device discovery seems even worse than the previous version. It's having a hard time discovering my Yeelight which was always discovered before.

If you want to help out and test you can install the miio CLI and see if it discovers your vacuum robot.

**Comment by circuuz** [comment]
I see. I'll give it a test and report back!

**Comment by jghaanstra** [comment]
You can chip in with your findings here: https://github.com/aholstenson/miio/issues/92

**Comment by jghaanstra** [comment]
We have cracked the Mi Robot issue and I have implemented support again with https://github.com/jghaanstra/com.xiaomi-miio/commit/cd51f3e26658da6306e73ac07df1ea3addc9c1a2
