### ISSUE TITLE
Add support for mmgg.pet_waterer.wi11 (Xiaomi Smart Pet Fountain)

### ISSUE THREAD

**Issue by DamianPL** [jghaanstra/com.xiaomi-miio#200]
Hi,

Is it possible to add a Xiaomi Smart Pet Fountain device

https://home.miot-spec.com/spec?type=urn:miot-spec-v2:device:pet-drinking-fountain:0000A067:mmgg-wi11:1

**Comment by jghaanstra** [comment]
There is a new version in the test channel that should add support for this device. Please test it by installing the test version (you can switch back to the live version without loosing devices and flows).

https://homey.app/nl-nl/app/com.xiaomi-miio/Xiaomi-Mi-Home/test/

**Comment by DamianPL** [comment]
Thank you very much works almost perfectly :)
The connection works fine, but the alarm about the lack of water appears all the time

**Comment by jghaanstra** [comment]
> The connection works fine, but the alarm about the lack of water appears all the time

That is a bit strange. Could you test what happens when the device is actually without water and see if the alarm is cancelled.

**Comment by DamianPL** [comment]
There is an exchange.

When there is water in the container, a message about flooding appears and lights up red in Homey.

When there is no water, there is no alarm in homey.

All other functions work fine :)

**Comment by jghaanstra** [comment]
Ok, I'll invert the value.

**Comment by DamianPL** [comment]
Let me know when you release a test version ;)

**Comment by jghaanstra** [comment]
Next version will go straight to live.

**Comment by DamianPL** [comment]
Maybe you know when?

**Comment by DamianPL** [comment]
After update 3.2.3 it works perfectly ;) Thank you!

**Comment by jghaanstra** [comment]
Released with 3.2.3
