### ISSUE TITLE
incorrect humidity value on Mi Smart Antibacterial Humidifier “deerma.humidifier.jsq5” 

### ISSUE THREAD

**Issue by puddrik** [jghaanstra/com.xiaomi-miio#201]
homey pro showing 0.38% instead of 38% on the measured Relative Humidity on the Mi Smart Antibacterial Humidifier “deerma.humidifier.jsq5” 

Xiaomi app shows correct value

**Comment by jghaanstra** [comment]
There is a new version in the test channel that should fix this. Please test it by installing the test version (you can switch back to the live version without loosing devices and flows).

https://homey.app/nl-nl/app/com.xiaomi-miio/Xiaomi-Mi-Home/test/

**Comment by puddrik** [comment]
Hi

I tried it and first no change then I uninstalled and reinstalled the humidifier and suddenly it shows 3400%
Then went back to the Live version and for some reason it now shows the correct value on the live version

**Comment by jghaanstra** [comment]
Great, it wasnt a bug after all .. I'll revert the change.
