### ISSUE TITLE
Roidmi Eva 

### ISSUE THREAD

**Issue by Popaul73** [jghaanstra/com.xiaomi-miio#202]
Hello, could you add the roidmi Eva vacuum cleaner to your application, I tried to connect it as a Xiaomi vacuum mop the map and the parts appear but I can't issue any order to the vacuum cleaner, thanks by the way Do you have  Do you have a link for a donation to thank you for your work?  Translated by Google translate.

**Comment by jghaanstra** [comment]
Thank you for the donation.

Do you have the exact model number of the vacuum cleaner (should be under device info in the official app somewhere).

**Comment by Popaul73** [comment]
Code s/ n    RVWWBA0I09534
N° de compilation.   3245
Devld.       bf3aea7f09203b3bear0oc
Station base s/n.     RVWWBA0I09534

Firmware robot 1.2.3
Firmware station 1.5.9

Le dim. 21 mai 2023, 11:59, Jelger Haanstra ***@***.***> a
écrit :

**Comment by jghaanstra** [comment]
That's not what I'm looking for. It should be something like `roidmi.vacuum.v60` but perhaps with a different number.

**Comment by Popaul73** [comment]
Robot. SDJ06RM
Station. JCZ06RM

number found in the manual

Le dim. 21 mai 2023, 16:55, Jelger Haanstra ***@***.***> a
écrit :

**Comment by Popaul73** [comment]
hello I can't test your work, mi Home is completely messing around I
installed different versions but nothing works. thank you anyway for the
work done cordially

Le mer. 31 mai 2023, 14:51, Jelger Haanstra ***@***.***> a
écrit :
