### ISSUE TITLE
No action card in flow for swing modus on mi smart standing fan 2 lite.

### ISSUE THREAD

**Issue by pjmpessers** [jghaanstra/com.xiaomi-miio#204]
Hello.

Thanks for the app xiaomi. Thanks to that i can attach  my mi smart standing fan 2 lite.
But while i can turn on and off the rotation in the device card, i can't do that as a action in the flow card.
And what does dim 400% do?

Placed a small donation for your app.

**Comment by jghaanstra** [comment]
Thanx for the donation.

The Mi Smart standing fan 2 lite has the model ID dmaker.fan.1c which does not support setting the swing mode angle according to the docs which I based the driver on . If your model does support this feature please let me know the exact device identifier. I will implement a flow card for setting the angle for your model if it's supported.

The dim capability is supposed to set the swing mode angle as well for supported models. I'll make sure it's not not show on devices that do not support setting the swing mode angle. Not sure why it shows 400% though. Need to check that as well.

But please let me know the exact model of your device.

**Comment by pjmpessers** [comment]
Thanks for the quick responce. It is indeed the dmaker.fan.1c. But i don't know where i can find the device identifier. Or is that the model ID?

**Comment by jghaanstra** [comment]
Are you sure it's the `dmaker.fan.1c `? You might be able to find it in the official Xiaomi app under device info somewhere. 

I checked the code and it it's really this model it should not have the angle capability as this is not supported according to the docs.

**Comment by pjmpessers** [comment]
I searched for device info on de original xiaomi app, but i can't find it. But the windows app to get a token showed the dmaker.fan.1c as model.

**Comment by jghaanstra** [comment]
Odd. Are you able to set the angle from the Xiaomi app or the device itself?

**Comment by pjmpessers** [comment]
Yesss. On the device physical and ofcourse in the device card on homey.

**Comment by pjmpessers** [comment]
The box says it is model JLLDS01XY.
Does this help?

**Comment by jghaanstra** [comment]
Could you restart the app, wait for 2 minutes and send me a diagnostic report afterwards. That way I can confirm the model identifier.

**Comment by jghaanstra** [comment]
Thanx, I guess the docs are wrong. I'll add the option for setting the angle for this model as well.

**Comment by pjmpessers** [comment]
c4b1a4de-c143-4c35-83d1-c22804546afd

Done. And switched on and off rotation. I hope it helped.

P.S. thanks for the quick response.

**Comment by pjmpessers** [comment]
Perfect. Thank you very much. 👍🏻🙏🏻

**Comment by jghaanstra** [comment]
I doubt it will be perfect. It's all very trial and error with incorrect docs, similar devices that all have their own implementation and no actual devices to test with. But we will see ...

**Comment by pjmpessers** [comment]
Not a problem. Understandable. I will try it out and let you know. In the meantime thanks for the app and your support.

**Comment by jghaanstra** [comment]
I've published the changes to the test channel. Could you test this version and let me know the outcome. You can switch back to the live version without loosing devices, settings or flows.

https://homey.app/a/com.xiaomi-miio/test/

**Comment by pjmpessers** [comment]
Thank for the test app. But it seems this is for the oscilation angle. I can set the angle like 30 degrees, but it is saying "Missing argument" But this is not for setting rotation on and off.

**Comment by pjmpessers** [comment]
Sorry. I gave it the wrong name. It is called swing modus in the device card. 😳

**Comment by jghaanstra** [comment]
Right. I pushed release 3.2.7 to the test channel. Could you test that.

https://homey.app/a/com.xiaomi-miio/test/

**Comment by pjmpessers** [comment]
Wow. Perfect. That worked. Thank you very much for the support and fix.

P.S. for me you could remove the oscillation angle. This one doesn't work. Oscillation stitching on and of does.

**Comment by jghaanstra** [comment]
Great, others might benefit frrom from the oscillation angle action card so I'll leave it in there.

Thanx again for the second donation. Much appreciated.

**Comment by pjmpessers** [comment]
Your welcome. And you for the support.

**Comment by pjmpessers** [comment]
Great. Solved.

**Comment by pjmpessers** [comment]
Great. Solved
