### ISSUE TITLE
Vacuum Mop "Then flow" issue

### ISSUE THREAD

**Issue by T0macher** [jghaanstra/com.xiaomi-miio#205]
Hi,

I found an issue, when i tried to send beck the vacuum cleaner to the dock, from a flow.
I tested, and when i use the "return to dock" card, it works as a "start cleaning". and i found the same issue, when i tried the "turn off" or "stop" cards.

Could you help please?
i ran a diag report: 27291425-9f62-41f5-9ca5-e67b4bef6e10

Thank you so much :)
Tamas

**Comment by jghaanstra** [comment]
I'll see if I can impriove this behaviour with the next release.

**Comment by T0macher** [comment]
Thank you so much!
