### ISSUE TITLE
Support for Roborock Vacuum S8 (roborock.vacuum.a51)

### ISSUE THREAD

**Issue by simonscorne** [jghaanstra/com.xiaomi-miio#206]
Hi there, 

I've just added a Roborock S5 and an Roborock S8 via your app. 
The Roborock S5 is working without any issues. 
But the Roborock S8 is not recognized and therefore I cannot use it via Homey. Is it possible to add the functionalities of this roborock?

Diagnostic report: 720b530b-9608-44c4-ac44-f164142392b4

**Comment by simonscorne** [comment]
I tried to follow the steps of your link. I am able to control the vacuum with the app on my PC. Unfortunately I do not understand any of the following steps. So I am not sure if I can help you get the information you need..

**Comment by simonscorne** [comment]
I just saw that the Roborock's name in the app is called roborock.vacuum.a51 not roborock S8

**Comment by jghaanstra** [comment]
I'm aware, the model is in the log. I just checked the code and I cant quite explain why it isnt working. Could try and re-pair it and restart the app after it's paired, wait 5 minutes and send me another diagnostig report.

**Comment by simonscorne** [comment]
I just re-paired and restarted the app. Hereby the diagnostic report code: 80957e30-693b-4641-a3ca-1ea461f9f23e

![WhatsApp Image 2023-05-31 at 17 50 42](https://github.com/jghaanstra/com.xiaomi-miio/assets/135128441/1809438a-b3c3-4bea-b9e0-eacbbefff3b2)

**Comment by jghaanstra** [comment]
Please re-test on version 3.2.9. Should be fixed.

**Comment by simonscorne** [comment]
Hey there, 

Thank you for working on this issue. I've just tested the functionality.
It is now possible to add the vacuum to Homey and reading the status of the filters, alarms and brushes is working.
Unfortunately it is not possible to turn the vacuum on and off.
Controlling the vacuum by changing the vacuum cleaner state is also not working. 
Changing the fanspeed or mop intensity does work properly.

I've added some images of the errors i've been getting and I also send you a diagnostic report: 
779c933d-7e69-47b7-8a95-54d6a596cb1f

![WhatsApp Image 2023-06-14 at 15 58 53 ((1)](https://github.com/jghaanstra/com.xiaomi-miio/assets/135128441/005d233b-fa97-4a1f-b0dc-925152c8a1e9))
![WhatsApp Image 2023-06-14 at 15 58 53](https://github.com/jghaanstra/com.xiaomi-miio/assets/135128441/f43d47d8-ed5d-422b-b366-df1b6c840b4d)
![WhatsApp Image 2023-06-14 at 15 58 52 (1)](https://github.com/jghaanstra/com.xiaomi-miio/assets/135128441/32d6bf1c-a9b0-4f7f-8b20-72f293969159)
![WhatsApp Image 2023-06-14 at 15 58 52](https://github.com/jghaanstra/com.xiaomi-miio/assets/135128441/53552dbf-7dce-4c92-90c5-d27e58009848)

**Comment by jghaanstra** [comment]
Ok, I'ss see if I can fix that in the next release.

**Comment by jghaanstra** [comment]
This issue should be fixed with release 3.2.10 which is now in test and awaiting approval from Athom to go live. Please test.

https://homey.app/a/com.xiaomi-miio/test/

**Comment by simonscorne** [comment]
I've just tested release 3.2.10 and the issues are now resolved. Thank you so much for your effort and support

**Comment by jeroendew** [comment]
@simonscorne  How did you got the S8 connected to Homey. I've managed to get the token and IP. But when i try to add it in homey i get a handshake timeout. 

What stept did you do to connect it?
