### ISSUE TITLE
Fan Speed on Smartmi Standing Fan 2S (zhimi.fan.za4) while using Advanced Smartmi/ZhiMi Fan (WiFi)

### ISSUE THREAD

**Issue by NAmRoD21v** [jghaanstra/com.xiaomi-miio#207]
Yesterday I added the Smartmi Standing Fan 2S (zhimi.fan.za4) as an Advanced Smartmi/ZhiMi Fan (WiFi). The device was added without any issues. But I noticed that changing the fan speed within the devices tab of Homey doesn’t change the fan speed of the Fan itself. Also there is no flow card to change the device speed. When I add the device using the Basic Smartmi/ZhiMi Fan (WiFi) I do have flow cards to change the speed, but not the possibility to change the fan speed in the device tab. 

Diagnostic Report: 106bb19b-9ade-4987-ac7e-3e94fe57d67c

Edit: created and added a new diagnostic report. The first one gave errors because I added the fan twice.

**Comment by jghaanstra** [comment]
I'll fix setting the fanspeed in the next release, it's currently broken for the advanced driver.

There is already a flowcard for it. It's called dim the device though as I'm re-using the dim capability for setting the fanspeed. Unfortunately flow cards are not renamed even when renaming a capability.

**Comment by NAmRoD21v** [comment]
Thanks for fixing it!

I've seen that flow card, but I didn't know it was for changing the fan speed. The only difference with the Basic device is that the advanced fan speed can only be changed from 100 to 200, 300 and 400 percent. Is it possible to change it from 0 to 100?

**Comment by jghaanstra** [comment]
I assume you are testing the release in the test channel as the fix has not been published live yet.

To get a 0-100% range it might be necessary to re-pair the device.

**Comment by NAmRoD21v** [comment]
I'm using version 3.2.7. 

The range from 100, 200, 300 and 400 is in the Then flow card: Dim to. It is already in the current version but doesn't do anything at the moment. I attached a screenshot to show what I mean. 

![Screenshot 2023-06-07 192405](https://github.com/jghaanstra/com.xiaomi-miio/assets/6766394/c0247390-18c3-4de9-ae7e-38d4082594c6)

**Comment by jghaanstra** [comment]
Just wait for the update. It's awaiting approval from Athom.

**Comment by NAmRoD21v** [comment]
I installed the test update and changing the fan speed within the device works as expected. Thanks for fixing!

One small issue though. The dim flow card for changing the fan speed can now be set between 50% to 10000%. The same goes for relative dim level. 

![Screenshot 2023-06-10 172858](https://github.com/jghaanstra/com.xiaomi-miio/assets/6766394/fcc65af8-dfe7-468e-bf88-245ad2ee01a2)

**Comment by jghaanstra** [comment]
The test version is currently the same as live as it was approved by Athom some days ago.

I'll hope to fix the strange range of these action cards with the next release (`3.2.9`). It could be you would need to re-pair the device when it's released though.

**Comment by jghaanstra** [comment]
Should be fixed now but you might need to re-pair.

**Comment by NAmRoD21v** [comment]
When the last update (3.2.9) arrived, I re-added my device. The percentage in the flows now correct :D! Unfortunately the old issue of not being able to change the fan speed has returned. In both flows and on the device itself I can change the fan speed but nothing happens. The fan stays on the same speed :(.

**Comment by jghaanstra** [comment]
Pfff, will fix that with the next release.

**Comment by chiroptera-git** [comment]
I have a similar issue with standing fan 2S running on app version 3.2.10:
Device is unreachable: user ack timeout
The device is connected for a few seconds and unreachable afterwards, thus I am not able to change any user settings in the app in order to try shorter polling frequencies for example.

**Comment by jghaanstra** [comment]
> I have a similar issue with standing fan 2S running on app version 3.2.10: Device is unreachable: user ack timeout The device is connected for a few seconds and unreachable afterwards, thus I am not able to change any user settings in the app in order to try shorter polling frequencies for example.

Send a diagnostic report from the app settings.

**Comment by chiroptera-git** [comment]
> 

02493874-7741-4711-af3e-75607a2c1834

**Comment by chiroptera-git** [comment]
> Send a diagnostic report from the app settings.

02493874-7741-4711-af3e-75607a2c1834

**Comment by chiroptera-git** [comment]
@jghaanstra 
Your suggestion to "remove the device from Homey, resetting the fan to get a new
token and re-add it to Homey afterwards." does not work. I was adding the fan with the new token but it results in the same problem. The vaccum cleaner S5 runnung on same hard and software is working without any problems. Something else I can try?

**Comment by jghaanstra** [comment]
Please continu this on the support forum. Your problem is not related to this Github issue.

**Comment by jghaanstra** [comment]
> When the last update (3.2.9) arrived, I re-added my device. The percentage in the flows now correct :D! Unfortunately the old issue of not being able to change the fan speed has returned. In both flows and on the device itself I can change the fan speed but nothing happens. The fan stays on the same speed :(.

Can you confirm this to be fixed with release `3.2.11`?

**Comment by NAmRoD21v** [comment]
With the latest release I can control the fan within the devices tab as well as with the flows. The only issue I have now is that I get an unknown_error when I set the fan speed to 7%.

**Comment by jghaanstra** [comment]
> With the latest release I can control the fan within the devices tab as well as with the flows. The only issue I have now is that I get an unknown_error when I set the fan speed to 7%.

Weird but sounds like an issue with the unofficial implementation. Probably not something I'm gonna or even can fix. Feel free to send me a diagnostic report. If there really is something in there I'll open this ticket again.

**Comment by NAmRoD21v** [comment]
Hereby the diagnostic report for the 7% problem.
983246e3-f286-4dce-801d-af5f47f8aaaa

**Comment by jghaanstra** [comment]
Not something I can solve, It's something network related. I'm adding the error for possible future reference.

```
stderr:
    2023-07-06T19:45:06.253Z [err] [ManagerDrivers] [Driver:fan_zhimi_advanced] [Device:15132b87-82ab-45da-8c89-78193b5450ce] Error
    at Object.reject (/app/node_modules/miio/lib/network.js:541:14)
    at DeviceInfo.onMessage (/app/node_modules/miio/lib/network.js:430:9)
    at Socket. (/app/node_modules/miio/lib/network.js:180:13)
    at Socket.emit (node:events:513:28)
    at UDP.onMessage [as onmessage] (node:dgram:933:8) {
  code: -5001
}
```
