### ISSUE TITLE
Issue Connecting Xiaomi Gateway 3 and Mi temp and humidity sensor

### ISSUE THREAD

**Issue by ricoxdela** [jghaanstra/com.xiaomi-miio#208]
Hi,
It looks like I can connect Xiaomi Gateway 3 lumi.gateway.mgl03 but can't add Mi humidity and temp sensor miaomiaoce.sensor_ht.t2. anyone can help me adding those devices 15 of them ?

**Comment by jghaanstra** [comment]
`Xiaomi Gateway 3 lumi.gateway.mgl03` is not supported as the API is different then the older models. And since the API is not documented support can not be added.
