### ISSUE TITLE
smartmi Air purifier 2  zhimi.airpurifier.za1. errors during flows

### ISSUE THREAD

**Issue by jampeef** [jghaanstra/com.xiaomi-miio#209]
I get errors when changing mode using flows on my smartmi Air purifier 2 (zhimi.airpurifier.za1) , mode gets changed but it spits out the error . “Invalid capability (homey:app:com.xiaomi-miio:airpurifier_zhimi_mode) value type. Expected: string. Got: number”

**Comment by jghaanstra** [comment]
Duplicate: https://github.com/jghaanstra/com.xiaomi-miio/issues/207
