### ISSUE TITLE
Missing card?

### ISSUE THREAD

**Issue by BrapBrapp2** [jghaanstra/com.xiaomi-miio#210]
On one off my smart standing fans there is no flow cards for Straight Wind and Natural Wind, if I go under the device settings I can change without no problem

Diagnostic code 

8e9b5625-86c2-497a-b672-7af2995c2f78

**Comment by jghaanstra** [comment]
I checked and there is nothing wrong with the code. There should be an action card named `Set Mode`. Please double check.

**Comment by BrapBrapp2** [comment]
I know, my other two smart standing fan have a mode card, but not the Smart standing fan Pro. It is missing the card.
![IMG_0645](https://github.com/jghaanstra/com.xiaomi-miio/assets/31710271/246b9acd-246e-44aa-9126-fe83f09940e2)
![IMG_0644](https://github.com/jghaanstra/com.xiaomi-miio/assets/31710271/9f4b4b08-68e6-45a5-a3e2-7d2f122ac13e)

**Comment by jghaanstra** [comment]
Have you tried re-adding the device. It was probably added later and is now not available for this device?

**Comment by jghaanstra** [comment]
Found the issue. It's a bug that will be fixed with release 3.2.10.

**Comment by BrapBrapp2** [comment]
Great! Nice work :)

**Comment by jghaanstra** [comment]
This issue should be fixed with release 3.2.10 which is now in test and awaiting approval from Athom to go live. Please test.

https://homey.app/a/com.xiaomi-miio/test/

**Comment by BrapBrapp2** [comment]
I can confirm that it is fixed! The card is showing up and works fine. Thanks!
