### ISSUE TITLE
Can't add my Dreame Bot W10 Pro cleaner

### ISSUE THREAD

**Issue by Stupi** [jghaanstra/com.xiaomi-miio#211]
Hello,

I tried to add my cleanr Dream Bot W10 Pro to the homey pro 2023 but I'm receiving error message below after cleaner is added:
I'm 100% sure that IP address and token are correct.

Device is unreachable: Cannot read properties of undefined (reading 'get_properties')

Model: dreame.vacuum.p2027
![Screenshot 2023-06-13 at 16 58 59](https://github.com/jghaanstra/com.xiaomi-miio/assets/7235969/4d2e7957-7b21-4968-b953-7899791b6be8)

**Comment by Stupi** [comment]
I'm not sure if it will be helfull but here is integration for Home Assistant
https://github.com/Tasshack/dreame-vacuum

**Comment by Stupi** [comment]
Thanks for update. I really appreciate it!

**Comment by jghaanstra** [comment]
Thanx for the donation, much appreciated as well!

**Comment by Stupi** [comment]
Hi thanks for update of app. It's working now. Just want to ask, do you consider to add functionality to choose rooms to clean and also how cleaning times - it's option for dreame w10 pro at least.

![IMG_9207](https://github.com/jghaanstra/com.xiaomi-miio/assets/7235969/d37e00e9-5a75-4f07-9de9-864638a0e2c3)
![IMG_9206](https://github.com/jghaanstra/com.xiaomi-miio/assets/7235969/011404ff-b454-4a5f-8d9d-2fd70c66775d)
