### ISSUE TITLE
New functionality for flow - set rooms for cleaning & cleaning times

### ISSUE THREAD

**Issue by Stupi** [jghaanstra/com.xiaomi-miio#213]
Hello,

I want to ask if you can add functionality for dreame w10 pro:

1. set rooms for cleaning
2. set cleaning times - what I see on Tasshack implementation, it has to have some api call - https://github.com/Tasshack/dreame-vacuum 
![IMG_9207](https://github.com/jghaanstra/com.xiaomi-miio/assets/7235969/87eb102b-8f20-4991-9772-ffdca03e2df7)
![IMG_9206](https://github.com/jghaanstra/com.xiaomi-miio/assets/7235969/cba00377-3da8-43c0-8502-03bbd3a82732)

**Comment by jghaanstra** [comment]
Please point me to the exact  miio/miot API command for clean times. I wont be able to add it otherwise.

**Comment by Stupi** [comment]
I'm not sure if this will be helpful - https://github.com/Tasshack/dreame-vacuum/blob/master/docs/services.md - it's called repeats = cleaning times

**Comment by jghaanstra** [comment]
Nope, I need the miio / miot API command.

**Comment by jghaanstra** [comment]
I have tried to add a flow card to start the cleaner with room selection with release 3.2.10 which is now in test and awaiting approval from Athom to go live. Please test.

https://homey.app/a/com.xiaomi-miio/test/

I didnt find the right documentation to add cleaning times.

**Comment by jghaanstra** [comment]
No response, closing issue.
