### ISSUE TITLE
[BUG] mmgg.pet_waterer.wi11 (Smart Pet Water Dispenser)

### ISSUE THREAD

**Issue by Devstored** [jghaanstra/com.xiaomi-miio#214]
Good morning,

I can't add my XIAOMI Smart Pet Water Dispenser. It is listed in supported objects, but I get a handshake timeout.

I don't know if the integration of this object is planned in the Roadmap?

Thank you so much !

![IMG_C76FAA28967E-1](https://github.com/jghaanstra/com.xiaomi-miio/assets/46482210/d0f68079-197f-4014-add0-6b7debc9bfa7)

**Comment by jghaanstra** [comment]
Handshake time outs usually happen when the used token is incorrect. You might need to reset the device to get a new token.

**Comment by jghaanstra** [comment]
No response, closing issue.
