### ISSUE TITLE
add new device MJXFJ-80-G3

### ISSUE THREAD

**Issue by oly1294** [jghaanstra/com.xiaomi-miio#215]
Thanks for the wonderful app, but could you add the MJXFJ-80-G3 air purifier to the list of equipment. Thank you!

**Comment by jghaanstra** [comment]
See https://github.com/jghaanstra/com.xiaomi-miio/wiki/Adding-new-devices

Without any of the three options I can not add the device.

**Comment by oly1294** [comment]
Thank you for quick response!
I'm not very good at programming, but this device is a variation of the MJXFJ-150-G1 model, via "get mi home device token" but is defined as: Model: [zhimi.airfresh.ua](http://zhimi.airfresh.ua/). Added to Home as MJXFJ-150-G1, but none of the control commands work. tell me what will be the easiest way to transfer you the necessary data for its integration in Nome? Thanks a lot!

**Comment by jghaanstra** [comment]
Seems parameters are described here: https://github.com/al-one/hass-xiaomi-miot/issues/1015#issuecomment-1415735249

**Comment by jghaanstra** [comment]
Support has been added with release 3.2.10 which is not in test and awaiting approval from Athom to go live. Please test.

https://homey.app/a/com.xiaomi-miio/test/

**Comment by oly1294** [comment]
Thanks a lot! everything is working. You are the best programmer in the world!
