### ISSUE TITLE
Dreame Bot W10 Pro (dreame.vacuum.p2027) - can't turn on/off 

### ISSUE THREAD

**Issue by Stupi** [jghaanstra/com.xiaomi-miio#216]
Hello,

thanks for add dreame bot w10 pro to supported devices. It works a few days. I tried today remove device and add it back but it's not working properly after this action. I'm receiving error - Device Unavailable Device is unreachable: state is not defined. It appears for a few seconds but if I clicked on turn on I receive error - Missing Capability Listener: onoff

**Comment by jghaanstra** [comment]
Fixed this error locally `Device Unavailable Device is unreachable: state is not defined`. Not sure if that will also fix `Missing Capability Listener: onoff`. But we will see after the release of version 3.2.10.

**Comment by jghaanstra** [comment]
This issue might be fixed with release 3.2.10 which is now in test and awaiting approval from Athom to go live. Please test.

https://homey.app/a/com.xiaomi-miio/test/

**Comment by jghaanstra** [comment]
No response, closing issue.
