### ISSUE TITLE
Yeelink light / Xiaomi Smart bulb

### ISSUE THREAD

**Issue by Agrux** [jghaanstra/com.xiaomi-miio#217]
Hello,

I have the message "this miio.setpower is not a function" when I'm trying to interact with my yeelink.light.color5.
I have installed v3.2.10 experimental but it don't change.
Could you help me ?

**Comment by jghaanstra** [comment]
Yeelights are not supported by this app. Use https://homey.app/en-gb/app/com.yeelight/Yeelights-LAN/

(And please use the support forum for these type of questions, GitHub is for bugs and features)
