### ISSUE TITLE
Please add support for Xiaomi Mijia Smart Safe

### ISSUE THREAD

**Issue by GoodT** [jghaanstra/com.xiaomi-miio#218]
Dear developer, 

I would like to kindly ask you if is possible to add support for [Xiaomi Mijia Smart Safe](https://www.youtube.com/watch?v=bYKEMPsB0CM). Its not needed to add all the functionality, but notification from it will be very helpful.

Thanks

**Comment by jghaanstra** [comment]
This is a Bluetooth device. The Xiaomi Mi Home app only supports WiFi devices and a couple of ZigBee devices connected to a WiFi connected gateway.
