### ISSUE TITLE
Please add support for Smartmi Smart Fan

### ISSUE THREAD

**Issue by krl691** [jghaanstra/com.xiaomi-miio#219]
I would be very grateful if you could add support for Smartmi Smart Fan Heater model: zhimi.heater.nb1. 

[https://eu.smartmiglobal.com/pages/fan-heater](url)

[https://www.openhab.org/addons/bindings/miio/](url)

**Comment by krl691** [comment]
I installed the latest version but get "unknown model", see screendump below. The fan responds when you access it in Homey and press the slider, but only a beep from the fan and nothing else. The on/off switch does not work. This model does not have stepless speed/heat, only warm or hot and off or on.
![Skjermbilde 2023-06-30 115917](https://github.com/jghaanstra/com.xiaomi-miio/assets/121890807/38604876-f2d9-4542-ab71-92c700116eeb)

**Comment by jghaanstra** [comment]
Send a diagnostic report from the app settings. But if you device is identified as unknown model it might not be of the model you requested support for.

**Comment by krl691** [comment]
I dont know, but its the model that the tokenapp is reporting, se attachment. My router gives me this on my DHCP-adress: zhimi-heater-nb1_mibt77F3

Diagnostic code from the app: 8806488c-550e-4ad4-878e-8d08b4b0752d

Regards,
Kai R. Limi


Fra: Jelger ***@***.***>
Sendt: fredag 30. juni 2023 kl. 12:42
Til: ***@***.***>
Kopi: Kai R. ***@***.***>; ***@***.***>
Emne: Re: [jghaanstra/com.xiaomi-miio] Please add support for Smartmi Smart Fan (Issue #219)


Send a diagnostic report from the app settings. But if you device is identified as unknown model it might not be of the model you requested support for.

**Comment by jghaanstra** [comment]
As the device does not identify itself through Homey I'm not sure the Homey app will work for this device. I'll fix some issues in the log where the device seems to behave differently than the documentation I found on this device but if it will ever work properly I cant tell.

**Comment by krl691** [comment]
I'm grateful anyway, and we'll see what you come up with.

Attached is what Xiaomi's app shows in terms of functionality on the fan itself.

Fra: Jelger ***@***.***>
Sendt: fredag 30. juni 2023 kl. 13:00
Til: ***@***.***>
Kopi: Kai R. ***@***.***>; ***@***.***>
Emne: Re: [jghaanstra/com.xiaomi-miio] Please add support for Smartmi Smart Fan (Issue #219)


As the device does not identify itself through Homey I'm not sure the Homey app will work for this device. I'll fix some issues in the log where the device seems to behave differently than the documentation I found on this device but if it will ever work properly I cant tell.

**Comment by jghaanstra** [comment]
You cant send attachments to Github over email. Add it on Github itself.

**Comment by krl691** [comment]
Attached is what Xiaomi's app shows in terms of functionality on the fan itself.
![Skjermbilde 2023-06-30 130414](https://github.com/jghaanstra/com.xiaomi-miio/assets/121890807/b305ed62-ac2e-45cc-b73e-a1971abac70d)
![Skjermbilde 2023-06-30 130456](https://github.com/jghaanstra/com.xiaomi-miio/assets/121890807/56cfb369-49ef-4001-93c6-005480774974)

**Comment by krl691** [comment]
Now it looks much better! It no longer shows as unknown and I can turn it on or off, but lacks functions such as warm or hot (It only has 2 heat settings) and oscillation.

Very nice progress, thanx!

Fra: Jelger ***@***.***>
Sendt: mandag 31. juli 2023 kl. 19:57
Til: ***@***.***>
Kopi: Kai R. ***@***.***>; ***@***.***>
Emne: Re: [jghaanstra/com.xiaomi-miio] Please add support for Smartmi Smart Fan (Issue #219)


Could you re-test this with release 3.2.12 which is currently pending approval in the test channel.

https://homey.app/a/com.xiaomi-miio/test/

**Comment by jghaanstra** [comment]
Please submit a new feature request if you want that added. It's functionality which isnt available for other heaters and requires extra work. Such features have less priority over bugs.
