### ISSUE TITLE
iOS Jailbreak documentation correction

### ISSUE THREAD

**Issue by vladkorotnev** [jghaanstra/com.xiaomi-miio#22]
The documentation in https://github.com/jghaanstra/com.xiaomi-miio/blob/master/docs/obtain_token.md

states the following path:
`/var/mobile/Containers/Data/Application/514106F3-C854-45E9-A45C-119CB4FFC235/Documents/USERID_mihome.sqlite`

for the database.

However the UUID is also different on every installation and device. It would be better if there was a note stating that besides the path.

Thanks in advance

**Comment by jghaanstra** [comment]
Fixed with https://github.com/jghaanstra/com.xiaomi-miio/issues/22

Thanx!

**Comment by vladkorotnev** [comment]
Sorry to bother, but it displays a bit odd for some reason, like so:
!(screenshot)[http://i.imgur.com/bcWeThO.png]

Probably the "<>" made the markdown parser think it's an HTML tag of sorts and need to be escaped.

**Comment by jghaanstra** [comment]
Thanx, fixed that.
