### ISSUE TITLE
Xiaomi Gateway v2 not responding

### ISSUE THREAD

**Issue by Robovh** [jghaanstra/com.xiaomi-miio#221]
I have adding the xiaomi gateway v2 to homey using the Xiaomi Mi Home app, which works fine.
But directly after adding the gateway to homey it stops responding within homey.
When clicking on the device I get this message:
![thumbnail_Screenshot_20230710-113807](https://github.com/jghaanstra/com.xiaomi-miio/assets/7330469/d6d5e998-aec8-4d10-a151-e7be71ffe002)

And this message when looking at the device:
![thumbnail_Screenshot_20230710-113914](https://github.com/jghaanstra/com.xiaomi-miio/assets/7330469/eb1a73ee-d52f-4766-8645-a3fe99760ca1)

How can I solve this?

Diagnostic Report: 88639320-3d2c-4be1-ae99-d9eb2b5ac0f0

**Comment by jghaanstra** [comment]
It's a bug, I'll see if I can fix it with the next release but it's tricky. Not sure why your device shows this error. Is it's firmware up to date?

**Comment by jghaanstra** [comment]
Adding the device as WiFi device to control the light and alarm etc. is completely unrelated to adding the device as hub for Zigbee sub devices in the configuration tab. The error is only on the WiFi device for light and alarm etc. After adding the gateway as Zigbee gateway you should be able to add these Zigbee subdevices to Homey.

But you should only do this if you are having trouble using the Zigbee devices directly with Homey. Since you probably havent tried that yet you should try the aqara app first: https://homey.app/nl-nl/app/com.xiaomi-mi/Aqara/

**Comment by Robovh** [comment]
Well that’s good to know, then I found this bug accidentally.
I most definitely have used the aqara app, that’s actually the reason that I bought this gateway/hub. Since I apparently have the same issue as everybody else using the aqara/xiaomi motion sensors, that they stop responding after 20min/3hours.
For me I found out that the reason they stop responding is because they have a robb shop light as last zigbee router. Where if the last zigbee routing point would have been an ikea socket they will continue to work properly, but I cannot manually assign with zigbee router device is their last chain in the network.
Therefor my plan was to buy this gateway and add all zigbee devices to the gateway and let homey access them through the gateway in order to consistently be able to use them.

But if I understand correctly. When I configure the gateway in the Xiaomi Mi Home app config, I should be able to just click device and then add an aqara motion sensor (gateway) for example and it should be listed as long as I have one configured in the Xiaomi Home app?

**Comment by jghaanstra** [comment]
```
But if I understand correctly. When I configure the gateway in the Xiaomi Mi Home app config, I should be able to just click device and then add an aqara motion sensor (gateway) for example and it should be listed as long as I have one configured in the Xiaomi Home app?
```
If the gateway has been correctly connected as a gateway under the app settings, then yes, it should work like this.

**Comment by Robovh** [comment]
Oke that’s good to know, I have check and in the app setting it states 0 devices. I’m currently trying if it makes a difference it the devices are added to the hub after it has been configured to homey or before. But that doesn’t seem to make a difference.

**Comment by Robovh** [comment]
I did some more testing today and the devices are indeed listed when the gateway is configured correctly in the app settings. After setting up the gateway in the app settings, the gateway ip and token fields are filled with default data but do have a green check (v) at the end.

I don’t know if entering the correct data there or just some time made the devices appear, but now I can add devices from the gateway to homey even just added ones.

Also within the settings tab where the gateways are listed, the gateway states “Connected Devices 0”. I don’t know if this means the amount of devices that are connected to the gateway, or the amount of devices that homey has connected from this gateway. If it is either one of those this value doesn’t seem to be updated.

![image](https://github.com/jghaanstra/com.xiaomi-miio/assets/7330469/a22ae5ec-6765-450b-8dc9-a4920666b9b4)

**Comment by jghaanstra** [comment]
Could you re-test the WiFi driver for the gateway  this with release 3.2.12 which is currently pending approval in the test channel.

https://homey.app/a/com.xiaomi-miio/test/

**Comment by Robovh** [comment]
Hee @jghaanstra, I had some delay. Im currently trying to test this, since the version 3.2.12 has already auto updated to my Homey. But it seems I cannot add a Xiaomi Gateway v2 (WIFI) device, when I test connection it states "Could not connect to device, handshake timeout".

In my app it states that I have version v3.2.12, do I have to do something differently in order to get the test version?
Is there something else I might need to try?

**Comment by jghaanstra** [comment]
> Could not connect to device, handshake timeout".

This means your token is not correct. Try resetting the device and start from scratch.

**Comment by Robovh** [comment]
Forgot to post response, my bad. But the problem is solved.
