### ISSUE TITLE
Please add smart kettle

### ISSUE THREAD

**Issue by massari46** [jghaanstra/com.xiaomi-miio#222]
Can you add viomi smart kettle (same with Xiaomi smart kettle). Connecting with Bluetooth.

And can you add Xiaomi Mi Body Composition Scale 2 Smart connecting with Bluetooth.

Thank you so much .

**Comment by jghaanstra** [comment]
No, this app is WiFi devices only.

**Comment by massari46** [comment]
> No, this app is WiFi devices only.

Okey thank you
