### ISSUE TITLE
Mi Smart LED Bulb Essential - this.miio.setPower is not a function

### ISSUE THREAD

**Issue by rentisob** [jghaanstra/com.xiaomi-miio#223]
Hi! I'm trying to add a Mi Smart LED Bulb Essential to Homey, IP address and token were obtained, it's connected and successfully added to my Homey, but then I cannot control it, getting this message: 
this.miio.setPower is not a function

Reported issue: c55fdefb-3d72-44dc-9228-f0ccba61cdac
Do you have an idea what can cause this? 

Thanks,
Csaba

**Comment by jghaanstra** [comment]
You are trying to add a Yeelight using the Xiaomi Mi Home app. Use this app instead: https://homey.app/en-gb/app/com.yeelight/Yeelights-LAN/

**Comment by rentisob** [comment]
When I'm trying to add it to Yeelight app, then it always fails. I could add easily this bulb to Xiaomi app, but not to the Yeelight. Checked with all available type of bulbs in Yeelight, it does not work with either. 

Please see the message: 
![kép](https://github.com/jghaanstra/com.xiaomi-miio/assets/74683402/ed080728-c367-41a3-8948-d0444159a274)

**Comment by jghaanstra** [comment]
You are using the Yeelight app from Athom which is crap. Use the one I linked to in the previous message.

**Comment by rentisob** [comment]
I thought that the mobile app is also needed (because your app does not find any device), this was the reason why I tried to add first the bulb to the IOS based Yeelight app and then use your version in Homey. 
Unfortunately when I'm searching in Homey with your Yeelight LAN app then it does find any device.

See the pictures:
![yeelight_lan](https://github.com/jghaanstra/com.xiaomi-miio/assets/74683402/ab831475-0b00-4a77-b2f6-76e7dad81205)
![yeelight_lan_2](https://github.com/jghaanstra/com.xiaomi-miio/assets/74683402/9542cf32-7e92-486e-9aba-ec26f6125816)

What is the method to connect a bulb to Homey Yeelight LAN? Do I have to already connect it to the Wi-Fi network first and then search via the Yeelight LAN app (same network as Homey of course)? Or should be the bulb in AP mode and then search via the Yeelight LAN app directly? (Or as my first try to use the Yeelight IOS based app and then the Homey's Yeelight LAN app?)

Thank you for your help! 
Csaba

**Comment by jghaanstra** [comment]
It needs to be added to wifi, to the yeelight official app and there you need to enable LAN control. See https://community.homey.app/t/app-yeelights-lan-needs-other-developer/21134

**Comment by rentisob** [comment]
Ok, understood, that's the way that I wanted to follow, but unfortunately my bulb cannot be recognised by the official Yeelight app. I will ask the Yeelight support now.
