### ISSUE TITLE
Add support for Aqara Radiator Thermostat E1

### ISSUE THREAD

**Issue by Jokubiko** [jghaanstra/com.xiaomi-miio#225]
Add support for the Aqara Radiator Thermostat E1, model SRTS-A01.

https://www.aqara.com/eu/product/radiator-thermostat-e1

**Comment by jghaanstra** [comment]
Probably not, this is a Zigbee device which I'm not sure of can be supported by the current Zigbee gateway integration. I know direct support is being added in the Aqara app though: https://homey.app/a/com.xiaomi-mi/ .

If you really want it integrated through the gateway I would need a device to test with  (without guarantee I can make it work);

Let me know if you want to donate the device to possibly have it integrated, else I'll close this request.

**Comment by Jokubiko** [comment]
Thanks for the feedback. You can close the case.

Op za 22 jul. 2023 om 19:10 schreef Jelger Haanstra <
***@***.***>
