### ISSUE TITLE
Roborock S8 Ultra Pro not function correctly

### ISSUE THREAD

**Issue by OneGoogus** [jghaanstra/com.xiaomi-miio#226]
Hi

I was able to add my Roborock S8 Ultra Pro, and it reads status just fine. 

but everytime I try to change anything I just get errors like: args.device.miio.find is not a function.
I have tried to reinstall the app to see if there was any problems there.

Dianostic Report: 8054de8f-2244-4115-a8b3-f5b5501b4883

**Comment by jghaanstra** [comment]
This device isnt supported (yet) as can be seen here: https://github.com/jghaanstra/com.xiaomi-miio/wiki/Supported-Devices

**Comment by jghaanstra** [comment]
Could you test this with release 3.2.12 which is currently pending approval in the test channel.

https://homey.app/a/com.xiaomi-miio/test/

**Comment by OneGoogus** [comment]
I get no errors at all, and it seems to respond on any flow changes i have tried. But its late, so can't test it completely right now. but I'm working from home office tomorrow, so I can give it a test on all functions tomorrow.

**Comment by OneGoogus** [comment]
All tested, and it works perfectly. great job Jelger.
