### ISSUE TITLE
Missing features RoboRock S8 - action card for vacuum/mop mode and bin notification

### ISSUE THREAD

**Issue by jeroendew** [jghaanstra/com.xiaomi-miio#227]
I've the roborock S8 connected to the app. But i'm missing some flow card hopefully it's possible to add these to the app?
I would like to have card to choose between Vacuum, Mopping or Both and if possible to set the intensity in the same card.

And i don't understand these cards, where or what is getting cleaned?
 - Start vacuuming
 - Start vacuuming one spot

Greetings,
Jeroen

**Comment by jghaanstra** [comment]
With what app do you have the vacuum cleaner connected? I dont recognize these action cards as part of the Xiaomi Mi Home app.

**Comment by jeroendew** [comment]
I'm connected with the Mi home app. 
When I select vacuum/water icon (img 1). Then I get these options. (img 2)
![image](https://github.com/jghaanstra/com.xiaomi-miio/assets/57914031/e8b0b5a5-8eec-4607-8fd8-9378bccd22cf)
![image](https://github.com/jghaanstra/com.xiaomi-miio/assets/57914031/3cac502b-781b-4cbe-b28f-921e0ff54260)

Also the flow card scrob intensity is not working (img 3)
![image](https://github.com/jghaanstra/com.xiaomi-miio/assets/57914031/c953e33e-d5f9-4a14-a456-1fefe6f81b22)

**Comment by jghaanstra** [comment]
This action card is not coming from the Xiaomi Mi Home app but probably from the Roborock app. That is not my app. You should either move the robot to the Xiaomi Mi Home app or ask your questions to the developer of the Roborock app (which I believe is not responding anymore).

**Comment by jghaanstra** [comment]
> I would like to have card to choose between Vacuum, Mopping or Both and if possible to set the intensity in the same card
I'll see if I can add that. It's tricky though as not all vacuums support this option.

>Start vacuuming
Well, it starts to vacuum with the default settings

> Sport clean
Will clean the area around the location where the vacuum has been sent

> Also the flow card scrob intensity is not working (img 3)
Its a bug which I fixed and will be part of the next release.

> And is there a tag/notification possible for bin full?
No as this is not supported by a lot of the vacuum cleaners.

**Comment by jeroendew** [comment]
Thanks for the explanations and trying to add those features

**Comment by jghaanstra** [comment]
I have added experimental support for an action card that allows to select sweep/mop and intensity with release 3.2.13. I'm not sure it will work so it needs to be tested. This version is currently pending approval. Please use the test version to test it.

https://homey.app/a/com.xiaomi-miio/test/

I looked into the dustbin data but I see no way to retrieve it. Possible support is further tracked here: https://github.com/jghaanstra/com.xiaomi-miio/issues/230

**Comment by jeroendew** [comment]
I've tested it. It changes the vacuum en mop intensity but not the mode.
I also receive this error :
![image](https://github.com/jghaanstra/com.xiaomi-miio/assets/57914031/ec382ee9-dff4-453f-874c-f2b41f4b361f)

**Comment by jghaanstra** [comment]
I'll try and fix that with the next release.

**Comment by jghaanstra** [comment]
This should be fixed with release 3.2.14 which is currently pending approval by Athom. Please test it.

https://homey.app/a/com.xiaomi-miio/test/

**Comment by jeroendew** [comment]
Thanks, this does work :-)
