### ISSUE TITLE
Feature request Smartmi Smart Fan/zhimi.heater.nb1

### ISSUE THREAD

**Issue by krl691** [jghaanstra/com.xiaomi-miio#228]
Please add functions such as warm or hot (It only has 2 heat settings) and oscillation.

**Comment by jghaanstra** [comment]
This has been added with release 3.2.13 which is pending approval. Please use the test version to test it.

https://homey.app/a/com.xiaomi-miio/test/

**Comment by krl691** [comment]
Now it looks really good! 👍 But could you add where you adjust the slider (the pole) up and down, a text called "Constant Temp" and degrees from 16 to 30. It is in accordance with the app. Beyond that, I see no problems. I have not yet tested flows.

**Comment by jghaanstra** [comment]
> But could you add where you adjust the slider (the pole) up and down, a text called "Constant Temp" and degrees from 16 to 30. It is in accordance with the app. Beyond that, I see no problems. I have not yet tested flows.

No, I have no control over these elements of the user interface of the Homey app.

**Comment by krl691** [comment]
Oscillation via flows does not work. I also do not have access to the slider in flows, see the attached image. And regarding the slider, if you can't make it so that it shows adjustment from 16 to 30 degrees, it would be good if it got a label that says "constant temp" at least. This can be switched on and off in the app so that the fan never switches off regardless of the temperature.
![Skjermbilde 2023-08-25 131858](https://github.com/jghaanstra/com.xiaomi-miio/assets/121890807/1f1618d2-553c-4062-a094-ca3f7634f8ff)

**Comment by jghaanstra** [comment]
> Oscillation via flows does not work.

You need to supply more info if you expect me to solve this.

>  I also do not have access to the slider in flows

Please submit a new feature request for an action card for setting the target temp on a Smartmi Heater

> And regarding the slider, if you can't make it so that it shows adjustment from 16 to 30 degrees, it would be good if it got a label that says "constant temp" at least.

I also have no control over that as well. You should ask Athom about changing the way custom capabilities are shown. See the documentation here: https://apps.developer.homey.app/the-basics/devices/capabilities#custom-capabilities

**Comment by krl691** [comment]
Okay, sorry. But it is quite simple. See Attachment. The oscilation does not respond to "On" via flows, but actually "Off" works.(if the app already has set it on).
![Skjermbilde 2023-08-25 134823](https://github.com/jghaanstra/com.xiaomi-miio/assets/121890807/5bd23204-6bf2-44c7-9562-76b8d8e40d26)

**Comment by jghaanstra** [comment]
Will fix that with the next release.

**Comment by jghaanstra** [comment]
This should be fixed with release 3.2.14 which is currently pending approval by Athom. Please test it.

https://homey.app/a/com.xiaomi-miio/test/

**Comment by krl691** [comment]
Now with the 3.2.14 the oscilitian feature works with action cards in flows. Thanx! But target temperature does not work, either manually by entering the device or via flow and action card. There is also no action card to switch off the target temperature (continues mode).

**Comment by krl691** [comment]
Just to add to the last comment - I'm getting the error message "Value is not defined" when using the action card for target temperature.

**Comment by krl691** [comment]
There is no error message when adjusting target temperature from the device in Homey, just a sound from the fan it self. But the target temperature in the app in my phone is not repsonding. I can send a diagnostic report. 👍

**Comment by krl691** [comment]
Heres is the diagnostic code: 0570167c-aecf-4f32-85fe-bef47c1e1533

**Comment by jghaanstra** [comment]
No error in there as well. There is nothing I can do to fix this without having the physical device.

**Comment by krl691** [comment]
Ok, but maybe the slider and the action card should bee removed from the device in Homey since it doesn't work either in flows or directly on the device?

**Comment by jghaanstra** [comment]
I havent heard it not to be working for other heaters. There are more models supported by this driver.

**Comment by krl691** [comment]
I thought this one was the only with heating supported by your app, but okey, I can live without the target temperature. Thanx anyway. 👍

**Comment by jghaanstra** [comment]
I'm closing this as there is not much more to do without having the device myself.
