### ISSUE TITLE
Mi Robot Vacuum Cleaner, Fan little bug

### ISSUE THREAD

**Issue by robiebab** [jghaanstra/com.xiaomi-miio#23]
If you set the fan speed trough homey card (fan speed) it keeps spinning like something needs to be executed, except it already is executed.

steps to repeat
-create a flow
-set fanspeed to silent or other
-run flow
-see that the card keeps spinning

**Comment by jghaanstra** [comment]
I'll fix this in the next release.

**Comment by jghaanstra** [comment]
Fixed with https://github.com/jghaanstra/com.xiaomi-miio/commit/e4f5716df117ee72ecd21df83e6ee0cd79aa54d8
