### ISSUE TITLE
Support for dmaker.fan.p18 (Mi Smart Fan 2)

### ISSUE THREAD

**Issue by Dergers** [jghaanstra/com.xiaomi-miio#233]
Hello,

is it possible to add the Mi Smart Standing Fan 2 (dmaker.fan.p18)?

Thank you
Dergers

**Comment by jghaanstra** [comment]
What's not working. It should already be supported.

https://github.com/jghaanstra/com.xiaomi-miio/wiki/Supported-Devices#fans

**Comment by Dergers** [comment]
Thank you for your feedback, it works.
You can close the case.

**Comment by jghaanstra** [comment]
Thanx for the donation, much appreciated.
