### ISSUE TITLE
Support for Xiaomi vacuum E12 mop mode

### ISSUE THREAD

**Issue by TVAVAE** [jghaanstra/com.xiaomi-miio#236]
How can we easily try to support the E12 vacuum? (xiaomi.vacuum.b112gl). What steps you standard take to support?

**Comment by TVAVAE** [comment]
Found code here: https://github.com/al-one/hass-xiaomi-miot/blob/master/custom_components/xiaomi_miot/core/miot_local_devices.py

Not sure if usefull?

**Comment by TVAVAE** [comment]
Some cool info here about the id's! https://home.miot-spec.com/spec?type=urn:miot-spec-v2:device:vacuum:0000A006:xiaomi-b112gl:1

**Comment by jghaanstra** [comment]
I'll see what I can do.

**Comment by jghaanstra** [comment]
Please test release 3.2.15 which is pending approval by Athom in the app store.

https://homey.app/a/com.xiaomi-miio/test/

https://github.com/jghaanstra/com.xiaomi-miio/wiki/Supported-Devices

**Comment by TVAVAE** [comment]
Looks great at first sight! Thanks :).

Will test further and keep you posted!

**Comment by TVAVAE** [comment]
What I see is that our model van also mop, it doesnt yet look supported, or is it "vlek schoonmaken"?

**Comment by jghaanstra** [comment]
Not supported, I'll might add that with a future release.

**Comment by jghaanstra** [comment]
Please test release 3.2.16 which is pending approval by Athom in the app store.

https://homey.app/a/com.xiaomi-miio/test/

https://github.com/jghaanstra/com.xiaomi-miio/wiki/Supported-Devices

**Comment by TVAVAE** [comment]
> Please test release 3.2.16 which is pending approval by Athom in the app store.
> 
> https://homey.app/a/com.xiaomi-miio/test/
> 
> https://github.com/jghaanstra/com.xiaomi-miio/wiki/Supported-Devices

Cool! Testing! Looks good at first sight!

**Comment by jghaanstra** [comment]
I'm closing this for now. If there is something you can post back here.
