### ISSUE TITLE
Homey Roborock Q8 Max 

### ISSUE THREAD

**Issue by SimonKai22** [jghaanstra/com.xiaomi-miio#237]
I would be very grateful for the integration of Roborock Q8 Max.
roborock.vacuum.a73

What other information do you need?

I am grateful for support.

**Comment by SimonKai22** [comment]
Unfortunately, I don't know my way around that well. What does next release mean? Can I support you?
How to know when you have found a solution? I am very grateful to you.

**Comment by jghaanstra** [comment]
It means support will be added with the next version. I'll post back here when it's being released and can be tested.

You can support me through PayPal: http://paypal.me/jghaanstra

**Comment by jghaanstra** [comment]
Please test release 3.2.16 which is pending approval by Athom in the app store.

https://homey.app/a/com.xiaomi-miio/test/

https://github.com/jghaanstra/com.xiaomi-miio/wiki/Supported-Devices

**Comment by SimonKai22** [comment]
unfortunately it did not work for me. In the list is also only the Q8 and not the Q8 max. 
with me also the IP addresses do not fit. in the Toll he has the address 192.168.8.1 on in my fritzbox 192.168.178.76. I had assigned this statically on the Fritzbox.  
![grafik](https://github.com/jghaanstra/com.xiaomi-miio/assets/145959476/5f48e664-05f7-4ee3-8b93-206ae01fcffd)
![grafik](https://github.com/jghaanstra/com.xiaomi-miio/assets/145959476/3eb7aee1-a5dd-40b4-9dd5-7895a5df6372)
![grafik](https://github.com/jghaanstra/com.xiaomi-miio/assets/145959476/c6b6b7a8-279e-497c-a21b-575c3c5daaf6)

Am I doing something wrong? 
![grafik](https://github.com/jghaanstra/com.xiaomi-miio/assets/145959476/955047a2-2828-4bf6-9918-4e8ec7390920)

**Comment by SimonKai22** [comment]
I have reset the device again. Now the IP addresses match, but I get this message.
Am I making a mistake?
![IMG_2140](https://github.com/jghaanstra/com.xiaomi-miio/assets/145959476/fc2da4c4-e89b-45e8-afce-c26928de9b9e)

**Comment by jghaanstra** [comment]
Looks like something is wrong with your network. Homey is not able to reach the IP address. Are they in the same LAN? This is unrelated to support of this device though. I'm closing this issue. If you fix your networking issues and have the device connected but it doesnt work as expected just post back here.

**Comment by SimonKai22** [comment]
Short update:After a reboot of my Homey it seems to work.I will test it more extensively the functions and then gladly give feedback if this is desired.Am 28.09.2023 um 22:42 schrieb Jelger Haanstra ***@***.***>:﻿
Looks like something is wrong with your network. Homey is not able to reach the IP address. Are they in the same LAN? This is unrelated to support of this device though. I'm closing this issue. If you fix your networking issues and have the device connected but it doesnt work as expected just post back here.

**Comment by SimonKai22** [comment]
I have tested it extensively today. It works very well. Finding out the room ID is a bit strange. But it works.

Thanks a lot
