### ISSUE TITLE
Support Roborock Q5 Pro - Homey

### ISSUE THREAD

**Issue by mbrocke123** [jghaanstra/com.xiaomi-miio#240]
I would be very happy for the integration of the new Roborock Q5 Pro.
 
Do you need more informations? Thank you so much.

**Comment by jghaanstra** [comment]
Read this https://github.com/jghaanstra/com.xiaomi-miio/wiki/Adding-new-devices

**Comment by mbrocke123** [comment]
I now have it:

roborock.vacuum.a72

Thanks

**Comment by jghaanstra** [comment]
Please test release 3.2.17 which adds support for this device. The release is pending approval by Athom in the app store but you can test it through the test channel

https://homey.app/a/com.xiaomi-miio/test/

**Comment by mbrocke123** [comment]
It works really good. Thank you. Great work.
