### ISSUE TITLE
Support for Xiaomi Air Purifier 4

### ISSUE THREAD

**Issue by fmel8** [jghaanstra/com.xiaomi-miio#241]
Hi,

I just added the app and tried to add my Xiaomi devices. For the air purifier, I used the Advanced Mi Air Purifier MIoT (WIFI).
Everything seems to be working except the On/Off and the Enable Ions. The last one is not really usefull but the first is mandatory for flows.
Are there any known issues for this device ?

device info: zhimi-airp-mb5-mibtCE7B
diag report: 00c59d58-3e73-4a10-8939-a92bf1df580d

**Comment by jghaanstra** [comment]
It's a bug, will be fixed with the next release.

**Comment by jghaanstra** [comment]
Please test release 3.2.17 which should contain a fix. The release is pending approval by Athom in the app store but you can test it through the test channel

https://homey.app/a/com.xiaomi-miio/test/

**Comment by fmel8** [comment]
Hello,

I just tested and it works fine!
Thank you for your support.

Other things are missing/not working but It's no big deal.
