### ISSUE TITLE
Smartmi Smart Convector Heater 1S

### ISSUE THREAD

**Issue by b4dad** [jghaanstra/com.xiaomi-miio#244]
it would be awesome if we could get this heater added to the app

Smartmi Smart Convector Heater 1S
zhimi.heater.zb1a
sorry cant find the MIoT spec

Have tried many other drivers, nothing functions

### Supply the device details
* **Name:** << The name of the device >>
* **Model ID:** << brand.type.id, for instance zhimi.airpurifier.mc1, can also be found using token extraction tool (see wiki) >>
* **MIoT spec:** << find the link to the specs of this device on this website: https://home.miot-spec.com/ >>

**Comment by jghaanstra** [comment]
https://home.miot-spec.com/spec/zhimi.heater.zb1a

**Comment by b4dad** [comment]
Nice one, as I’m a little new, what happens next in terms of adding it to the app?

**Comment by jghaanstra** [comment]
You wait until I find the time and motivation to look into it. I'll let you know here when it's included in a new version of the app and you can test it.

**Comment by jghaanstra** [comment]
Support has been added with release 3.2.18 which is currently pending Athom's approval in the app store. You can test it by installing the test version.

https://homey.app/a/com.xiaomi-miio/test/

You need to use the driver named Smart Space/Fan Heater MIoT (WiFi)

You can show your appreciation [here](http://paypal.me/jghaanstra).

**Comment by jghaanstra** [comment]
Closed due to lack of response.
