### ISSUE TITLE
Problems connecting Smartmi Humidifier v2

### ISSUE THREAD

**Issue by pjgrue** [jghaanstra/com.xiaomi-miio#245]
Have a Smartmi Evaporative Humidifier v2 that has worked fine with Homey until this summer. When connecting the humidifier again this autumn it works for some seconds and then looses connection for a while before it connects again for some seconds. I have tried to remove and reconnect the humidifier, read out the token again and connect. At last i tried using the Humidifier Pro device. This works so I can read status and parameters on the device, but give error when trying to control the device.

**Comment by jghaanstra** [comment]
Send a diagnostic report

**Comment by pjgrue** [comment]
6702c1f1-5ce4-43c3-81a7-17cd3db9f37c

**Comment by jghaanstra** [comment]
Repair the device with the Smartmi Humidifier v1/v2 driver. Reboot Homey and let it run for 5 minutes. Test it and if you experience issues send me another report.

**Comment by pjgrue** [comment]
Looks like it can read all parametere from the device, but not control on/off. 
Report # 473d24be-bd75-4de9-b1f8-73ba8a45f658
![Screenshot_20231021_131136_Homey](https://github.com/jghaanstra/com.xiaomi-miio/assets/136737630/8811d1f8-9ad3-49d9-9ec6-deb7763ed5f7)

**Comment by pjgrue** [comment]
Looks like the problem is fixed in the 3.2.19 release. Thank you.
