### ISSUE TITLE
Feature Request: Change Display Brightness via Then Card

### ISSUE THREAD

**Issue by thomaswitt** [jghaanstra/com.xiaomi-miio#247]
The Display Brightness is available and changable via Display Settings, but not automatically (e.g. turn off the display when you go to bed).

Therefore: I'd like to be able to change the display brightness via a "Then..." card.

**Comment by jghaanstra** [comment]
This added with release 3.2.19 which is currently pending approval in the app store. Please test it.

https://homey.app/a/com.xiaomi-miio/test/

**Comment by thomaswitt** [comment]
Just texted, unfortunately it doesn't do anything. Sure it's the right setting? The App offers on/off/dim, the card offers on and off.

In the documentation, I think the correct SIID is 13, but if I understand the code correctly, it's currently 6… maybe that's the problem?

**Comment by jghaanstra** [comment]
Not sure where you got the value 6 but it's not that. https://github.com/jghaanstra/com.xiaomi-miio/blob/fd18ff0fccc30c707e7ffba08f00dea346d112c4/drivers/airpurifier_zhimi_advanced_miot/device.js#L246

I do see the min and max value are inverted. https://github.com/jghaanstra/com.xiaomi-miio/blob/fd18ff0fccc30c707e7ffba08f00dea346d112c4/drivers/airpurifier_zhimi_advanced_miot/device.js#L249

But this should still result in some change in brightness where turning it on actually turns it off and visa versa. I'll fix that with the next release. Other than that there is not much more I can do without having the device,.

**Comment by jghaanstra** [comment]
A possible fix has been published to the test channel and is waiting app store approval. Please test it.

https://homey.app/a/com.xiaomi-miio/test/
