### ISSUE TITLE
Support for Yunmi Kettle 

### ISSUE THREAD

**Issue by c-fevre** [jghaanstra/com.xiaomi-miio#248]
### Device details
* **Name:** Yunmi Kettle v1
* **Model ID:** yunmi.kettle.v1
* **MIoT spec:** https://home.miot-spec.com/spec?type=urn:miot-spec-v2:device:kettle:0000A009:yunmi-v1:1

### Current support
I'm working as a developer and I'm learning the Homey environment, with your help I'll probably be able to find some information or even adapt your app. I have the device at home :)

**Comment by jghaanstra** [comment]
This appears to be a (mainly) Bluetooth device and the docs you linked is lacking any real information. The Xiaomi Mi Home app only integrates WIFi devices but without documentation this can not be done. If I'm mistaken about the connectivity and you do have proper documentation on the MIoT parameters feel free to respond here. I'm closing this for now.
