### ISSUE TITLE
Add support for xiaomi gateway

### ISSUE THREAD

**Issue by mauritsivs** [jghaanstra/com.xiaomi-miio#25]
Please add support for the xiaomi gateway. 
the miio library has support for it. Even though we dont need the zigbee functions of it anymore since homey can do it directly, it still has some nice usable functions, like a speaker that can play alarms or doorbells etc, a light, and a luminance sensor...

**Comment by jghaanstra** [comment]
Looks like the miio library only supports the light capability from the gateway itself. I'll only implement that for now. You could request support for other gateway functions in the miio repo.

**Comment by jghaanstra** [comment]
Actually only the luminance is supported right now. Support for the alarms and light (color and brightness) is not available yet. See this issue for more information: https://github.com/aholstenson/miio/issues/69

**Comment by jghaanstra** [comment]
Fixed with https://github.com/jghaanstra/com.xiaomi-miio/releases/tag/2.6.2
