### ISSUE TITLE
New Device Model: chuangmi.plug.m3

### ISSUE THREAD

**Issue by AndrewFarley** [jghaanstra/com.xiaomi-miio#250]
### Supply the device details
* **Name:** Mi Smart Plug (Wi-Fi) Basic
* **Model ID:** chuangmi.plug.m3
* **DID** (if needed): 128684406
* **MIoT spec:** https://home.miot-spec.com/s/chuangmi.plug.m3

### Current support
* This device is in the supported devices list although, I believe it only has chuangmi.plug.m1 not m3
* This device allows me to connect to it when I specify the IP and token with the m1 driver
* This m1 driver does successfully reads the device's temperature
* HOWEVER, when attempting to turn on or off the device it says `this.miio.setPower is not a function`

I've done a submission of diagnostic data and received an email which said this device is not supported.  The log ID is: `1a8ce7bc-9433-4a7c-8391-0e32ccd9f2df`

### Additional information
I was able to use this device perfectly with the [miiocli](https://github.com/rytilahti/python-miio) utility and I have provided TCP dumps of the successful interactions with my device in an attempt to help you implement/debug/resolve this issue.

#### Status:
```bash
# For showing the status
tcpdump -s 0 -XX -vv host 10.20.31.194 -w status.pcap
miiocli chuangmiplug  --ip 10.20.31.194 --token f9610ca94107629828d486a7cc4d7920 status

# For turning it on
tcpdump -s 0 -XX -vv host 10.20.31.194 -w on.pcap
miiocli chuangmiplug  --ip 10.20.31.194 --token f9610ca94107629828d486a7cc4d7920 on

# For turning it off
tcpdump -s 0 -XX -vv host 10.20.31.194 -w off.pcap
miiocli chuangmiplug  --ip 10.20.31.194 --token f9610ca94107629828d486a7cc4d7920 off
```
[chuangmi.plug.m3_miiocli_functioning.tar.gz](https://github.com/jghaanstra/com.xiaomi-miio/files/13431919/chuangmi.plug.m3_miiocli_functioning.tar.gz)

In these packet captures (in the zip above) I have three captures the traffic functionally able to control and talk to this device each of which were ran in separate terminals so they can run in parallel.  And no, I don't really care that I've shared the IP or token here, I will reset them after this is working natively in Homey.

If you have any additional questions, or need additional data please ask.  I'd love to be able to natively use this in Homey.

Thanks

**Comment by jghaanstra** [comment]
Thanx for the elaborate response. This device model is not in the [supported devices list](https://github.com/jghaanstra/com.xiaomi-miio/wiki/Supported-Devices#plugs-and-switches) yet. I'll add support with the next release.

**Comment by jghaanstra** [comment]
This model has been added in the release which is published to the test channel and is waiting app store approval. Please test it.

https://homey.app/a/com.xiaomi-miio/test/
