### ISSUE TITLE
New Device Support s7 max ultra (roborock.vacuum.a65)

### ISSUE THREAD

**Issue by hgarc014** [jghaanstra/com.xiaomi-miio#251]
> As there is no official API and Xiaomi does not support third-party integration, being able to add a device to the Homey app depends on an existing integration, online documentation or donating the device to the developer. If neither of these can be fulfilled then integration is not possible.

### Supply the device details
* **Name:** Roborock S7 Max Ultra Robot Vacuum with RockDock
* **Model ID:** roborock.vacuum.a65
* **MIoT spec:** [roborock.vaccum.a65](https://home.miot-spec.com/spec/roborock.vacuum.a65)
(note there does appear to be 2 other versions, but they don't match my exact [version on the website](https://home.miot-spec.com/s/roborock.vacuum.a65))

### Current support

I have been using the following model id for the s7 ([roborock.vacuum.a27](https://github.com/jghaanstra/com.xiaomi-miio/wiki/Supported-Devices#:~:text=roborock.-,vacuum,-.a27)), which has some functionality, but fails to run the vaccum. It appears to correctly detect vaccum state, battery, and sensors as they update when i run it through the mi home app. Just unable to actually change vaccum states through homey hub

### Additional information

it appears the method being used to attempt to change states doesn't work. 

![image](https://github.com/jghaanstra/com.xiaomi-miio/assets/5572299/acdde80e-11b5-423e-8c59-ba059865f397)

**Comment by hgarc014** [comment]
@jghaanstra I'm sure you have tons of other things, but I was wondering if you have a regular release cadence or a vague idea when i could expect this functionality (a few months, a few weeks, etc).

**Comment by jghaanstra** [comment]
Few weeks tops.

**Comment by jghaanstra** [comment]
This model has been added to the app version which has been published to the test channel and is waiting app store approval. Please test it.

https://homey.app/a/com.xiaomi-miio/test/

**Comment by hgarc014** [comment]
Thank you! Yes everything looks to be working now
