### ISSUE TITLE
Add more flow cards(set hunidity%, turn on/off light/sound etc.) in Homey for Smart Mi Antibacterial Humidifier JSQ5

### ISSUE THREAD

**Issue by JGH88** [jghaanstra/com.xiaomi-miio#252]

**Comment by jghaanstra** [comment]
Please be specific, no description and using words as etc. will not help you get what you want.

**Comment by jghaanstra** [comment]
* You can turn on/off the light and sound from the device settings in Homey.
* You can set the humidity using the dim capability to the predefined values [30, 40, 50, 60, 70, 80]. What more are you expecting?

**Comment by JGH88** [comment]
Thank you for your reply. I have misunderstood something. My request is to be able to disable notification sounds(alarm) and light. When the device turns on after power has been disconnected, the light and sound is activated again. Is it possible to create a flowcard which does this? Flowcard - “Turn off LED indicator light”Flowcard - “Turn off notification sound(alarm)”I just tested and realised that the translation to the Danish Homey is incorrect. The translation says adjust/dim/brighten light to xx%. What happens when I adjust/dim/brighten is I that it changes the humidity. So this works and I can actually set a specific % between 40 and 70. I thought this was changing the brightness of the indication light. Den 11. dec. 2023 kl. 19.35 skrev Jelger Haanstra ***@***.***>:﻿

You can turn on/off the light and sound from the device settings in Homey.
You can set the humidity using the dim capability to the predefined values [30, 40, 50, 60, 70, 80]. What more are you expecting?

**Comment by jghaanstra** [comment]
I'll see what I can do when I find some time and motivation.

**Comment by JGH88** [comment]
Thank you. I would appreciate it.
I have sent you a donation to show my appreciation for the current work you
have done.

man. 11. dec. 2023 kl. 22.11 skrev Jelger Haanstra ***@***.***

**Comment by jghaanstra** [comment]
Thanx, that helps a bit ... ;-)

I added the notification sound and led light cards yesterday. Unfortunately due to they way the target humidity is implemented I can not change the action card translation.

**Comment by jghaanstra** [comment]
The toggle notification sound and LED light has been added in the app version is is now published to the test channel and is waiting app store approval. Please test it.

https://homey.app/a/com.xiaomi-miio/test/

**Comment by JGH88** [comment]
Thank you :-)
I just tested it but it doesn't work.
1. "Set notification sound off" runs, but it doesnt turn off the sound.
2. "Set LED off" fails with following error " Cannot read properties of
undefined (reading 'light')"
3. "Turn off humidifier" doesn´t turn it off now.

Den fre. 15. dec. 2023 kl. 14.36 skrev Jelger Haanstra <
***@***.***>:

**Comment by jghaanstra** [comment]
1. and 2. are going to be trail and error without having the actual device to test with. I will change some things in the next release but I'm not sure it will fix it.

3. Should be fixed with the next release.

**Comment by JGH88** [comment]
Ok.Just let me know and I will test it immediately. :-)BR JasonDen 17. dec. 2023 kl. 18.19 skrev Jelger Haanstra ***@***.***>:﻿


and 2. are going to be trail and error without having the actual device to test with. I will change some things in the next release but I'm not sure it will fix it.


Should be fixed with the next release.

**Comment by jghaanstra** [comment]
Possible fixes are available in release 3.2.21 which is not pending approval in the app store. Please test it.

https://homey.app/a/com.xiaomi-miio/test/

**Comment by JGH88** [comment]
Hi JghaanstraSound and light works. Only thing that isn’t working anymore is the set humidity %(“light”) as a flow card?Best regards JasonDen 17. jan. 2024 kl. 16.40 skrev Jelger Haanstra ***@***.***>:﻿
Possible fixes are available in release 3.2.21 which is not pending approval in the app store. Please test it.
https://homey.app/a/com.xiaomi-miio/test/

**Comment by jghaanstra** [comment]
Please open up a new issue with more information. I'm closing this issue.
