### ISSUE TITLE
Add more card for rockrobo.vacuum.v1

### ISSUE THREAD

**Issue by fmel8** [jghaanstra/com.xiaomi-miio#254]
Hi,

**Current device:** rockrobo.vacuum.v1

**Request:** Add cards for the actions Pause/Resume 

**Use case:** I'm trying to do a pause/resume flow so in case you need the room to be quiet (phone call or something..) you can quickly pause and start the vacuum. I tried using the cards Activate/Deactivate and Start, Stop but It doesn't pause. Instead It stop the current cleaning session and start from the beginning.

**Comment by jghaanstra** [comment]
Please supply the command which need to be called. Otherwise I wont be able to add it unless you donate this device.

**Comment by jghaanstra** [comment]
A pause action card has been added in the app version which has been published to the test channel and is waiting app store approval. Please test it.

https://homey.app/a/com.xiaomi-miio/test/

**Comment by fmel8** [comment]
Thank you for the quick implementation !
I’m not at home this week-end but I will try to give a feedback asap.

Le 15 déc. 2023 à 14:37, Jelger Haanstra ***@***.***> a écrit :

﻿

A pause action card has been added in the app version which has been published to the test channel and is waiting app store approval. Please test it.

https://homey.app/a/com.xiaomi-miio/test/

**Comment by fmel8** [comment]
Hi,

I tested the Pause card and It works well!
But I don't know how to implement it in my flow. I try to check the vacuum state using the card "is activated" and if yes pause if no resume the cleanup.
It seems like when the vacuum is paused the state stays in activated the card It will never resume the cleanup.

**Comment by jghaanstra** [comment]
The pause state is currently mapped to the "cleaning" state of the vacuumcleaner_state capability of Homey (which does not have a paused state). I'll change this and map it to the stopped state.

**Comment by jghaanstra** [comment]
The pause state is mapped differently in release 3.2.21 which is now pending approval in the app store. Please test it.

https://homey.app/a/com.xiaomi-miio/test/

**Comment by fmel8** [comment]
Hi,

I tested with both versions 3.2.20 and 3.2.21; and the flow worked with both versions ^^'
