### ISSUE TITLE
Add model roborock.vacuum.a51 (Roborock S8)

### ISSUE THREAD

**Issue by Easton8805** [jghaanstra/com.xiaomi-miio#255]
Hello,

could you please add a new model to Xiaomi Mi Home App?
Particularly Roborock S8
model: roborock.vacuum.a51

Im here new and not sure if I provided required data. If you need something more, please, let me know.

Thanks in advance.

**Comment by jghaanstra** [comment]
Have you actually tried pairing this device, it's already supported.

https://github.com/jghaanstra/com.xiaomi-miio/wiki/Supported-Devices

**Comment by Easton8805** [comment]
I selected device ADVANCED ROBOROCK VACUUM CLEANER, 
filled IP address, Token, and set polling frequency to  60 seconds.

If I Test connection, it returns COULD NOT CONNECT TO DEVICE, HANDSHAKE TIME OUT.
Could you please advice where I am wrong, then?

**Comment by jghaanstra** [comment]
You are using an incorrect token. Try again and reset the device if you keep having this issue and you are sure your details (IP and token) are correct.
