### ISSUE TITLE
New Device Model: Mi Smart Plug (WiFi) EU

### ISSUE THREAD

**Issue by Michelvl92** [jghaanstra/com.xiaomi-miio#256]
### Supply the device details
* **Name:** Mi Smart Plug (WiFi) EU
* **Model ID:** chuangmi.plug.hmi206
* **MIoT spec:** [Link to Mi Smart Plug (WiFi) EU on miot](https://home.miot-spec.com/s/chuangmi.plug.hmi206)

### Current support
I have tested the device by adding the device as `chuangmi.plug.m1` or `chuangmi.plug.v1` or `chuangmi.plug.v3`, it is possible to add the device, but then putting it on/off then I get the message `this.miio.setPower` is not a function.

**Comment by jghaanstra** [comment]
This model has been added in release 3.2.21 which is now pending approval in the app store. Please test it.

https://homey.app/a/com.xiaomi-miio/test/

**Comment by jghaanstra** [comment]
No feedback, closing issue.
