### ISSUE TITLE
Add Flowcard  swepping, moppping or booth as option for dreame.vacuum.r2228o

### ISSUE THREAD

**Issue by gine78** [jghaanstra/com.xiaomi-miio#257]
Hello,

is it possible to get flowcard options for only swepping (without mopping)?

### Supply the device details
* **Name:** L10S Ultra
* **Model ID:** dreame.vacuum.r2228o
* **MIoT spec:** https://home.miot-spec.com/spec/dreame.vacuum.r2228o

### Current support
 missing functionality 

### Additional information
in the mobile app it is possible that the vacuum is only swepping without mopping. is it possible to get the function in the homey app?

**Comment by jghaanstra** [comment]
I'll add better support for this device with the next release (will require re-pairing when the new release is live).  This will add a action card for setting the mop intensity.

But as far as I can tell from the documentation there is no option for setting the cleaning mode on Dreame vacuumcleaners (as is with Roborock cleaners). So I cant add this flow card.

**Comment by jghaanstra** [comment]
Please test the support for this device model by re-pairing the device in release 3.2.21 which is now pending approval in the app store. Please test it.

https://homey.app/a/com.xiaomi-miio/test/

**Comment by jghaanstra** [comment]
No feedback, closing issue.
