### ISSUE TITLE
New Device Model Xiaomi Robot Vacuum X10 (dreame.vacuum.r2209)

### ISSUE THREAD

**Issue by PatriceVolkmer** [jghaanstra/com.xiaomi-miio#258]
### Supply the device details
* **Name:** Xiaomi Robot Vacuum X10
* **Model ID:** dreame.vacuum.r2209
* **MIoT spec:** https://home.miot-spec.com/s/dreame.vacuum.r2209

### Current support
The token can be extract but the device (via the windows app by https://github.com/Maxmudjon).
The problem is that with the token and ip adresse that the Xiaomi Robot Vacuum X10 can not add to the homey pro system.

I use the app "Xiaomi Mi Home -Control Xiaomi Mi Home devices using Homey by Jelger Haanstra" and get the following by all versions of vacuum robots.

![image](https://github.com/jghaanstra/com.xiaomi-miio/assets/91467028/2d122fa2-9de8-4177-902b-acb514d1230f)

**Comment by jghaanstra** [comment]
This device is already supported and the error you get is because you are using the wrong token. Sometimes you need to reset the device to get a fresh working token. If you need support, use the support forum: https://community.homey.app/t/app-pro-xiaomi-mi-home-app/118

**Comment by PatriceVolkmer** [comment]
hey Jelger,

I do a reset and get a new token but the Message still is the same and it does not work. 
I try several version (2nd Screenshot).

Any ideas?

Kind Regards,
Patrice

![image](https://github.com/jghaanstra/com.xiaomi-miio/assets/91467028/77caeeea-02fa-4d41-b0d0-be6383653850)
![image](https://github.com/jghaanstra/com.xiaomi-miio/assets/91467028/dfae41ac-0457-4117-870e-1f5c68360162)

**Comment by jghaanstra** [comment]
I was mistaken, this model isnt supported yet. I will add it with the next release. I do doubt if this is the cause of this error though as that is usually a token (or a networking) error. But it's best to wait until I have implemented and test it again on the new release.

**Comment by PatriceVolkmer** [comment]
Ok perfect. I will test the next release and will provide active feedback

**Comment by jghaanstra** [comment]
Support for this device model has been added in release 3.2.21 which is now pending approval in the app store. Please test it.

https://homey.app/a/com.xiaomi-miio/test/

**Comment by PatriceVolkmer** [comment]
hey Jelger, I use for the r2209 this icon but get the following message again:
![image](https://github.com/jghaanstra/com.xiaomi-miio/assets/91467028/be054108-d5de-46e7-a2ee-68e034a70aa8)

![image](https://github.com/jghaanstra/com.xiaomi-miio/assets/91467028/fe3a8016-38ca-4da1-9580-3bf8ccee4171)

Any idea?

**Comment by jghaanstra** [comment]
> Any idea?

The error "Could not connect to device, handshake timeout" usually means you are using an incorrect token or there are networking issues. Try resetting the device and start from scratch. There is nothing more I can do for you

**Comment by PatriceVolkmer** [comment]
i will check that. Which asset type is the correct one?
![image](https://github.com/jghaanstra/com.xiaomi-miio/assets/91467028/3ee90225-ed32-466e-9af2-d55682b5666f)

**Comment by jghaanstra** [comment]
The first one. See https://github.com/jghaanstra/com.xiaomi-miio/wiki/Supported-Devices.

**Comment by PatriceVolkmer** [comment]
@jghaanstra : unfortunatelly it does not work. I reset the device and got a new token but still the same error. when i ping the dreame robot a get an answer. how can I troubleshoot the problem?

**Comment by jghaanstra** [comment]
> how can I troubleshoot the problem?

The error indicates there is something wrong with the network traffic between Homey and the device. That's either the token or something in your network config (not using correct Ip adddres, the devices are not in the same LAN, etc. etc.). You should look into that.
