### ISSUE TITLE
Add support for xiaomi.airp.cpa4

### ISSUE THREAD

**Issue by Ampler92** [jghaanstra/com.xiaomi-miio#260]
> As there is no official API and Xiaomi does not support third-party integration, being able to add a device to the Homey app depends on an existing integration, online documentation or donating the device to the developer. If neither of these can be fulfilled then integration is not possible.

### Supply the device details
* **Name:** Xiaomi Smart Air Purifier 4 Compact
* **Model ID:** xiaomi.airp.cpa4
* **MIoT spec:** https://home.miot-spec.com/spec/xiaomi.airp.cpa4

### Current support
yes tested with every driver, does not work with any of them unfortunately, advanced miot gives 'cannot read undefined data'

### Additional information

Many Thanks for adding the support for this device!!

**Comment by jghaanstra** [comment]
This has been added with release 3.2.22 which is now pending approval in the app store. You can already test it using the test version of the app. I'm closing this issue. If you see unexpected results please report back here.

https://homey.app/a/com.xiaomi-miio/test/
