### ISSUE TITLE
Add support dreame.vacuum.p2114a

### ISSUE THREAD

**Issue by LordSata** [jghaanstra/com.xiaomi-miio#262]
> As there is no official API and Xiaomi does not support third-party integration, being able to add a device to the Homey app depends on an existing integration, online documentation or donating the device to the developer. If neither of these can be fulfilled then integration is not possible.

### Supply the device details
* **Name:** Xiaomi Robot Vacuum X10+
* **Model ID:** dreame.vacuum.p2114a
* **MIoT spec:** https://home.miot-spec.com/spec/dreame.vacuum.p2114a
* 
### Current support
yes tested with every driver, does not work with any of them unfortunately, advanced miot gives 'cannot read undefined data'

### Additional information
Many Thanks for adding the support for this device!!

**Comment by jghaanstra** [comment]
This has been added with release 3.2.22 which is now pending approval in the app store. You can already test it using the test version of the app. I'm closing this issue. If you see unexpected results please report back here.

https://homey.app/a/com.xiaomi-miio/test/
