### ISSUE TITLE
Add support for careli.fryer.maf10a

### ISSUE THREAD

**Issue by rgreco87** [jghaanstra/com.xiaomi-miio#264]
> As there is no official API and Xiaomi does not support third-party integration, being able to add a device to the Homey app depends on an existing integration, online documentation or donating the device to the developer. If neither of these can be fulfilled then integration is not possible.

### Supply the device details
* **Name:** Xiaomi Smart Air Fryer 6.5L
* **Model ID:** careli.fryer.maf10a
* **MIoT spec:** https://home.miot-spec.com/spec/careli.fryer.maf10a

### Current support
Tested with "Air Fryers MIoT (WiFi)", I can add the device but it doesn't work: **Device is unreachable: Cannot read properties of undefined (reading 'toString')**

### Additional information
I wish you could add this model, thank you!

**Comment by jghaanstra** [comment]
I'll see if I can add it with the next release.

**Comment by jghaanstra** [comment]
This has been added with release 3.2.22 which is now pending approval in the app store. You can already test it using the test version of the app. I'm closing this issue. If you see unexpected results please report back here.

https://homey.app/a/com.xiaomi-miio/test/
