### ISSUE TITLE
Xiaomi lightstrip

### ISSUE THREAD

**Issue by Droop49** [jghaanstra/com.xiaomi-miio#266]
Hi

Can you add support for Xiaomi Lightstrip?
philips.light.strip5

I tried all bulb and lights drivers but none is working. 
Best regards

### Supply the device details
* **Name:** << The name of the device >>
* **Model ID:** << brand.type.id, for instance zhimi.airpurifier.mc1, can also be found using token extraction tool (see wiki) >>
* **MIoT spec:** << find the link to the specs of this device on this website: https://home.miot-spec.com/ >>

### Current support
<< Have you tested an existing driver based on the currently supported devices list (see wiki) and what was the result / error / missing functionality? >>

### Additional information
<< Add any other context or screenshots about the feature request here. >>

**Comment by jghaanstra** [comment]
Added with release 3.2.23 which is pending approval in the app store. You can already test it using the version in the test channel. Please test and supply feedback.

https://homey.app/a/com.xiaomi-miio/test/

**Comment by jghaanstra** [comment]
No response, closing issue.
