### ISSUE TITLE
Add support for dreame.vacuum.r2232c (Dreame L10s Prime)

### ISSUE THREAD

**Issue by mbrocke123** [jghaanstra/com.xiaomi-miio#267]
Hello,

could you please add a new model to Xiaomi Mi Home App?
Dreame L10s Prime
model: dreame.vacuum.r2232c

Thanks in advance.

**Comment by jghaanstra** [comment]
This has been been added with release `3.2.24`. Please test it.

**Comment by jghaanstra** [comment]
No response, closing.
