### ISSUE TITLE
Support for Mijia Smart Pet Food Feeder 2

### ISSUE THREAD

**Issue by harryoffer** [jghaanstra/com.xiaomi-miio#268]
### Supply the device details
* **Name:**      -       Mijia Smart Pet Food Feeder 2
* **Model ID:**      -       xiaomi.feeder.pi2001
* **MIoT spec:**      -    https://home.miot-spec.com/spec/xiaomi.feeder.pi2001

### Current support
Shows as unknown model - Device is unreachable: Cannot read properties of undefined (reading 'get_properties')
Occasionally, it pops in with options like Normal/Low/Empty, but only for a second then goes back to unknown

---- STOP EDITING HERE----
### Donation
I enjoy creating apps for Homey and try to support them as best as I can. If you enjoy using my apps a [donation](https://www.paypal.me/jghaanstra) in return for the time I put into this is much appreciated.

**Comment by jghaanstra** [comment]
This has been been added with release `3.2.24`. Please test it.

**Comment by harryoffer** [comment]
thanks, updated to 3.2.24
was able to add the feeder, however, device still shows as unavailable.
Device is unreachable: measure_battery is not defined
![image](https://github.com/jghaanstra/com.xiaomi-miio/assets/25121690/01694fd8-ca89-4fb7-ac07-98195d280d12)

it shows the above for a minute and then for 5 seconds shows this image
![image](https://github.com/jghaanstra/com.xiaomi-miio/assets/25121690/109ad60b-aea7-49a6-9c62-26a7fd0b66d2)
and dthen clicking across to the battery icon shows this
![image](https://github.com/jghaanstra/com.xiaomi-miio/assets/25121690/2858de99-9e45-41ac-b8ba-bd049ebc54c9)

The intermittent polling thing was there previously, the battery error is new.

Settings for the device shows no errors
![image](https://github.com/jghaanstra/com.xiaomi-miio/assets/25121690/a6ab1e8d-9aaf-4954-bead-d40bc434eb37)

**Comment by jghaanstra** [comment]
Will be fixed with the next release.

**Comment by jghaanstra** [comment]
I added a fix with release 3.2.25, please test and confirm it works or not. The app is currently pending approval so you will need to use the test version until it is approved.

https://homey.app/a/com.xiaomi-miio/test/

**Comment by jghaanstra** [comment]
Closed due to lack of response.
