### ISSUE TITLE
connection to roborock S8

### ISSUE THREAD

**Issue by eelko123** [jghaanstra/com.xiaomi-miio#270]
Is integration to Roborock S8 possible?

Unfortunatly the link does not appear in your list.

name >> Name of the device: roborock S8
model >> Model id: roborock.vacuum.a51
spec >> Roborock S8 does not appear to be on the website provided

### Current support
Yes >> I used token and IP address, fault provided is "could not find that PairSession" or "could not connect to device, haandshake timeout", when i manually type over the token

### Additional information
Hope you can provide a way to link Roborock S8 to homey, thank you for all the support!

---- STOP EDITING HERE----
### Donation
I enjoy creating apps for Homey and try to support them as best as I can. If you enjoy using my apps a [donation](https://www.paypal.me/jghaanstra) in return for the time I put into this is much appreciated.

**Comment by jghaanstra** [comment]
This device is already support. The error you get is related the switching to another app during pairing. Use the WebUI for pairing or have the token already in the clipboard.

I'll add this device to supported under the documentation. If you experience issues use the support topic on the forum.
