### ISSUE TITLE
Support for Dreame L10s Pro Ultra

### ISSUE THREAD

**Issue by pcherkash** [jghaanstra/com.xiaomi-miio#271]
Hello,

Could you please add a new model to Xiaomi Mi Home App?
Dreame L10s Pro Ultra
model: dreame.vacuum.r2338a

**Comment by jghaanstra** [comment]
> Could you please add a new model to Xiaomi Mi Home App?

At the moment I cant, there is no specification available for this device at https://home.miot-spec.com/spec/dreame.vacuum.r2338a . I'll assign the parameters of a previous model but if something changed that wont work as well. You should keep track of this link and notify me if the specs are added there.

**Comment by jghaanstra** [comment]
I added possible support with release 3.2.25, please test and confirm it works or not. The app is currently pending approval so you will need to use the test version until it is approved.

https://homey.app/a/com.xiaomi-miio/test/

**Comment by jghaanstra** [comment]
Closed due to lack of response.
