### ISSUE TITLE
Support for Xiaomi Lamp 1S (new)

### ISSUE THREAD

**Issue by pcherkash** [jghaanstra/com.xiaomi-miio#272]
Hello,

Could you please add a new model to Xiaomi Mi Home App?
Xiaomi Lamp 1S
model: yeelink.light.lamp27 (https://home.miot-spec.com/spec/yeelink.light.lamp27)

**Comment by jghaanstra** [comment]
This app doesnt support Yeeligghts. Check the Yeelight LAN or Yeelight app in the app store.
