### ISSUE TITLE
Support for Xiaomi Smart Evaporative Cooling Fan

### ISSUE THREAD

**Issue by tronstone** [jghaanstra/com.xiaomi-miio#274]
Hello, once again I would like to thank the developer for such a tremendous amount of work done to integrate Mi devices. I would like to request the addition of a new device.

### Device details
* **Name:** Xiaomi Smart Evaporative Cooling Fan
* **Model ID:** dmaker.fan.p44
* **MIoT spec:** https://home.miot-spec.com/spec/dmaker.fan.p44
### Current support
**Error, device not supported**

### Donation
I enjoy creating apps for Homey and try to support them as best as I can. If you enjoy using my apps a [donation](https://www.paypal.me/jghaanstra) in return for the time I put into this is much appreciated.

**Comment by tronstone** [comment]
@jghaanstra do you need the device for this? I can provide access for you

**Comment by jghaanstra** [comment]
No, it will be added with the next release.

**Comment by jghaanstra** [comment]
Add with 3.2.26 which is currently pending approval. Please test by installing the test version or wait until it's approved.

https://homey.app/a/com.xiaomi-miio/test/

**Comment by tronstone** [comment]
Thanks, friend for the quick reponse on your part!

@jghaanstra I've already added my device and tested it, met a lot of bugs.

Tried to add in different ways, only the Advanced Mi Smart Standing Fan MIoT (WiFi) connection option works.

From the bugs:

- First the on/off button works, but then it gives the error: invalid enum capability (fan_dmaker_mode) value: 3. Expected: 0,1, after that the device is no longer available
- Other functions either don't work at all or work incorrectly (for example wind strength shows either 100% or 400% although there are actually 4 levels: 1, 2, 3 and 4).

- Only the functions from the **advanced settings** work correctly.

P.s If you want to debug problems I can provide access for you

**Comment by jghaanstra** [comment]
Please send a diagnostic report from the app settings.

**Comment by tronstone** [comment]
@jghaanstra 4ce6d06c-8288-40ac-b014-b1daf636e6fb

**Comment by jghaanstra** [comment]
The log you send me is useless. Please remove the device, restart the app (or Homey), pair the device with the `Advanced Mi Smart Standing Fan MIoT (WiFi)` driver. Wait 2 minutes. Toggle it on and off, wait two minutes and then send the log again.

I'll fix the error with `error: invalid enum capability (fan_dmaker_mode) value: 3. Expected: 0,1` with the next release. That will prevent the device from going offline. I dont know why the wind strength shows as percentage, perhaps the documentation is wrong. You mention other functions not working at all, please be specific.

**Comment by tronstone** [comment]
New log: aad5dad5-e547-4960-ad6f-99651376b404

Functions supported by my fan:
1. Turn on/off
2. Wind strength - 4 levels
3. Modes - Direct, Natural, Sleep, Cool
4. Automatic horizontal oscillation on/off
5. Advanced options

Functions that not working: 
1. Not working
2. 100% and 400%, not levels
3. Only two modes, I can't check it due to error
4. I've seen angles to customize the rotation, but they don't work

**Comment by jghaanstra** [comment]
1. Will be fixed with the next release as mentioned
2. Dont know why these show as a percentage, as mentioned my best guess is the documentation is wrong. I cant fix that.
3. Will be fixed with the next release as mentioned, this is the same problem as #1.
4. There is a on/off switch for oscillation available under the device which should work when #1 is fixed (it probably already works but cant be tested due to the device going offline)

**Comment by jghaanstra** [comment]
Please test release 3.2.29 which is currently pending approval in the app store.

https://homey.app/a/com.xiaomi-miio/test/

**Comment by tronstone** [comment]
@jghaanstra many thanks for add support of this device. I have already tested and all the basic functions work properly. I think the number of features will be sufficient for now. And thanks again :)
