### ISSUE TITLE
Xiaomi Smart Tower Fan (dmaker.fan.p39) / Connection Timeout

### ISSUE THREAD

**Issue by Travelman67** [jghaanstra/com.xiaomi-miio#279]
My 3 Xiaomi Smart Tower Fan (dmaker.fan.p39), worked well during this summer. since update on Homey pro to Xiaomi Mi Home v3.2.31 i got connection issue. Deleted all 3 Fans in Homey and try all Fan models. Adding of the FAN with IP an Token are succesfull. But after some seconds i see a triangle -> Device not available. I tried all so to remove all 3 FAN's in Xiaomi App. then i add the 3 FAN in the Xiaomi App. I got new Token for all 3 FAN's. Then i add all 3 FAN's in the Homey. Same issue. Do i have a important step overseen?

**Comment by jghaanstra** [comment]
It's a bug which will be fixed with the next release.

**Comment by jghaanstra** [comment]
Should be fixed now with the release which is currently in test. 

https://homey.app/a/com.xiaomi-miio/test/
