### ISSUE TITLE
camera

### ISSUE THREAD

**Issue by sorakamid2** [jghaanstra/com.xiaomi-miio#280]
I'm just getting ffffffffffffffffffffffffffffffff when trying to get the token. I'm assuming this doesn't work with cameras, right? Is there another method?
![paint123](https://github.com/user-attachments/assets/defd3f3d-0b4c-4a5c-9a4b-3cdea5032d64)

**Comment by jghaanstra** [comment]
Cameras are not supported. Please use the support forum for these kind of questions. GitHub is for bugs and feature requests.
