### ISSUE TITLE
Adding device Mijia Bedside Lamp 2nd Generation (yeelink.light.bslamp2)

### ISSUE THREAD

**Issue by jon-walton** [jghaanstra/com.xiaomi-miio#283]
### Supply the device details
* **Name:** Mijia Bedside Lamp 2nd Generation
* **Model ID:** yeelink.light.bslamp2
* **MIoT spec:** https://home.miot-spec.com/spec?type=urn:miot-spec-v2:device:light:0000A001:yeelink-bslamp2:2

### Current support
No support

---- STOP EDITING HERE----
### Donation
I enjoy creating apps for Homey and try to support them as best as I can. If you enjoy using my apps a [donation](https://www.paypal.me/jghaanstra) in return for the time I put into this is much appreciated.

**Comment by jghaanstra** [comment]
This is essentially a Yeelight and should be supported by the Yeelight Cloud or Yeelight LAN app. This is a bit of a troublesome device though as LAN control required for this device was disabled at some point. For more info see 

https://forum.yeelight.com/t/topic/22664/1428?page=52

https://github.com/jghaanstra/com.yeelight/issues/11

I'm hesitant to add Yeelights to the Xiaomi app though as it has it's own apps.

**Comment by jon-walton** [comment]
thanks for the update!
