### ISSUE TITLE
 xiaomi YEELIGHT Candela

### ISSUE THREAD

**Issue by meyland** [jghaanstra/com.xiaomi-miio#30]
Hey, 
Just to be sure, would this work?

https://www.aliexpress.com/item/Original-xiaomi-YEELIGHT-mijia-Candela-Smart-Control-led-night-light-Atmosphere-light-for-Mi-home-app/32840140707.html

**Comment by jghaanstra** [comment]
I believe the Candela only uses Bluetooth. This Homey app only works with the WiFi enabled yeelights. So no, it probably won't work.
