### ISSUE TITLE
Problem plugin with Xiaomi Phillips light bulb

### ISSUE THREAD

**Issue by rostov36** [jghaanstra/com.xiaomi-miio#33]
https://youtu.be/CcUnUNQCd-I

Help me please and repair

**Comment by jghaanstra** [comment]
I dont own any Xiaomi Philips light bulbs myself so I can not test what is causing this. Do you know how to run a Homey app from the command line. I can make a special version that will give me more debug logging that will enable me to figure out what is going on.

**Comment by jghaanstra** [comment]
https://github.com/jghaanstra/com.xiaomi-miio/tree/debug

If you run this version through command line it should spit out additional logging which might tell me what is going on.

**Comment by rostov36** [comment]
i install this version.  
module.js:540
throw err;
^

Error: Cannot find module 'miio'
at Function.Module._resolveFilename (module.js:538:15)
at Function.Module._load (module.js:468:25)
at Module.require (module.js:587:17)
at Module.require (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/index.js:1:253)
at require (internal/module.js:11:18)
at Object.<anonymous> (/drivers/philips-bulb/driver.js:4:14)
at Module._compile (module.js:643:30)
at Object.Module._extensions..js (module.js:654:10)
at Module.load (module.js:556:32)
at tryModuleLoad (module.js:499:12)

Exit code: 1
Exit signal: null

**Comment by jghaanstra** [comment]
Did you download the complete repo as zip file including the node_modules directory which includes the miio module?

**Comment by rostov36** [comment]
It’s my mistake. It’s ok now. What I must to do?

**Comment by jghaanstra** [comment]
Use the Athom CLI and run the app with "athom app run" command. And see if there is any error logging directly available in the console. If not re-pair your light and than copy and paste the output here.

**Comment by rostov36** [comment]
2018-05-28 23:50:05 [log] [XiaomiMiioApp] Initializing Xiaomi Mi Home app ...
Creating device
Initializing device
Polling device
(node:10748) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): ReferenceError: reject is not defined
(node:10748) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2018-05-28 23:50:15 [log] [ManagerDrivers] [philips-bulb] [0] TypeError: colorTemperature.replace is not a function
    at getData (/drivers/philips-bulb/device.js:82:45)
    at <anonymous>

**Comment by rostov36** [comment]
2018-05-28 23:50:05 [log] [XiaomiMiioApp] Initializing Xiaomi Mi Home app ...
Creating device
Initializing device
Polling device
(node:10748) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): ReferenceError: reject is not defined
(node:10748) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2018-05-28 23:50:15 [log] [ManagerDrivers] [philips-bulb] [0] TypeError: colorTemperature.replace is not a function
    at getData (/drivers/philips-bulb/device.js:82:45)
    at <anonymous>

**Comment by jghaanstra** [comment]
OK, thanx. I'll look into it some time soon and will let you know.

**Comment by rostov36** [comment]
thanks for the help. Tell me, when it will be possible to solve the problem approximately?

**Comment by rostov36** [comment]
request to https://api.athom.com/user/me failed, reason: read ECONNRESET
what my mistake?

**Comment by jghaanstra** [comment]
Not yet, but I'm getting closer. I have just pushed another update to the debug branch. Could you test again, also by changing the color temperature through Homey but also through the Mi Home smartphone app and once again post the results here.

https://github.com/jghaanstra/com.xiaomi-miio/tree/debug

**Comment by rostov36** [comment]
─────────────── Logging stdout & stderr ───────────────
2018-05-29 20:49:40 [log] [XiaomiMiioApp] Initializing Xiaomi Mi Home app ...
Creating device
Initializing device
Polling device
(node:2726) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): ReferenceError: reject is not defined
(node:2726) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Color { values: [ 5646 ], model: 'temperature' }
Color { values: [ 5646 ], model: 'temperature' }
Color { values: [ 5646 ], model: 'temperature' }
Color { values: [ 5646 ], model: 'temperature' }
Color { values: [ 5646 ], model: 'temperature' }
Color { values: [ 5646 ], model: 'temperature' }
Color { values: [ 5646 ], model: 'temperature' }

**Comment by rostov36** [comment]
2018-05-29 20:54:15 [log] [XiaomiMiioApp] Initializing Xiaomi Mi Home app ...
Creating device
Initializing device
Polling device
Color changed:  Color { values: [ 5646 ], model: 'temperature' }
Color changed normalized:  NaN
(node:3534) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): ReferenceError: reject is not defined
(node:3534) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by jghaanstra** [comment]
New version uploaded, please test again.

**Comment by jghaanstra** [comment]
I have not heard back from you. I'm publishing a new release to the app store (2.6.5) which contains the fixes allowing you to pair your Philips devices. If you experience any more issues please open up a new report.

**Comment by rostov36** [comment]
Yesterday I tested. It’s ok. But I have a new problem) I will give you a link
