### ISSUE TITLE
Add support for Desk Lamp

### ISSUE THREAD

**Issue by WeeJeWel** [jghaanstra/com.xiaomi-miio#35]
I've got this device: https://www.yeelight.com/en_US/product/mijia-lamp
The app does not find it using the 'Yeelights' driver. The ceiling light, which is connected to the same network is recognized.

**Comment by jghaanstra** [comment]
It seems the type name of lamp is not mentioned in the Yeelight api docs. These are used during discovery. I'll ask around and will add it once I know it's type name.

**Comment by WeeJeWel** [comment]
Can I help you debugging? Maybe send a log?

**Comment by jghaanstra** [comment]
No need, already found the model identifier. Will add it soon.

**Comment by jghaanstra** [comment]
Implemented with release 2.6.5.

https://github.com/jghaanstra/com.xiaomi-miio/releases/tag/2.6.5
