### ISSUE TITLE
Remove hue/sat from ceiling light, and fix temperature range

### ISSUE THREAD

**Issue by WeeJeWel** [jghaanstra/com.xiaomi-miio#36]
RE: App Store comment

I have this device: https://nl.aliexpress.com/item/New-Original-Xiaomi-Yeelight-Smart-Ceiling-Light-Lamp-Remote-Mi-APP-WIFI-Bluetooth-Control-Smart-LED/32855767684.html?spm=a2g0s.9042311.0.0.27424c4ddWzRQT

Homey thinks there are Hue/Sat controls, but this light doesn't support them.
Also the temperature is out of range. In the warmest regions, the temperature is not applied.

**Comment by jghaanstra** [comment]
Most likely fixed with https://github.com/jghaanstra/com.xiaomi-miio/commit/543802e520935403f48b20982ba4361e1da2f3b6

Please comment if the issue still persists.
