### ISSUE TITLE
adding Philips light bulb error

### ISSUE THREAD

**Issue by kopanicak** [jghaanstra/com.xiaomi-miio#37]
i can't add Philips light bulb.
i have got an error: device.power is not a function.
IP and token are good.

what i do wrong? thanks

![screen](https://user-images.githubusercontent.com/9351901/40987429-c8ada08a-68e8-11e8-8392-e372d83b39e3.png)

**Comment by jghaanstra** [comment]
Are you sure your token is correct. Another user has reported the Philips Light Bulbs to be working correctly. See https://github.com/jghaanstra/com.xiaomi-miio/issues/33

I dont own the device myself so I cant test it.  If you know your way around nodejs and the command line I could create a little test script that might give more info on what is going on. Let me know.

**Comment by jghaanstra** [comment]
Install nodejs and the miio command line (npm install -g miio)

Go to your nodejs directory and create a file called miio.js which contains the following:
```
const miio = require('./node_modules/miio/lib');

// Create a new device over the given address
miio.device({
	address: '192.168.0.1',
  token: 'xxxxxxxxxxxxxxxxxxxxxxx'
}).then(device => {
  const getData = async () => {
      try {
          const power = await device.power();
          const brightness = await device.brightness()
          const color = await device.color();

          let result = {
              onoff: power,
              brightness: brightness,
              color: color,
          }

          console.log(result)
      } catch (error) {
          console.log(error);
      }
  }
  getData();
}).catch(err => console.log('Error occurred:', err));
```

Edit the path to where you installed miio, the IP address of your bulb and your token. Then run the script with node miio.js and let me know the output.

**Comment by kopanicak** [comment]
![screen5](https://user-images.githubusercontent.com/9351901/41189523-85c51d40-6bcf-11e8-93fa-6c1c8f346bbe.jpg)

if I write bad token i have got an error "Could not connect to device"

**Comment by rostov36** [comment]
My bulb works good. I can help but not earlier than June 13th. I'm not in the city.

**Comment by rostov36** [comment]
@kopanicak can you reboot your bulb? May be in this problem)

**Comment by kopanicak** [comment]
![q02](https://user-images.githubusercontent.com/9351901/41190616-b583be5c-6be2-11e8-8299-f4bf382eac96.jpg)
![q01](https://user-images.githubusercontent.com/9351901/41190618-ba098e0c-6be2-11e8-83e1-6259de9afa18.jpg)

I have these bulbs from Gearbest. Buyed in May 2018. I reset bulbs four times and I still can not pair with Homey.

**Comment by rostov36** [comment]
This lamp doesn’t support plugin.

**Comment by kopanicak** [comment]
ok. there is the problem. i'm sorry for my mistake. thank for support.

**Comment by kopanicak** [comment]
it is possible to make support for these very popural cheap bulbs? can I help with something? what is the way for adding support with unknown devices?

**Comment by jghaanstra** [comment]
@kopanicak you can control it using the Mi Home smartphone app?

If so, you can have a look here on how to add support: https://github.com/aholstenson/miio/blob/master/docs/missing-devices.md

For now I'm closing this issue.
