### ISSUE TITLE
Zone cleaning

### ISSUE THREAD

**Issue by hultis** [jghaanstra/com.xiaomi-miio#44]
Hi!

Is it possible to add zonecleaning to the vacuume in Homey?
It works with HA according to the link below:

https://hackernoon.com/how-i-set-up-room-cleaning-automation-with-google-home-home-assistant-and-xiaomi-vacuum-cleaner-9149e0267e6d?gi=bcbd691e0023

Would be great if I could set up a card and tell the Homey what coordinates it should vacuum.

Thanks =)

**Comment by jghaanstra** [comment]
I'm awaiting this PR to be included in the miio library. Once it becomes available I can implement it in the Homey app.

https://github.com/aholstenson/miio/pull/133

**Comment by jghaanstra** [comment]
A pull request means someone else has already written the code but the owner needs to approve the edits and add them to the library. The PR is months old, so the owner does not seem to be actively maintaining the library anymore. So I'd say, not any time soon.

**Comment by hultis** [comment]
Oh I see, thats a bummer :/ but Thank you! :)

**Comment by jghaanstra** [comment]
Fixed with release 2.8.0. It's awaiting approval in the app store.

https://github.com/jghaanstra/com.xiaomi-miio/releases/tag/2.8.0

I have implemented the PR request in an own version of the miio library.
