### ISSUE TITLE
hello i'm trying to get the token to install Xiaomi gateway.

### ISSUE THREAD

**Issue by marc900** [jghaanstra/com.xiaomi-miio#45]
hello i'm trying to get the token to install Xiaomi gateway
I'm using a iPad/imac
Any help..

**Comment by jghaanstra** [comment]
Follow the instructions as described here: https://github.com/jghaanstra/com.xiaomi-miio/blob/master/docs/obtain_token.md

I don't have any Apple devices so I can't help any further.

**Comment by marc900** [comment]
Hello Mr Haanstra,

Thank you for your reply,
I’ve got one reply of the gateway Xiaomi, according to your instruction.
Can you help me translate which is the token code? I hope you can help 

See attachment
kind Regards
Marc Jacob

**Comment by marc900** [comment]
Hello Mr Haanstra,

I’ve got it worked with the third option, of your instruction link. 
Although the query did not work, i could find the key in the database

One question, is it possible to use the gateway also as a doorbell ? (I could not find this in the options-flow of the device)

Please let me know
Kind Regards
Marc Jacob

**Comment by jghaanstra** [comment]
No, unfortuntely the miio library used by my app does not support any kind of doorbell capability.
