### ISSUE TITLE
Xiaomi Gateway

### ISSUE THREAD

**Issue by marc900** [jghaanstra/com.xiaomi-miio#46]
Hello,
Ive managed to connect the gateway with Homey. I Thought one of the advantages of the gateway is the function as a amplifier, when the signals are poor.  With the developer tool i don't recognize the gateway in the loops of the other sensors. Can you explain why and what can i furthermore do with this  gateway ?

**Comment by jghaanstra** [comment]
My app only communicates with Xiaomi devices over WiFi. So extending ZigBee mesh is certainly not within scope. It would require adding the gateway as a slave ZigBee device and I'm not sure of that is even possible. You will have to ask in the Xiaomi ZigBee support thread on the athom forum.

**Comment by marc900** [comment]
Hello JG
Thanks for the reply
