### ISSUE TITLE
Power Strip does not work

### ISSUE THREAD

**Issue by edsallo** [jghaanstra/com.xiaomi-miio#48]
Through the plug-in, turn off, but do not turn on.
Does not show the real status of the power strip.
Do not display consumption readings.
Two power strip without USB, firmware 1.2.4_58.
One power strip with USB, firmware 3.4.2._79.

**Comment by jghaanstra** [comment]
I'll probably drop support for this device. I dont own it and it's poorly documented so there is no way for me to troubleshoot it.

**Comment by jghaanstra** [comment]
Power consumption has been partially added. Closing this issue.
