### ISSUE TITLE
Add consumable statusses of the Mi Robot Vacuum Cleaner

### ISSUE THREAD

**Issue by jghaanstra** [jghaanstra/com.xiaomi-miio#5]
This has not been implemented in the miio library yet so it requires a pull request.

**Comment by jghaanstra** [comment]
Support for the Mi Robot Vacuum Cleaner will be dropped with release 2.3.0-beta since the miio library is unable to communicate with the robot as of firmware 3.3.9_003077.

**Comment by jghaanstra** [comment]
Reopened as support for the vacuumcleaner has returned.

**Comment by dennisbrouwer91** [comment]
Any idea on when the Vacuumcleaner support will be back in the Homey app?

**Comment by jghaanstra** [comment]
@dennisbrouwer91  It is already, it's in the beta channel in the Homey app store.

**Comment by jghaanstra** [comment]
Depends on https://github.com/aholstenson/miio/issues/95
