### ISSUE TITLE
unable to connect to Gateway in another subnetwork

### ISSUE THREAD

**Issue by HenkeMX** [jghaanstra/com.xiaomi-miio#52]
Hi, 
I have put the Gateway v.3 in a guest wifi network different from Homey but with full access from Homey's network to the guest network. But it does not work to add the Gateway in Homey. I get the message:  **Could not connect to device, handshake timeout**

When they were in the same subnetwork it worked fine, but I would like to isolate them from each other.

**Comment by jghaanstra** [comment]
This is probably not supported by the miio library used in my Homey extension. An issue slightly related to this has been reported already here: https://github.com/aholstenson/miio/issues/106

Does it work when you add the gateway in the Mi Home smartphone app when your phone is connected to the other network. It might not even be supported by Xiaomi at all.

Either way, there is not much I can do about it. You could report it in the miio repo and hope it gets fixed but support seems to be dead.

**Comment by HenkeMX** [comment]
I have the Gateway connected to the APP even if they are on separate Wifi networks, as well as the Vacuum Cleaner v1. So I figured it would work also with Homey.

**Comment by jghaanstra** [comment]
Where you able to add the vacuum cleaner in Homey, even though it's on a different network?

**Comment by HenkeMX** [comment]
Vacuum not added to Homey yet, not managed to get hold of the secret needed.
