### ISSUE TITLE
Roborock s50 will not take commands in v.2.8.3

### ISSUE THREAD

**Issue by cop112** [jghaanstra/com.xiaomi-miio#53]
Worked out fine with v.2.8.2 but not since last update. Flows do nothing and when I try to change the status of the mi robot in devices I get the following error message: "Something went wrong addressing device Mi Robot (Network communication is unavailable, device might be destroyed".

Device is certainly not destroyed :)

**Comment by jghaanstra** [comment]
Have you tried restarting the Homey app?

And could it be your vacuum cleaner has changed IP address or the token has changed do to an update or new setup?

**Comment by jghaanstra** [comment]
Issue closed due to inactivity.
