### ISSUE TITLE
Retreive token 

### ISSUE THREAD

**Issue by Luckystar1210** [jghaanstra/com.xiaomi-miio#54]
Hi,

I´m a Homey user and have installed your Homey app Xiaomi Mi Home.
When adding a device I need a token and you have made an excelent description on how to retreive that token. Thanks!
Method one did not return a token, so I continued with method 3.

When excecuting the query from miio2.db to retreive the token, the query returns null.

![xiaomi_token](https://user-images.githubusercontent.com/43998955/46681669-074ce380-cbec-11e8-8073-f8bda6a35d85.JPG)

During install of my Xiaomi Roborock, I updated the unit to latest firmware (3.3.9_001632). Could it be that there is an update of how the token is handeled?

**Comment by jghaanstra** [comment]
No, all firmware version are supported. But as mentioned in the tutorial you need to use an older version of the Mi Home app since the latest versions dont hold the token anymore.

>>> The latest versions of the Mi Home smartphone app dont hold the token anymore so before you begin with any of these methods you will need to install an older version of the smartphone app. Version 5.0.19 works for sure and perhaps maybe even some newer version as well. Android users can find older version of the app here.
