### ISSUE TITLE
Support for xiaomi smartmi air humidifier 2

### ISSUE THREAD

**Issue by LyoshaDovolen** [jghaanstra/com.xiaomi-miio#55]
Please add support for Xiaomi smartmi air humidifier 2
https://www.aliexpress.com/wholesale?catId=0&initiative_id=AS_20181011071521&isPremium=y&SearchText=xiaomi+smartmi+air+humidifier+2

**Comment by jghaanstra** [comment]
Unfortunately this device is not supported yet by the underlaying miio library. Support for this device has been requested already here: https://github.com/aholstenson/miio/issues/155

Once it's supported by miio I will implement it in the Homey app as well but the miio library is currently unmaintained so I'm not sure if this is ever gonna happen.

For my own reference, xtra details for adding support can be found here: https://github.com/rytilahti/python-miio/pull/388/files and  https://community.home-assistant.io/t/xiaomi-humidifier-support/35672/50

**Comment by jghaanstra** [comment]
Yes, I forgot to close this issue. Support for this has been added some time ago. Closing it now.
