### ISSUE TITLE
hub ver. 3 

### ISSUE THREAD

**Issue by falco-lt** [jghaanstra/com.xiaomi-miio#57]
problem: homey  can't see aqara hub v3 (lumi-gateway-v3-miape04c)

**Comment by falco-lt** [comment]
Xiaomi Aqara Upgraded ZigBee Version Gateway ver. 3 - i cant connect to homey

**Comment by jghaanstra** [comment]
Could you try and retrieve the mode identifier using the miio command line as described here: https://github.com/aholstenson/miio/blob/master/docs/missing-devices.md

**Comment by falco-lt** [comment]
all ok - problem was software
