### ISSUE TITLE
Yeelight Ceiling Light status sometimes incorrect

### ISSUE THREAD

**Issue by chinswain** [jghaanstra/com.xiaomi-miio#59]
I have a large number of Yeelight Ceiling lights around the house, quite often they are switched on\off using their paired bluetooth remotes. Occasionally it seems this causes the the "Is Turned Off\On" Card to fail (Due to the Turned On Tag being incorrect).
Is it possible to query the status of the light when the Is Turned Off\On card is activated?

I'll run the app via CLI and try to reproduce the issue at the weekend.

**Comment by jghaanstra** [comment]
My guess is that the connection between Homey and the light has broken and the light appears as offline and thus the Turned Off/On card will return an incorrect status. If this is the case it can not be solved by polling the light once this condition card is called. A CLI install should be able to confirm this. I might need to make a specific debug version if it's not clear yet.

If this is actually the cause I might not be able to solve it. I see this behaviour sporadically with my own Yeelight (I have only one) but cant explain why it happens and what more I can do to solve it.

**Comment by jghaanstra** [comment]
Closed due to inactivity. Feel free to comment if you still want to try to debug this.
