### ISSUE TITLE
Permanent Internet connection

### ISSUE THREAD

**Issue by GSanCap** [jghaanstra/com.xiaomi-miio#62]
Its mandatory that the controlled device (Ex. Xiaomi Universal IR Remote) has permanent Internet connection? If I put my Xiaomi device in a inet isolated network the "miio discover" command don't show token anymore

Thanks

**Comment by jghaanstra** [comment]
This is not the repository for miio. You are better off asking your question about the miio CLI here: https://github.com/aholstenson/miio

But reading your own findings I'd say it's indeed required to have a permanent internet connection.
