### ISSUE TITLE
Yeelight stopped working

### ISSUE THREAD

**Issue by pave-xx** [jghaanstra/com.xiaomi-miio#63]
Homey lost my yeelight. 

I removed it and trying to reconnect it. But during the "add new device" screen in homey it just says that it cant find any new devices.

Any tips?

**Comment by jghaanstra** [comment]
Could you try and restart the Xiaomi app on Homey and try pairing again.

(and are you sure you have enabled LAN mode / developer mode for your Yeelight?)

**Comment by jghaanstra** [comment]
Closed due to inactivity.
