### ISSUE TITLE
Xiaomi Philips Zhirui Downlights

### ISSUE THREAD

**Issue by chinswain** [jghaanstra/com.xiaomi-miio#65]
I've just installed the new release with Xiaomi Philips Zhirui Downlight support but it doesn't appear to work, I receive the below error "device.power is not a function"

![err](https://user-images.githubusercontent.com/4403897/49150756-c88efc00-f305-11e8-86b8-6330d4a491a3.PNG)

**Comment by jghaanstra** [comment]
That's too bad, someone will have to retrieve the valid commands for this device. I see you have requested for support already in the miio library but since it looks like it's abandoned I dont think it will be supported any time soon.

**Comment by chinswain** [comment]
Oh no - It's been abandoned? Not great news!

**Comment by jghaanstra** [comment]
Appearantly not in combination with the miio library. This device model is already registered. I'm actually quite surprised it's not working.

https://github.com/jghaanstra/com.xiaomi-miio/blob/e553d5ea261913c4050602ec97a419779cbc4962/node_modules/miio/lib/models.js#L64

**Comment by jghaanstra** [comment]
> Would that change work?

I have updated the app here on Github, could you try again.

**Comment by chinswain** [comment]
Same issue again unfortunately (device.power is not a function), I've tried removing the app, rebooting Homey and running via CLI.

I've reset the light and captured the new token via the Packet Sender method, added to the Mi Home Android app to connect the light to WiFi.

I get no output from the console when running, is there a debug method I could enable?

**Comment by jghaanstra** [comment]
Ah that is what I need!

I have uploaded a new release to Github, could you see if that work?

**Comment by chinswain** [comment]
Success!

**Comment by JoeyPoortman** [comment]
Its been a while since anything got posted here, but my new downlights have a higher firmware version and won't show up in HA is there a chance you can look into it @jghaanstra  ?
