### ISSUE TITLE
Cannot get token from the Xiaomi Gateway (Hong Kong version)

### ISSUE THREAD

**Issue by tath105** [jghaanstra/com.xiaomi-miio#68]
Hi all,

Thanks for your time/help in advance. I'm looking for a way to get the LAN Communication Token (16 characters) from Xiaomi Gateway (Hong Kong version). I can retrieve the token in the China version using the official XiaoMi app (I got some previously and I'm still allowed to reset the token).

In the China version, I can use the official XiaoMi App in iOS to get the token: i) go to "About", ii) click the blank areas 3 times.

However, for the Hong Kong version I bought, the "About" option is gone in the same APP, note:
  1. I connect the Gateway (Hong Kong version) in the region "Hong Kong"
  2. the Gateway failed to initiate if in the region "China" (that means I do not even have a chance to try if I can go to "About" page)

Given the above do not work, I have tried the following link (which I think is quite comprehensive). I could get a 96-character token via iOS backup but have no clue how to get the 16 character token I need.
The link: https://github.com/jghaanstra/com.xiaomi-miio/blob/master/docs/obtain_token.md

Appreciate if anyone can share any experience.

**Comment by jghaanstra** [comment]
Just follow the last steps from the tutorial.

```The latest Mi Home app store the tokens encrypted into a 96 character key and require an extra step to decode this into the actual token. Visit this website and enter the details as shown below: ** Input type: text
Input text (hex): your 96 character key
Selectbox Plaintext / Hex: Hex
Function: AES
Mode: ECB
Key (hex): 00000000000000000000000000000000
Selectbox Plaintext / Hex: Hex
Hit the decrypt button. Your token are the first two lines of the right block of code. These two lines should contain a token of 32 characters and should be the correct token for your device.```

**Comment by tath105** [comment]
@jghaanstra  thanks, and I read the same, and I got a "32-character" token; However home-assistant requires me to use a "16-character" token. Any suggestion in this case?

**Comment by jghaanstra** [comment]
Dont know why Home Assistant would ask for a 16-character token. The method you followed as described in the library will leave with a 32-character token which is the correct size.
