### ISSUE TITLE
Mi Air Purifier Pro Set Speed doesn't work in flow errors with "unknown error"

### ISSUE THREAD

**Issue by gekonizer** [jghaanstra/com.xiaomi-miio#70]
Homey 2.0
Mi Air Purifier Pro Set Speed doesn't work in flow. Errors with "unknown error" if I tests flow. See attached pictures.

![image](https://user-images.githubusercontent.com/30910474/51807169-d7e9e180-2283-11e9-90c1-96fd4f1272cd.png)
when pressed exclamation mark:
![image](https://user-images.githubusercontent.com/30910474/51807173-e6d09400-2283-11e9-9a19-9e2d66de5f5e.png)

**Comment by jghaanstra** [comment]
How does setting the speed for this Mi Air Purifier Pro work in the Mi Home app. It also allows you to change the mode to favorite and then set the speed from 1 till 16?

**Comment by jghaanstra** [comment]
I have changed something in the app and pushed a new release to Github. Do you know how to do a CLI install to test if this is working for you.

https://community.athom.com/t/how-to-cli-install-method/198

**Comment by gekonizer** [comment]
In Mi Home app I can set favorite mode (manual) and change speed with slider bar. See pictured attached below
![img_ce55fafa2054-1](https://user-images.githubusercontent.com/30910474/51942457-6773c980-2417-11e9-9b31-5505c00a9c36.jpeg)
![img_62a42a09d88b-1](https://user-images.githubusercontent.com/30910474/51942528-968a3b00-2417-11e9-93f4-c41a386e2ba2.jpeg)

**Comment by jghaanstra** [comment]
@gekonizer see my previous message

> I have changed something in the app and pushed a new release to Github. Do you know how to do a CLI install to test if this is working for you.

https://community.athom.com/t/how-to-cli-install-method/198

**Comment by gekonizer** [comment]
Tested with new version (2.10.0) and still the same problem - 'unknown error' durring try to set favorite speed
![img_a3a92abc879d-1](https://user-images.githubusercontent.com/30910474/51943141-0cdb6d00-2419-11e9-967e-9f149806ea97.jpeg)

**Comment by jghaanstra** [comment]
Bugger, it's hard to troubleshoot something like this without the actual device.

I have uploaded some changes to Github. Could you run the app from command line (`athom app run`) and try to set the favorite level again. I'm hoping to see some more information through the command line logging.

**Comment by gekonizer** [comment]
After last your changes it works! Thanks! :)

─────────────── Logging stdout & stderr ───────────────
2019-01-29 23:09:19 [log] [XiaomiMiioApp] Initializing Xiaomi Mi Home app ...
trying to set level set:  15
trying to set level set:  8

![img_cccef679ac64-2](https://user-images.githubusercontent.com/30910474/51944207-bf143400-241b-11e9-8d86-b0c3f3ef3e7d.jpeg)

**Comment by jghaanstra** [comment]
Great, I'll add this into the next release.

I'm trying to add the waterlevel for the humidifier v2 as well, I noticed in the screenshots you also own a humidifier. Is it perhaps a v2 and would you be willing to test if this is working. It would require you to re-pair the device while running version 2.10.0 on the command line and give me feedback on the output from the console. More info here: https://github.com/jghaanstra/com.xiaomi-miio/issues/71

I'm closing this issue.

**Comment by gekonizer** [comment]
Ok, sure. I have v2. I will try to test it.
