### ISSUE TITLE
Evaporate Humidifyer 2 - Water level

### ISSUE THREAD

**Issue by efurdal** [jghaanstra/com.xiaomi-miio#71]
Could you add the water level sensor on the Evaporate Humidifyer 2, to the Homey app?
That way I add some flows and monitor the water level :)

**Comment by jghaanstra** [comment]
I have just pushed a new version to GitHub which adds a new driver for the Humidifier v2. It still contains the icon of the v1 and the waterlevel capability has not been implemented fully yet but if you could test this it would tell me if I have implemented the waterlevel correctly into the miio library. What you need to do is download the version from the link below and use the CLI install method to run the app with `athom app run`. Once the app is running you will need to re-pair the device as the humidifier v2. Once paired you should see the water level in the pairing wizard and also in the command line every time Homey polls the device. Please let me know if this is actually the case.

**Comment by gekonizer** [comment]
It seems it works. See logs:
─────────────── Logging stdout & stderr ───────────────
2019-01-29 23:33:27 [log] [XiaomiMiioApp] Initializing Xiaomi Mi Home app ...
Waterlevel:  99.16666666666667
Waterlevel:  99.16666666666667
Waterlevel:  99.16666666666667
Waterlevel:  99.16666666666667
Waterlevel:  98.33333333333334
Waterlevel:  99.16666666666667
Waterlevel:  99.16666666666667

![img_43bfbc43dd45-1](https://user-images.githubusercontent.com/30910474/51945576-6cd51200-241f-11e9-8e45-3f2dd7bcee79.jpeg)

**Comment by jghaanstra** [comment]
@gekonizer  Thanx for letting me know. I have just pushed a new update to Github adding the actual capability to the device. Could you please re-pair th device and see if the capability is updated in the Homey app (and that the icon of this custom capability is visible).

**Comment by gekonizer** [comment]
@jghaanstra it seems that in app.json is mistake. Is not parsed correctly during start application.
logs:
Error in `app.json`:
SyntaxError: Unexpected token ] in JSON at position 19222

It seems that in line 832 is '},' but seems should be just '}'.
When I changed like this, application runs. But I don't see any changes.
See pictures:
![img_2885](https://user-images.githubusercontent.com/30910474/51971087-ae45db80-2478-11e9-9115-857a899f69a4.PNG)
![img_2886](https://user-images.githubusercontent.com/30910474/51971097-b30a8f80-2478-11e9-96a6-f67aff4b22f6.PNG)
![img_7930a6e1e613-1](https://user-images.githubusercontent.com/30910474/51971105-b4d45300-2478-11e9-8a5d-195951c3a6c2.jpeg)

**Comment by gekonizer** [comment]
@jghaanstra 

Now it looks better. Waterlecel icon appears but without value (see picture) Flow cards still haven't waterlevel as a trigger (see picture). Durring pairing homey app crashed but after re-runing homey app I see that the device is added properly.

![img_2892](https://user-images.githubusercontent.com/30910474/51977856-e0f7d000-2488-11e9-83e7-5dd1b3d1cdce.PNG)
![img_2891](https://user-images.githubusercontent.com/30910474/51977858-e2c19380-2488-11e9-8442-f22015bea4bd.PNG)



See logs. I don't known if they are usefull for you:
─────────────── Logging stdout & stderr ───────────────
2019-01-30 12:05:23 [log] [XiaomiMiioApp] Initializing Xiaomi Mi Home app ...
(node:7546) UnhandledPromiseRejectionWarning: Error: invalid_step
    at Object.JSON.parse (/opt/homey-client/system/helpers/jsonfns.js:1:1190)
    at JSON.parse (<anonymous>)
    at jsonToObject (/opt/homey-client/system/helpers/jsonfns.js:1:1083)
    at function.e.data.map.e (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1379)
    at Array.map (<anonymous>)
    at HomeyClient._onMessage (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1372)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:762:12)
    at _combinedTickCallback (internal/process/next_tick.js:142:11)
(node:7546) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7546) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:7546) UnhandledPromiseRejectionWarning: Error: invalid_step
    at Object.JSON.parse (/opt/homey-client/system/helpers/jsonfns.js:1:1190)
    at JSON.parse (<anonymous>)
    at jsonToObject (/opt/homey-client/system/helpers/jsonfns.js:1:1083)
    at function.e.data.map.e (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1379)
    at Array.map (<anonymous>)
    at HomeyClient._onMessage (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1372)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:762:12)
    at _combinedTickCallback (internal/process/next_tick.js:142:11)
(node:7546) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:7546) UnhandledPromiseRejectionWarning: Error: invalid_step
    at Object.JSON.parse (/opt/homey-client/system/helpers/jsonfns.js:1:1190)
    at JSON.parse (<anonymous>)

**Comment by jghaanstra** [comment]
I think we are almost there. Could you try again?

**Comment by gekonizer** [comment]
@jghaanstra water level is shown correcly right now. Flow still have no wter level trigger.
![img_a383f2ee045d-1](https://user-images.githubusercontent.com/30910474/51982187-8add5980-2495-11e9-9e93-99501c1e68f8.jpeg)
![img_97df58a8cbc5-2](https://user-images.githubusercontent.com/30910474/51982208-9af53900-2495-11e9-9c9e-c03c7eda676a.jpeg)

**Comment by jghaanstra** [comment]
Argghh ... made a small boo boo. Could you try again, I really hope it's fixed now!

**Comment by gekonizer** [comment]
@jghaanstra Great! It works now. I have added a flow and it triggered when I added more water to the humidifier. Good job!
![img_2898](https://user-images.githubusercontent.com/30910474/51985640-a0a34c80-249e-11e9-915c-30fac8e51d37.PNG)

**Comment by jghaanstra** [comment]
Thank you for testing. I'll push this to the app store this evening. Closing this issue.
