### ISSUE TITLE
Would it be possible to declare Humidifier (and maybe Air Purifiers) as device class fan, or switch?

### ISSUE THREAD

**Issue by Moskvitch** [jghaanstra/com.xiaomi-miio#73]
No expert here, but could you take a look at this, please

https://github.com/swttt/com.swttt.homekit/issues/140

**Comment by robertklep** [comment]
Or possibly use a virtual class "fan", that's something that we could probably work with for Homeykit.

**Comment by jghaanstra** [comment]
@robertklep That does not sound to hard but I have no idea how I can set a virtual class. Do you have a link to the documentation or an example?

**Comment by robertklep** [comment]
It's not documented :( There's a reference to the `virtualClass` property in the [Web API documentation](https://developer.athom.com/docs/api/HomeyAPI.ManagerDevices.Device.html); the only reason I know about it is that we [received a PR for Homeykit](https://github.com/swttt/com.swttt.homekit/pull/117) a while back where devices with class `socket` had a virtual class `light`.

I have no idea how to set it, but I assume it works by adding a `virtualClass` property to the pairing data.

**Comment by jghaanstra** [comment]
I believe the virtual class is only available for devices with the socket class. It can be set using the 'choose slave' template when pairing the device. See the [documentation ](https://apps.developer.athom.com/tutorial-Drivers-Pairing-System%20Views-Choose%20Slave.html)here.

Changing the purifier or humidifier to a socket device class does not seem like a smart plan. Any other way to achieve integration with the Homekit app?

**Comment by robertklep** [comment]
I agree that you shouldn't use `socket` as a class.

I'll try and see if I can get `sensor` devices with an `onoff` capability working properly. In that case, you don't have to change anything.

**Comment by jghaanstra** [comment]
Ok, if needed post back here. I'm closing this for now.

**Comment by robertklep** [comment]
I think I can make it work inside of Homeykit 👍🏻

**Comment by Moskvitch** [comment]
Do I understand correctly that it can be done by fine-tuning Homeykit without any changes to the Mi Home app needed?

**Comment by jghaanstra** [comment]
Yes, is correct.
