### ISSUE TITLE
Yeelight shows as offline after update 

### ISSUE THREAD

**Issue by snowmandk71** [jghaanstra/com.xiaomi-miio#74]
After updating to 1.5.9 0189 my Yeelight ceeling light can not be operated. I can delete and rediscover but still status “unavaiable”

**Comment by jghaanstra** [comment]
Have you tried removing the device, restarting Homey and re-pairing again. If the problem persists please try to run the app from the command line and see what extra logging this gives you.

Btw, this firmware version is not even available to me yet for my Yeelight JIAOYUE 650 (MoonLight).

**Comment by snowmandk71** [comment]
Brilliant - simple solutions often helps :-)
Restarted Homey deleted light (again) and added - now it works :-)
Thanks for quick respons.
