### ISSUE TITLE
New bug latest update

### ISSUE THREAD

**Issue by ehdegroot** [jghaanstra/com.xiaomi-miio#75]
Update v2.11.1
Gives error: status.already_running_command
While adding any device.

**Comment by jghaanstra** [comment]
I can not reproduce this issue with a vacuum cleaner and the gateway. These are the only Xiaomi Mi Home devices I have myself. Could you be more specific when this error is given. What devices have you tested and when does this error come up (when testing the connection or in a later stage)?

**Comment by ehdegroot** [comment]
You can ignore me... i am sorry... for another issue i needed to reboot the Homey and that also solved this issue. Thnx for fast response.
