### ISSUE TITLE
Vacuum robot

### ISSUE THREAD

**Issue by Pim65** [jghaanstra/com.xiaomi-miio#76]
Hi,

Ive got the robot quite a long time, worked great with homey 1.5, but in v2 it isnt working at all. If i change status in the app, the robot is not reacting and gives a time out.if i give the robot the signal of cleaning (on the robot) the status in homey does change to cleaning. If its paused or charging it doesnt change in Homey.
What could this be?

Thanks Pim

**Comment by jghaanstra** [comment]
Does it work again (temporary) if you restart the Mi Home Homey app?

**Comment by Pim65** [comment]
Yes you can push every button but it gives a time out error all the time. Finally it does something, but due to the time outs it's getting wild in doing everything.

**Comment by jghaanstra** [comment]
Maybe it's a severe case of this issue: https://github.com/jghaanstra/com.xiaomi-miio/issues/27 . That's something I can not fix. Would be strange though that it has become worse with firmware 2.x.

What is the exact error you get on the flow card?

**Comment by Pim65** [comment]
That's the funny part, I do not get an error at all in a flow.
He just isn't reacting....all the time.
I just get time outs if I switch from for example cleaning to paused etc.
In the Xiaomi app thuis works flawless.

Verstuurd door Outlook<http://taps.io/outlookmobile> voor Android

________________________________

**Comment by jghaanstra** [comment]
I really dont know what is wrong then. You could try and run the app from the command line and try again. Perhaps that will spit out some extra logging that will point in a direction. For now I can not help you.

**Comment by jghaanstra** [comment]
Have you tried re-adding the device? Not sure if that helps but it might be worth a try.

**Comment by Pim65** [comment]
Hi Jelger,

I deleted the Robot, and got the token refreshed.

Problem is now that I can not install it in Homey.

everything is filled out correctly..

Pim

________________________________
Van: Jelger Haanstra <notifications@github.com>
Verzonden: zondag 24 februari 2019 19:20
Aan: jghaanstra/com.xiaomi-miio
CC: Pim65; Author
Onderwerp: Re: [jghaanstra/com.xiaomi-miio] Vacuum robot (#76)


I really dont know what is wrong then. You could try and run the app from the command line and try again. Perhaps that will spit out some extra logging that will point in a direction. For now I can not help you.

**Comment by jghaanstra** [comment]
Could you post a screenshot from the pairing screen with error when testing the connection.

**Comment by Pim65** [comment]
[cid:05672983-5ce5-413e-8749-e0136096e59d]


[cid:41b482a0-7f7c-4e3f-aa58-13c8fdd6c59c]

________________________________
Van: Jelger Haanstra <notifications@github.com>
Verzonden: woensdag 27 februari 2019 12:53
Aan: jghaanstra/com.xiaomi-miio
CC: Pim65; Author
Onderwerp: Re: [jghaanstra/com.xiaomi-miio] Vacuum robot (#76)


Could you post a screenshot from the pairing screen with error when testing the connection.

**Comment by jghaanstra** [comment]
Try again, something went wrong posting the screenshots.

**Comment by Pim65** [comment]
![image](https://user-images.githubusercontent.com/40526333/53491198-13034e80-3a96-11e9-8713-5a2a5b34c074.png)

![image](https://user-images.githubusercontent.com/40526333/53491224-23b3c480-3a96-11e9-9755-e104543df917.png)

**Comment by jghaanstra** [comment]
What I see is that the IP address in the Mi ToolKit differs from the one you are trying to add. 192.168.178.84 versus 192.168.178.84. Are you using the wrong IP?

**Comment by Pim65** [comment]
Also with the IP address change, no luck, same thing

Verstuurd door Outlook<http://taps.io/outlookmobile> voor Android

________________________________

**Comment by jghaanstra** [comment]
Same error?

Really dont know what is wrong. You seem to be the only one with this issue. Dont think I can help you with it.

**Comment by Pim65** [comment]
I will try a total reset of the robot

Verstuurd door Outlook<http://taps.io/outlookmobile> voor Android

________________________________

**Comment by Pim65** [comment]
I did a robot reset > new token > app is back alive , but still a lot of time out errors (error sending value timed out after 3000Ms)

beside that it seems to work.

Thanks for your help!

________________________________
Van: Jelger Haanstra <notifications@github.com>
Verzonden: woensdag 27 februari 2019 18:28
Aan: jghaanstra/com.xiaomi-miio
CC: Pim65; Author
Onderwerp: Re: [jghaanstra/com.xiaomi-miio] Vacuum robot (#76)


Same error?

Really dont know what is wrong. You seem to be the only one with this issue. Dont think I can help you with it.

**Comment by jghaanstra** [comment]
Unfortunately the time-out issue is something I can not fix. It's related to the miio protocol and how the miio nodejs library was coded.
