### ISSUE TITLE
Yeelights: Dim to 0% over X secs should turn the light off completely over X secs.

### ISSUE THREAD

**Issue by Moskvitch** [jghaanstra/com.xiaomi-miio#77]
Thx

**Comment by jghaanstra** [comment]
Fixed with release 2.11.2. Will push to app store soon.

https://github.com/jghaanstra/com.xiaomi-miio/commit/ffed9d9d5a6f7fe1f2224d0f50cc1e6fb122c993

**Comment by Moskvitch** [comment]
👍 Thanks!
