### ISSUE TITLE
Could not find that pairSesion

### ISSUE THREAD

**Issue by stefanprotzman** [jghaanstra/com.xiaomi-miio#78]
Ik wil de xiaomi gateway v3 toevoegen als apparaat in homey v2.0.4.
IP en token ingevuld, polling op 60 sec is prima lijkt me.
Als ik op 'test verbinding klik' komt er rode tekst in beeld:

"Could not find that pairSesion"
Wat mis ik nu?

**Comment by jghaanstra** [comment]
There is no such error message within my app so that seems to be a more generic Homey issue. Perhaps try and restart Homey and try again making sure not to keep the pairing window open for too long.

**Comment by jghaanstra** [comment]
Closed due to inactivity.
