### ISSUE TITLE
token size differs

### ISSUE THREAD

**Issue by skambar** [jghaanstra/com.xiaomi-miio#8]
Hey, 

using a dump from an iOS device the first weird thing was finding two sqllite files. One named as said in the tutorial for getting the tokens out of the app (_mihome.sqllite), one named 17xxxxx_mihome.sqllite. 
Only the second database contains values - seems like it was copied after checking in a new device - and looking for the token I found a character string containing 96 chars. 
I even splitted the string into strings of 32 chars but none of the strings were recognized by the vacuum cleaner I am trying to control. 
Do I miss something important here? Any help appreciated. 

Best regards

**Comment by jghaanstra** [comment]
I have read that the latest iOS update of the Mi Home app does not allow to retrieve the token anymore. I guess it's encrypted now or something.

It seems Xiaomi is actively trying to force users to use the Mi Home app instead of using the unofficial API to allow direct control.

There is pretty much nothing I can do about it.

**Comment by skambar** [comment]
Thank you for your response. 

I took an android tablet and there it worked like a charm. Unfortunately the device can not be paired with two phones and going back to iOS would reinitialize it - afaik. 
The current iOS version is nearly fully translated and I would love to use the iOS app in addition to the python controls.

**Comment by skambar** [comment]
[http://forum.iobroker.net/viewtopic.php?f=23&t=4898&sid=910cc87bd7a1a882437cbd92f1cd1ffc&start=1180](url)

In there you will find a javascript code which is actually able to decode the newly format the token has in the iOS app. It works!

**Comment by jghaanstra** [comment]
Awesome, thanx for posting. I'll update the docs when I have some time.

**Comment by jghaanstra** [comment]
Documentation has been updated.
