### ISSUE TITLE
Get Xiaomi Token & IP from Mi Home App (Android) without 3rd-party apps

### ISSUE THREAD

**Issue by trananhtuan** [jghaanstra/com.xiaomi-miio#80]
I find a new and easier way to obtain Token & IP by using only the log file of Mi Home App on Android (I use the latest version on Play Store, currently: 5.4.54). This doesn’t involve third-party apps, except for a file manager and a text-viewer, any will do. And you can do it easily on Android.

First, use any file manager to access folder SMARTHOME/LOGS/PLUG_DEVICEMANAGER on INTERNAL MEMORY of your Android phone. Look for a log file with format yyyy-MM-dd.txt (for ex: 2019-02-01), choose the most recent file (today date).
Open that file with a text editor of your choice and search for the name of Xiaomi Device (for ex: Mi Robot Vacuum), you will find something like this:

```
{"did":"117383849","token":"90557f13732y2494h278314a74d547b5","longitude":"x","latitude":"y","name":"Mi Robot Vacuum","pid":"0","localip":"192.168.88.68","mac":"40:31:3C:AA:BB:CC","ssid":"Your AP Name","bssid":"E4:8D:8C:EE:FF:GG","parent_id":"","parent_model":"","show_mode":1,"model":"rockrobo.vacuum.v1","adminFlag":1,"shareFlag":0,"permitLevel":16,"isOnline":true,"desc":"Zoned cleanup","extra":{"isSetPincode":0,"fw_version":"3.3.9_003460","needVerifyCode":0,"isPasswordEncrypt":0},"event":{"event.back_to_dock":"{\"timestamp\":1548817566,\"value\":[0]}
From here you can extract Token and Ip of the robot (“token”:“90557f13732y2494h278314a74d547b5”, “localip”:“192.168.88.68”

```
Can somebody confirm this method is working for you too?

**Comment by jghaanstra** [comment]
Amazing, this indeed works. I'll add it to the readme although I can hardly imagine this is something permanent. Seems to me this data should not be part of the log files.

**Comment by jghaanstra** [comment]
Unfortunately it does indeed not seem a reliable solution. I removed the folder and updated the Mi Home to the latest version. The folder did not return. Adding it to the documentation will probably only raise more questions than it solve them.

**Comment by trananhtuan** [comment]
They changed it in v5.4.56. I've just tried with v5.4.54 from https://mi-home.en.aptoide.com/ and it appears to be working (deleted the old LOGS, of course). Just download the app, sign-in and have all the plugins downloaded in the app.

This is still a lot easier than alternatives so I still think it's worth mentioning.

**Comment by jghaanstra** [comment]
Ok, I was gonna test that myself and I agree. It's good to add this info to the docs.

**Comment by trananhtuan** [comment]
Just tried a few different versions on an emulator and found out that **v5.4.54 is the only one that's working**. Just sign in Mi Home and the logs will appear at 
SMARTHOME/LOGS/PLUG_DEVICEMANAGER on INTERNAL MEMORY.

**Comment by jghaanstra** [comment]
That for sure confirms my initial thought that they probably never intended to include the token in the logs. Good to know and I'll point to this specific version.

**Comment by jghaanstra** [comment]
Updated.

https://github.com/jghaanstra/com.xiaomi-miio/blob/master/docs/obtain_token.md

**Comment by trananhtuan** [comment]
That was quick  :+1:

**Comment by stachdude** [comment]
Hey,

Does anybody still has this version somewhere and can share it ? It seems its not available for download, and the link in documentation seems a bit dangerous now. When you click for download you are redirected to a site which proposes to install some (unsafe and dangerous for sure) apk installer.
