### ISSUE TITLE
Mi Smart Kettle

### ISSUE THREAD

**Issue by Patrick1610** [jghaanstra/com.xiaomi-miio#82]
Could support for the smart kettle be added? Regards Patrick

**Comment by jghaanstra** [comment]
No. The Mi Smart Kettle is a Bluetooth device while this Homey app only has support for WiFi devices.

**Comment by Patrick1610** [comment]
That’s too bad! Any other ways to make that work with Homey?

**Comment by jghaanstra** [comment]
Not sure, I know little about the Homey support for Bluetooth devices but it does not seem very stable. I also don't know if the Bluetooth communication of Xiaomi devices has been hacked, don't think so. So little chance.
