### ISSUE TITLE
Yeelight Color v1 led bulb 100÷

### ISSUE THREAD

**Issue by TimTools** [jghaanstra/com.xiaomi-miio#83]
When i use a flow the app brightness is not set to 100÷

**Comment by jghaanstra** [comment]
Could you be more specific on which action card you are using and what the result is you are getting. To what brightness is it set according to the yeelight app.

**Comment by TimTools** [comment]
Yes i'm using color and brightness.
Color is set to white and brightness to 100 but it looks like 20. When i use yeelight i am able to increase the brightness

**Comment by TimTools** [comment]
Only when i use white mode in yeelight app the bulp is brighter

**Comment by jghaanstra** [comment]
White mode and color mode set to the color white will give you different results. Just to check, you use the "Color and brightness" action card. You set the color to #ffffff and the brightness to 100%. You then go into the Yeelight app and you can increase the brightness from 20% to 100% to actually get full brightness. And it's exactly set to 20% in the Yeelight app after setting it to 100% through a Homey flow with the "Color and brightness" action card?

**Comment by jghaanstra** [comment]
Closed due to inactivity.
