### ISSUE TITLE
App crashes on Homey reboot

### ISSUE THREAD

**Issue by DiedB** [jghaanstra/com.xiaomi-miio#84]
I'm using this app with two Yeelights (E27). Every time Homey reboots, the app crashes and I have to manually restart it before my lights work again.

**Comment by jghaanstra** [comment]
Do you Yeelights have a static it was dynamic ip address?

**Comment by DiedB** [comment]
I just assigned a static IP address to both lights, and rebooted Homey. The app did not crash this time.

However, power was out in the whole house while the crashes occured, so the router and access point were booting at the same time as well. I'll test this later as I am not home currently.

**Comment by jghaanstra** [comment]
Any news on this?

**Comment by DiedB** [comment]
I have not been able to reproduce the issue, but I still have to try powering down the whole house (will do that sometime during the night). Have you received any crash reports a week ago? It happened three or four times, every time the power went out.

**Comment by DiedB** [comment]
Powered down everything (while still having static IP addresses), the app did not crash this time around.

The only time it happens might be when dynamic IP addresses are assigned while the app starts. I still have to try that.

**Comment by DiedB** [comment]
Changing the IP address while the app restarts also works as expected, the device initializes offline and the app does not crash. Closing this issue for now.

**Comment by DiedB** [comment]
It occurred again. Homey Diagnostics report id is 7a0295a8-8e4f-4745-bf87-d492e45e5c11

**Comment by jghaanstra** [comment]
> Hi! Unfortunately, the app crashed while I was doing the following: (...) This is the stack trace:dgram.js:615 throw errnoException(err, 'addMembership'); ^ Error: addMembership ENODEV at Socket.addMembership (dgram.js:615:11) at Socket.<anonymous> (/lib/yeelight.js:40:20) at Object.onceWrapper (events.js:313:30) at emitNone (events.js:106:13) at Socket.emit (events.js:208:7) at startListening (dgram.js:156:10) at _handle.lookup (dgram.js:273:7) at __client.emit (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/SDK.js:1:2164) at HomeyClient._onMessage (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1360) at emitTwo (events.js:126:13)

It seems to be a corner case where the Homey app initializes and starts listening for broadcasts (used to update the state of the lights) but Homey has no active WiFi connection yet. Therefor adding a membership to multicast group at 239.255.255.250 fails. I'm not sure if I can catch this error preventing the app from crashing. I'll have to look into it.

**Comment by jghaanstra** [comment]
This should be fixed with the upcoming release 2.11.7. If the problem occurs again on this release please let me know.
