### ISSUE TITLE
Xiaomi Ceiling Light - update status of night mode capability

### ISSUE THREAD

**Issue by chinswain** [jghaanstra/com.xiaomi-miio#85]
Would it be possible to poll the light when using the Is Tuned On and Night Mode Is On status cards?

I have the new Xiaomi wall switches that use Bluetooth to communicate directly with the light's (Replicating the supplied remote).  I have motion sensors to turn the lights on/off but the wall switch must overide the flows (Motion sensors turn light on/off at night). 

There is currently no way to determine if the light was switched on/off via Bluetooth other than checking the lights status. This would work fine except there is a status update delay when lights are controlled outside of this app.

**Comment by jghaanstra** [comment]
How long is the delay? It works like this, when a Yeelight changes it's state (like power or color etc.) it broadcasts this event on the network. Homey is listening to these events and will update a state change if there is one. On a fast local network this should not take very long.

Adding extra polling would not improve the experience and will only cause extra traffic.

**Comment by chinswain** [comment]
> How long is the delay? It works like this, when a Yeelight changes it's state (like power or color etc.) it broadcasts this event on the network. Homey is listening to these events and will update a state change if there is one. On a fast local network this should not take very long.
> 
> Adding extra polling would not improve the experience and will only cause extra traffic.

I see, I'm sure I read Homey had to poll devices, they could not poll Homey. I'll do some testing this evening and see how long the delay is.

**Comment by jghaanstra** [comment]
Polling is implemented for the miio devices, not for the Yeelights anymore. I changed that a long long time ago. Yeelights should actually have it's own app but splitting them now is not really an option anymore.

**Comment by chinswain** [comment]
Very sorry, I meant the new "Night Mode" card you added - The on\off status is picked up by homey instantly, even when the light is controlled via the Bluetooth remote\wall switch.

I'm not seeing any night mode change at all unless it's done via a flow (or the lights device card). Is it possible to have this variable updated similar to on\off so I can determine if the user was switched night mode off via the Bluetooth wall switch?

**Comment by jghaanstra** [comment]
I see what you mean. I'll implement this in the next release.

**Comment by jghaanstra** [comment]
Fixed with release 2.11.6: https://github.com/jghaanstra/com.xiaomi-miio/releases/tag/2.11.6

**Comment by chinswain** [comment]
This is working perfectly in 2.11.6 - as it been changed in the latest commit?

**Comment by jghaanstra** [comment]
No
