### ISSUE TITLE
Homey not reachable 

### ISSUE THREAD

**Issue by Matt-Yao** [jghaanstra/com.xiaomi-miio#86]
This weekend my homey wasn't reachable anymore. After some troubleshooting i noticed that this app kept crashing.

Homey created an entry which states : app has stopped working. The developer has been notified.

Is it a known issue, i can't seem to find anything related.

**Comment by Matt-Yao** [comment]
After i disabled the app the issue didn't occure anymore.

**Comment by jghaanstra** [comment]
Which miio devices do you have connected and which of those are still actually reachable. I did not receive much crash reports but the ones I do receive are often related to devices that are no longer online.

**Comment by Matt-Yao** [comment]
At the moment i have 3 bulbs v2 and 2 led strips connected.

Just to be clear, homey wasn't reachable on it's IP address. Zigbee, zwave and flows   kept working.

After the notification the software was closed homey came back up.

**Comment by jghaanstra** [comment]
Hmmm, I have no such reports and the crash reports I receive are not about Yeelights. Since there are no reports from other users and I don't experience this myself I don't have much to go on.

I doubt it if this was really caused by my app. Could you try running the app from the command line and see if that gives more information to go on.

**Comment by Matt-Yao** [comment]
Ill turn the app back on and see what happens. Where should i start with this "cli" thing never done that before.

**Comment by jghaanstra** [comment]
> Where should i start with this "cli" thing never done that before.

https://community.athom.com/t/how-to-cli-install-method/198

**Comment by jghaanstra** [comment]
Any news on this?

**Comment by Matt-Yao** [comment]
Once ive updated the app to the latest version the issue seems to be gone. Thank you for your help. Ill mark this as closed.
