### ISSUE TITLE
Token storage on newer version

### ISSUE THREAD

**Issue by antoineQue** [jghaanstra/com.xiaomi-miio#87]
Hi everyone,

After succeeded in retrieving the appToken of my gateway using an older version of the Mi Home application, I would like to know how the app store this token in the newer versions (5.5.14) ? 
Like you said in the doc obtain_token, "the latest versions of the Mi Home smartphone app don't hold the token anymore", but it must be somewhere to be able to communicate securely.

Thanks !

**Comment by jghaanstra** [comment]
I'm sorry but I do not have a clue. It's probably saved somewhere deep down inside the code.
