### ISSUE TITLE
App constantly crashing

### ISSUE THREAD

**Issue by chinswain** [jghaanstra/com.xiaomi-miio#9]
Every few days the app (installed via the store) keeps crashing. The only connected device is an air filter.

Error message:
------------------
Hi!

Unfortunately, the app crashed while I was doing the following:

(...)

This is the stack trace:

Too many memwarns received

**Comment by jghaanstra** [comment]
Thank you for reporting. It's hard to debug this since I do not own this device but could you tell me which flows you are using for your air filter?

**Comment by jghaanstra** [comment]
@chinswain I have rebuild the app to be compatible with SDK2. I will push a beta release to the app store in the upcoming days. Would you be willing to test your air purifier with the release. It will require you to repair your device.

**Comment by jghaanstra** [comment]
@chinswain It's out in the beta channel, I would appreciate it if you could test it and supply me of feedback.

**Comment by dENNtoet** [comment]
@jghaanstra I have the exact same thing except with the yeelights. 

Hi!

Unfortunately, the app crashed while I was doing the following:

(...)

This is the stack trace:

/drivers/yeelights/device.js:228
                yeelights[id].socket.destroy();
                                    ^

TypeError: Cannot read property 'destroy' of null
    at Timeout.yeelights.(anonymous function).timeout.setTimeout [as _onTimeout] (/drivers/yeelights/device.js:228:37)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)

I also have yeelight that keeps going offline in Homey but works perfectly with the Yeelight app.

**Comment by jghaanstra** [comment]
Thanx for reporting @dENNtoet, I hope to have fixed this bug in the next release.

**Comment by chinswain** [comment]
It looks like the issue is fixed for me, haven't had a crash since installing the beta manually (and then via the app store).

**Comment by jghaanstra** [comment]
Thanx @chinswain, that confirms I have fixed the issues for the Humidifier and Air Purifier. @dENNtoet, I just publised release 2.3.1 to the beta channel which hopefully fixes those crashes and Yeelights showing as offline while they are not. Please let me know your findings.

**Comment by jghaanstra** [comment]
Since the problem of the original submitter has been fixed I'm closing this issue. Please open a new issue if you experience similar problems with the 2.3.1 or higher releases.
