### ISSUE TITLE
Add support for Aqara Wireless Relay Controller

### ISSUE THREAD

**Issue by PeetersJan** [jghaanstra/com.xiaomi-miio#90]
Could you add the relay controller to your app?

Add support for:
https://xiaomi-mi.com/sockets-and-sensors/Wireless Relay Controller/

![4c759c87-2de5-4c00-aeec-c13c67e51f15](https://user-images.githubusercontent.com/39444710/57979747-5a103880-7a22-11e9-8d4f-439558b9b516.jpg)

reference info:
Brand | Aqara
Model | LLKZMK11LM
Zigbee Model | lumi.relay.c2acn01
Wireless Connections | Zigbee

Probably, **adding the device to the wall switch driver will suffice**. 
When added as a (double) wall switch, it will be added as a generic device and thus not work correctly.
See: https://github.com/guyeeba/Hubitat/blob/master/Drivers/Aqara%20QBKG11LM-QBKG12LM-LLKZMK11LM.groovy
_____________________________________________________________________________________________________
"Documentation" |  https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1411
_____________________________________________________________________________________________________
A driver, based upon the wall switch driver  |  https://github.com/guyeeba/Hubitat/blob/master/Drivers/Aqara%20QBKG11LM-QBKG12LM-LLKZMK11LM.groovy

// two buttons, neutral required (QBKG12LM)
// reports:
// - endpoint 0x01, cluster 0x0006 (on/off),           attr 0x0000: Left button relay state (first octet 0x00=off, 0x01=on, the rest is Xiaomi-specific stuff)
// - endpoint 0x05, cluster 0x0012 (multistate input), attr 0x0055: Left button pushed (value = 0x0001)
// - endpoint 0x02, cluster 0x0002 (on/off),           attr 0x0000: Right button relay state (first octet 0x00=off, 0x01=on, the rest is Xiaomi-specific stuff)
// - endpoint 0x06, cluster 0x0012 (multistate input), attr 0x0055: Right button pushed (value = 0x0001)
// features:
// - Disconnect left button from relay: write uint8 (0x20) value (connected: 0x12, disconnected: 0xFE) to attribute 0xFF22 of endpoint 0x01, cluster 0x0000
// - Disconnect right button from relay: write uint8 (0x20) value (connected: 0x22, disconnected: 0xFE) to attribute 0xFF23 of endpoint 0x01, cluster 0x0000
____________________________________________________________________________________________________
Log file  |  https://github.com/dresden-elektronik/deconz-rest-plugin/files/3106838/xiaomi_relay.zip
_____________________________________________________________________________________________________
LLKZMK11LM
switch:
  - platform: "mqtt"
    state_topic: "zigbee2mqtt/<FRIENDLY_NAME>"
    availability_topic: "zigbee2mqtt/bridge/state"
    payload_off: "OFF"
    payload_on: "ON"
    value_template: "{{ value_json.state_l1 }}"
    command_topic: "zigbee2mqtt/<FRIENDLY_NAME>/l1/set"

switch:
  - platform: "mqtt"
    state_topic: "zigbee2mqtt/<FRIENDLY_NAME>"
    availability_topic: "zigbee2mqtt/bridge/state"
    payload_off: "OFF"
    payload_on: "ON"
    value_template: "{{ value_json.state_l2 }}"
    command_topic: "zigbee2mqtt/<FRIENDLY_NAME>/l2/set"

sensor:
  - platform: "mqtt"
    state_topic: "zigbee2mqtt/<FRIENDLY_NAME>"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "-"
    value_template: "{{ value_json.linkquality }}"
___________________________________________________________________________________________________
metadata {
    definition (name: "Aqara Wall Switch (QBKG11LM, QBKG12LM, neutral), Double relay (LLZKMK11LM)", namespace: "guyee", author: "Péter Gulyás") {
        capability "Configuration"
        capability "Refresh"
		capability "PushableButton"
		capability "DoubleTapableButton" // QBKG12LM only
		capability "Power Meter"
		capability "Energy Meter"
		capability "Temperature Measurement"

        command "childOn"
        command "childOff"
        command "childRefresh"
        command "recreateChildDevices"
        command "deleteChildren"
		// two buttons, neutral required (QBKG12LM)
		// reports:
		// - endpoint 0x01, cluster 0x0006 (on/off),           attr 0x0000: Left button relay state (first octet 0x00=off, 0x01=on, the rest is Xiaomi-specific stuff)
		// - endpoint 0x05, cluster 0x0012 (multistate input), attr 0x0055: Left button pushed (value = 0x0001)
		// - endpoint 0x02, cluster 0x0002 (on/off),           attr 0x0000: Right button relay state (first octet 0x00=off, 0x01=on, the rest is Xiaomi-specific stuff)
_____________________________________________________________________________________________________

![2019-05-19 10 33 08](https://user-images.githubusercontent.com/39444710/57979718-0dc4f880-7a22-11e9-973f-5a6666c99dea.jpg)
![2019-05-19 10 32 59](https://user-images.githubusercontent.com/39444710/57979719-0dc4f880-7a22-11e9-9323-0c414449d3a1.jpg)

**Comment by jghaanstra** [comment]
This is the repo for the Xiaomi Mi Home devices which communicate over WiFi. If you want a Zigbee device added you should request it in the Xiaomi Zigbee repo here: https://github.com/TedTolboom/com.xiaomi-mi-zigbee
