### ISSUE TITLE
new S6 vacuum robot

### ISSUE THREAD

**Issue by ic3cool** [jghaanstra/com.xiaomi-miio#92]
when adding with ip and token
i get device.getState is not a function

restartet homey, vac and also reinstalled the app.
no pro here so i dont know if there is any debug console to give you more heads up.
br.

**Comment by jghaanstra** [comment]
Looking at the error the S6 seems to have a different API which is not supported. As the miio libary is not maintained anymore it will probably not be supported in the future as well.

**Comment by ic3cool** [comment]
oh thats not happy news, will that lib be replaced with something else?
is it this you referring to?
https://github.com/jghaanstra/com.xiaomi-miio/tree/master/node_modules/miio

**Comment by jghaanstra** [comment]
Yep, that the library. The source is here: https://github.com/aholstenson/miio

I dont see this getting replaced any time soon. Someone with a lot of time and coding skills would have to pick that up (and that aint me).

**Comment by jghaanstra** [comment]
@ic3cool I just pushed an update to Github that might add support for the S6. Do you know how to test this using a command line install?

**Comment by ic3cool** [comment]
Good news. Never done command line install in this case.
Few pointers would be nice.

I guess node.js in place an pull your updated code for a starter?

**Comment by jghaanstra** [comment]
This holds all information you need: https://community.athom.com/t/how-to-cli-install-method/198

**Comment by ic3cool** [comment]
> This holds all information you need: https://community.athom.com/t/how-to-cli-install-method/198

sweet i will try to set up an env asap.

**Comment by ic3cool** [comment]
yes that did work!
have not tried everything and looked for errors.
but i was able to "add" robot. 
Connect to it.
Start clean.
And dock it again.
