### ISSUE TITLE
Xiaomi ClearGrass Air Monitor

### ISSUE THREAD

**Issue by GreyEarl** [jghaanstra/com.xiaomi-miio#93]
Hi, 

As shortly discussed on Slack a while ago, I want to see if we could get the Xiaomi ClearGrass Air Monitor working on Homey. Especially when someone already implemented the device in Home Assistent. I received the device a few days ago and what a machine it is.

As it turns out, 99% of the code was copied from the Xiaomi Air Quality Monitor:
https://community.home-assistant.io/t/xiaomi-cleargrass-air-detector/112315

**Device name:** ClearGrass Air Monitor
**Model:** CGS1
**Manufacturer":** Qingping Technology Co. Ltd.

The device is generating the following values:

- PM2.5
- CO2
- TVOC
- Temperature
- Humidity

I want to contribute as much as I can, like packet capturing. According to the Home Assistant implementator he found out the next parameters in the following order: ‘battery’, ‘battery_state’, ‘co2’, ‘humidity’, ‘pm25’ , ‘temperature’, ‘tvoc’.

Please let me know what you need and will make sure you get the information.

**Comment by jghaanstra** [comment]
I can not add it to my app if it is not added to the nodejs miio library. Since that is no longer maintained I do expect this device will be supported.

**Comment by GreyEarl** [comment]
@jghaanstra Thanks for replying! I know the problem with the miio library, I probably misread you reply on Slack.

What about this Python based library? https://github.com/rytilahti/python-miio
This library seems to be covering more devices and is maintained. Or are you stuck with Node?

**Comment by jghaanstra** [comment]
Since Homey is nodejs we are stuck with that. I lack the coding skills to develop the miio library myself so you are out of luck I guess.

**Comment by GreyEarl** [comment]
For the ones who is interested in this device on Homey. Through Home Assistant I managed to get the device fully working in Homey. So, if you have an HA instance you can try that. I made a [fork](https://github.com/GreyEarl/io.homeassistant) of the io.homeassistant app for Homey.

![image](https://user-images.githubusercontent.com/33351068/72730140-09dd0d80-3b91-11ea-9c4b-37e0f08f79cb.png)

![image](https://user-images.githubusercontent.com/33351068/72730186-2416eb80-3b91-11ea-84f5-0de789f1cfe4.png)

**Comment by EricBorland** [comment]
Maybe my PR #122 would work for that model as well...

**Comment by jghaanstra** [comment]
Closing old issues. This app needs financial support for further development and upgrade to SDK3. For more info see: https://community.homey.app/t/app-pro-xiaomi-mi-home-app-for-wifi-devices/118/943
