### ISSUE TITLE
Roborock S5 ignoring zone when flow starts

### ISSUE THREAD

**Issue by Andi2k11** [jghaanstra/com.xiaomi-miio#94]
When adding my Roborock to a flow and using Start Zone Cleaning the flow ignores my added zones.

See image. Thats a flow that should make the Roborock clean my hallway. But every time the flow starts, the Roborock cleans the whole house. I have tried to use different coordinates for diffrent rooms but still it only cleans the whole house.

![image](https://user-images.githubusercontent.com/6905721/59036293-457bcf00-886f-11e9-9c47-71a5ba9a256a.png)

Am I missing something? The coordinates I got from the app FloeVac. and my home is using the latest version of the app from apps.athom.com

**Comment by jghaanstra** [comment]
Could you try to remove the "Turn on" card from the flow and move the "Start zone cleaning" to the top of the flow and add a delay of 5 seconds for setting the Fan Power to turbo.

**Comment by Andi2k11** [comment]
That seems to be working. Going to check my other flows.

**Comment by jghaanstra** [comment]
If you experience more issues please let me know. Closing this for now.
