### ISSUE TITLE
Device is unavailable

### ISSUE THREAD

**Issue by bjornand1** [jghaanstra/com.xiaomi-miio#96]
Hi, I have been able to extract the token from my Mi Air Purifier 2S and add it as a device to my Homey. However, I just get a red triangle and the message that the device is unavailable. Any ideas how to fix this?

**Comment by jghaanstra** [comment]
Do you know how to run the app from the command line using the `athom app run` command? This should give me more debug logging on what is going on.

**Comment by bjornand1** [comment]
Hi, thanks for your reply. First of all, I realized that the token I used was wrong, I had extracted that from an iPhone backup, but I now have installed an Android emulator and obtained it that way. However, the outcome is the same; the air purifier gets successfully added, but still shows up as unavailable/offline, even of the Mi app sees it without any problems.

As for command running, I have never done that.

**Comment by bjornand1** [comment]
Hi again, I have now installed the athom cli and can run commands in Terminal on my Mac. However, I am not sure how to install and run the Xiaomi Mi Home app this way. Could you offer instructions?

**Comment by jghaanstra** [comment]
See https://community.athom.com/t/how-to-cli-install-method/198

**Comment by bjornand1** [comment]
Thanks, this is what I did, but whatever combination of athom app install and name/url of your app, I never hit the right syntax...

**Comment by jghaanstra** [comment]
Extract the zip file you downloaded from Github containing my app. Use the command line to enter this folder and run the command `athom app run`. This will ask for permission and after permission has been granted will run the app. After that you should see a debug log on the command line which hopefully will give me more information.

**Comment by bjornand1** [comment]
Hah, I don't know if this is a coincidence, but just as I ran the app in the command line, the unit showed up in the iPhone Homey app without errors now!

**Comment by jghaanstra** [comment]
Strange. I'm closing this for now, if you experience more issues just post them here.
