### ISSUE TITLE
Suggestion for Instruction for Non-Jailbroken iOS users

### ISSUE THREAD

**Issue by mediter** [jghaanstra/com.xiaomi-miio#97]
use of free open source softwares

1. backup extraction
[iPhoneBackupTools](https://github.com/richinfante/iphonebackuptools) by [Rich Infante](https://github.com/richinfante)

2. sqlite database
sqlite3 cli

3. [hexyl](https://github.com/sharkdp/hexyl) for output decrypted token as text

Please refer to [ios-token-without-reset](https://github.com/mediter/miio/blob/master/docs/ios-token-without-reset.md) for detailed process of applying these software for our purpose

**Comment by jghaanstra** [comment]
Thanx, actually just added a link to one of those tools yesterday. I now added another link to your repo.
