### ISSUE TITLE
Cannot find Yeelight Desk Light anymore

### ISSUE THREAD

**Issue by Flight777** [jghaanstra/com.xiaomi-miio#98]
Recently the app does not recognise or refind my Yeelight Desk Light anymore, even after multiple resets of the device (and enabling LAN mode in the Yeelight app) it is not finding it :(

**Comment by jghaanstra** [comment]
Please use the support forum for these kind of issue. Github is intended for actual bugs and feature requests.

**Comment by Flight777** [comment]
Because it has been working on previous versions of the app, I suppose it is/was a bug... as all other Yeelights are still working properly...

**Comment by jghaanstra** [comment]
I'm pretty sure it's something specific in your setup as about 1600 other users do not have this issue ... :-)

Just post it on the forums and I (or someone from the community) will help you from there.

(have you made sure LAN mode is enabled, it gets disabled when you reset the light)
