### ISSUE TITLE
App crashing randomly

### ISSUE THREAD

**Issue by shaarkys** [jghaanstra/com.xiaomi-miio#99]
Diagnostics data : cc6191ca-ce4e-460c-a4ac-2532b104108c

**Comment by jghaanstra** [comment]
I'm gonna need more info. The crash reports often don't contain anything (like in your case). 

What devices are you using and at what moments does the app crash.

**Comment by shaarkys** [comment]
Hi,

re "what devices" : 

1x homey:app:com.xiaomi-miio — gateway (not ZigBee)
3x  homey:app:com.xiaomi-mi — weather (Aqara temp)
**multiple**  homey:app:com.xiaomi-mi — sensor_switch.aq2 (both new and previous version)
homey:app:com.xiaomi-mi — sensor_magnet.aq2
homey:app:com.xiaomi-mi — vibration.aq1
**multiple** homey:app:com.xiaomi-miio — yeelights (not ZigBee)
**multiple** homey:app:com.xiaomi-mi — sensor_motion
homey:app:com.xiaomi-mi — sens

re "when" : two times right after reboot, another 4 times randomly

_Note : some of the Aqara temperature devices are not responding and need to be wake-up - not sure if it's not related, some of them sleeping for 3 weeks_

**Comment by jghaanstra** [comment]
The Xiaomi Zigbee devices are a different app and unrelated to this. I do see some issues with Yeelights for users with a not to stable internet connection where the connection between Homey and an Yeelight make the app crash. How is your WiFi, is it stable?

With this info I still can't do much about it. I also don't seem to be able to fix the crashes when the wifi is not stable. In other words, there is not much I can do for you.

**Comment by shaarkys** [comment]
I know ZigBee is unrelated, but better to provide all information. As for Wifi - I do have stable signal, however I do have two APs with roaming capabilities in between. So may happen that some of the lights may roam as the signal fluctuates. Strange is that I configured flaw, when apps crash, to automatically restart it - which seems doesn't work anyway. Is there any support from app side itself required for this flow to work ? ... but this is probably OT question already.

Can I help anyhow on debugging ?

**Comment by jghaanstra** [comment]
What you could do is run the app from the command line with `athom app run` and let it run for a while until it crashes and then post the last part of the console logging. Perhaps that gives me more clues why it crashes and what I can do to fix it (if I even can).

If you have never run or installed an Homey app from command line, here are instructions: https://community.athom.com/t/how-to-cli-install-method/198

**Comment by shaarkys** [comment]
I will let you know, if I catch something.
Btw, I see following error just by lunching it but everything works normal. I assume this is not an issue, or ?

`019-07-21 23:04:58 [log] [XiaomiMiioApp] Initializing Xiaomi Mi Home app ...
(node:29219) UnhandledPromiseRejectionWarning: Error: invalid_capability
    at Remote IPC Process

(node:29219) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:29219) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:29219) UnhandledPromiseRejectionWarning: Error: invalid_capability
    at Remote IPC Process

(node:29219) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:29219) UnhandledPromiseRejectionWarning: Error: invalid_capability
    at Remote IPC Process

(node:29219) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:29219) UnhandledPromiseRejectionWarning: Error: invalid_capability
    at Remote IPC Process`

**Comment by jghaanstra** [comment]
Could you list the various types of Yeelights which you have connected through my app?

**Comment by shaarkys** [comment]
Sure, I have two types of Yeelights connected : 
3x Xiaomi Mi LED Ceiling Light 20369
5x Xiaomi YLXD01YL

**Comment by jghaanstra** [comment]
I have pushed some changes to github. Could you `athom app run` with this release again and see if it gives me more details (and at least has solved the invalid_capability errors). If it has it would be great if you could keep the app running from the command line until it crashes.

**Comment by shaarkys** [comment]
Thank you, running 2.12.2 now , after launching it : 

`2019-08-14 17:01:47 [log] [XiaomiMiioApp] Initializing Xiaomi Mi Home app ...
(node:23322) UnhandledPromiseRejectionWarning: Error: invalid_capability
    at Remote IPC Process

(node:23322) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:23322) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:23322) UnhandledPromiseRejectionWarning: Error: invalid_capability
    at Remote IPC Process

(node:23322) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:23322) UnhandledPromiseRejectionWarning: Error: invalid_capability
    at Remote IPC Process

(node:23322) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:23322) UnhandledPromiseRejectionWarning: Error: invalid_capability
    at Remote IPC Process

(node:23322) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:23322) UnhandledPromiseRejectionWarning: Error: invalid_capability
    at Remote IPC Process

(node:23322) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
(node:23322) UnhandledPromiseRejectionWarning: Error: invalid_capability
    at Remote IPC Process

(node:23322) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
(node:23322) UnhandledPromiseRejectionWarning: Error: invalid_capability
    at Remote IPC Process

(node:23322) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 7)
(node:23322) UnhandledPromiseRejectionWarning: Error: invalid_capability
    at Remote IPC Process

(node:23322) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)
(node:23322) UnhandledPromiseRejectionWarning: Error: invalid_capability
    at Remote IPC Process

(node:23322) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 9)
(node:23322) UnhandledPromiseRejectionWarning: Error: invalid_capability
    at Remote IPC Process

(node:23322) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 10)
(node:23322) UnhandledPromiseRejectionWarning: Error: invalid_capability
    at Remote IPC Process

(node:23322) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 11)
(node:23322) UnhandledPromiseRejectionWarning: Error: invalid_capability
    at Remote IPC Process

(node:23322) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 12)
(node:23322) UnhandledPromiseRejectionWarning: Error: invalid_capability
    at Remote IPC Process

(node:23322) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 13)
(node:23322) UnhandledPromiseRejectionWarning: Error: invalid_capability
    at Remote IPC Process

(node:23322) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 14)
(node:23322) UnhandledPromiseRejectionWarning: Error: invalid_capability
    at Remote IPC Process

(node:23322) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 15)
(node:23322) UnhandledPromiseRejectionWarning: Error: invalid_capability
    at Remote IPC Process

(node:23322) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 16)`

**Comment by jghaanstra** [comment]
This may take a while before I get it right. I just pushed a change to GitHub which hopefully solved the invalid_capability. Could you give it a swing with this version.

**Comment by shaarkys** [comment]
No problem at all. Another one while running in console on 2.12.2 - going to upgrade now.

`2019-08-14 20:14:41 [log] [ManagerDrivers] [yeelights] [6] Unable to process message because of error: SyntaxError: Unexpected token { in JSON at position 42
2019-08-14 20:23:33 [log] [ManagerDrivers] [yeelights] [5] Yeelight - error on socket: Error: read EHOSTUNREACH`

**Comment by shaarkys** [comment]
And I re-downloaded the same version published 2 hours ago, still on 2.12.2

`2019-08-14 21:16:51 [log] [XiaomiMiioApp] Initializing Xiaomi Mi Home app ...
2019-08-14 21:16:58 [log] [ManagerDrivers] [yeelights] [5] Yeelight - error on socket: Error: connect EHOSTUNREACH 10.0.0.155:55443
(node:1687) UnhandledPromiseRejectionWarning: Error: invalid_capability
    at Remote IPC Process

(node:1687) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1687) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:1687) UnhandledPromiseRejectionWarning: Error: invalid_capability
    at Remote IPC Process

(node:1687) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:1687) UnhandledPromiseRejectionWarning: Error: invalid_capability
    at Remote IPC Process

(node:1687) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:1687) UnhandledPromiseRejectionWarning: Error: invalid_capability
    at Remote IPC Process

(node:1687) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:1687) UnhandledPromiseRejectionWarning: Error: invalid_capability
    at Remote IPC Process

(node:1687) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
(node:1687) UnhandledPromiseRejectionWarning: Error: invalid_capability
    at Remote IPC Process`

**Comment by jghaanstra** [comment]
The `Unable to process message because of error: SyntaxError: Unexpected token { in JSON at position 42` and `EHOSTUNREACH` are common errors. The first is caused by the Yeelight status updates sometimes not being formatted correctly and the second when a light can not be reached (because the power has been cut or there is a network hickup).

It sucks that the invalid_capability error is still there as it will make actual debugging harder. This is probably caused because a Yeelight was paired before a specific capability was added later on and the Yeelight was not re-paired to included this capability.

I'm thinking of a way to get an overview of your paired lights and their capabilities. I'll be creating a debug branch for this. As mentioned, this is probably gonna be a long ride to get to the bottom. I'll post back when I have something to test.

**Comment by shaarkys** [comment]
> 
> 
>the second when a light can not be reached (because the power has been cut or there is a network hickup).

Yep, my daughter press the switch ;-)

> It sucks that the invalid_capability error is still there as it will make actual debugging harder. This is probably caused because a Yeelight was paired before a specific capability was added later on and the Yeelight was not re-paired to included this capability.
 
Well, actually it's very fresh installation, like 3-4 weeks old and I haven't noticed any new capability being added or eg. official Yeelight application being updated to reflect that etc.

No problem with testing, when I will be nearby.

**Comment by jghaanstra** [comment]
I have created a debug branch which should spit out all your Yeelights including their capabilities to the console. It might even have fixed the invalid_capabilities errors as I have added extra checks if a capabilities is actually available for the device.

https://github.com/jghaanstra/com.xiaomi-miio/tree/debug

**Comment by shaarkys** [comment]
Seems it's gone ? ;-)

`─────────────── Logging stdout & stderr ───────────────
2019-08-14 22:08:24 [log] [XiaomiMiioApp] Initializing Xiaomi Mi Home app ...
2019-08-14 22:08:27 [log] [ManagerDrivers] [yeelights] [0] Initializing device: "Corridor light" of model "ceiling" with capabilities:
2019-08-14 22:08:27 [log] [ManagerDrivers] [yeelights] [0] [ 'onoff', 'dim', 'light_temperature', 'light_mode', 'night_mode' ]
2019-08-14 22:08:27 [log] [ManagerDrivers] [yeelights] [1] Initializing device: "Upstairs corridor light" of model "ceiling" with capabilities:
2019-08-14 22:08:27 [log] [ManagerDrivers] [yeelights] [1] [ 'onoff', 'dim', 'light_temperature', 'light_mode', 'night_mode' ]
2019-08-14 22:08:27 [log] [ManagerDrivers] [yeelights] [2] Initializing device: "Main entry light" of model "ceiling" with capabilities:
2019-08-14 22:08:27 [log] [ManagerDrivers] [yeelights] [2] [ 'onoff', 'dim', 'light_temperature', 'light_mode', 'night_mode' ]
2019-08-14 22:08:27 [log] [ManagerDrivers] [yeelights] [3] Initializing device: "Emma's room light" of model "ceiling" with capabilities:
2019-08-14 22:08:27 [log] [ManagerDrivers] [yeelights] [3] [ 'onoff', 'dim', 'light_temperature', 'light_mode', 'night_mode' ]
2019-08-14 22:08:27 [log] [ManagerDrivers] [yeelights] [4] Initializing device: "Bathroom light" of model "ceiling" with capabilities:
2019-08-14 22:08:27 [log] [ManagerDrivers] [yeelights] [4] [ 'onoff', 'dim', 'light_temperature', 'light_mode', 'night_mode' ]
2019-08-14 22:08:27 [log] [ManagerDrivers] [yeelights] [5] Initializing device: "Bedroom light" of model "ceiling" with capabilities:
2019-08-14 22:08:27 [log] [ManagerDrivers] [yeelights] [5] [ 'onoff', 'dim', 'light_temperature', 'light_mode', 'night_mode' ]
2019-08-14 22:08:27 [log] [ManagerDrivers] [yeelights] [6] Initializing device: "Simon's light" of model "ceiling" with capabilities:
2019-08-14 22:08:27 [log] [ManagerDrivers] [yeelights] [6] [ 'onoff', 'dim', 'light_temperature', 'light_mode', 'night_mode' ]
2019-08-14 22:08:27 [log] [ManagerDrivers] [yeelights] [7] Initializing device: "Garage light" of model "ceiling" with capabilities:
2019-08-14 22:08:27 [log] [ManagerDrivers] [yeelights] [7] [ 'onoff', 'dim', 'light_temperature', 'light_mode', 'night_mode' ]
2019-08-14 22:08:31 [log] [ManagerDrivers] [yeelights] [5] Yeelight - error on socket: Error: connect EHOSTUNREACH 10.0.0.155:55443`

**Comment by shaarkys** [comment]
> 2019-08-14 22:08:24 [log] [XiaomiMiioApp] Initializing Xiaomi Mi Home app ...
2019-08-14 22:08:27 [log] [ManagerDrivers] [yeelights] [0] Initializing device: "Corridor light" of model "ceiling" with capabilities:
2019-08-14 22:08:27 [log] [ManagerDrivers] [yeelights] [0] [ 'onoff', 'dim', 'light_temperature', 'light_mode', 'night_mode' ]
2019-08-14 22:08:27 [log] [ManagerDrivers] [yeelights] [1] Initializing device: "Upstairs corridor light" of model "ceiling" with capabilities:
2019-08-14 22:08:27 [log] [ManagerDrivers] [yeelights] [1] [ 'onoff', 'dim', 'light_temperature', 'light_mode', 'night_mode' ]
2019-08-14 22:08:27 [log] [ManagerDrivers] [yeelights] [2] Initializing device: "Main entry light" of model "ceiling" with capabilities:
2019-08-14 22:08:27 [log] [ManagerDrivers] [yeelights] [2] [ 'onoff', 'dim', 'light_temperature', 'light_mode', 'night_mode' ]
2019-08-14 22:08:27 [log] [ManagerDrivers] [yeelights] [3] Initializing device: "Emma's room light" of model "ceiling" with capabilities:
2019-08-14 22:08:27 [log] [ManagerDrivers] [yeelights] [3] [ 'onoff', 'dim', 'light_temperature', 'light_mode', 'night_mode' ]
2019-08-14 22:08:27 [log] [ManagerDrivers] [yeelights] [4] Initializing device: "Bathroom light" of model "ceiling" with capabilities:
2019-08-14 22:08:27 [log] [ManagerDrivers] [yeelights] [4] [ 'onoff', 'dim', 'light_temperature', 'light_mode', 'night_mode' ]
2019-08-14 22:08:27 [log] [ManagerDrivers] [yeelights] [5] Initializing device: "Bedroom light" of model "ceiling" with capabilities:
2019-08-14 22:08:27 [log] [ManagerDrivers] [yeelights] [5] [ 'onoff', 'dim', 'light_temperature', 'light_mode', 'night_mode' ]
2019-08-14 22:08:27 [log] [ManagerDrivers] [yeelights] [6] Initializing device: "Simon's light" of model "ceiling" with capabilities:
2019-08-14 22:08:27 [log] [ManagerDrivers] [yeelights] [6] [ 'onoff', 'dim', 'light_temperature', 'light_mode', 'night_mode' ]
2019-08-14 22:08:27 [log] [ManagerDrivers] [yeelights] [7] Initializing device: "Garage light" of model "ceiling" with capabilities:
2019-08-14 22:08:27 [log] [ManagerDrivers] [yeelights] [7] [ 'onoff', 'dim', 'light_temperature', 'light_mode', 'night_mode' ]
2019-08-14 22:08:31 [log] [ManagerDrivers] [yeelights] [5] Yeelight - error on socket: Error: connect EHOSTUNREACH 10.0.0.155:55443

**Comment by jghaanstra** [comment]
Ok, thats a step forward. Could you run this version for a while and post the console output from the moment it crashes.

**Comment by shaarkys** [comment]
I will try, however don't have PC running all the time, so probably over the day or afternoon when returning from work, Anyway, thank you very much so far ;-)

**Comment by shaarkys** [comment]
Seems it's more stable now, thank you
